-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity unet_pvm_top_custom_pvm_layer_config_enc5_s is
port (
    m_axi_gmem2_0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem2_0_AWREADY : IN STD_LOGIC;
    m_axi_gmem2_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem2_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem2_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem2_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem2_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_0_WVALID : OUT STD_LOGIC;
    m_axi_gmem2_0_WREADY : IN STD_LOGIC;
    m_axi_gmem2_0_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem2_0_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_0_WLAST : OUT STD_LOGIC;
    m_axi_gmem2_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem2_0_ARREADY : IN STD_LOGIC;
    m_axi_gmem2_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem2_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem2_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem2_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem2_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_0_RVALID : IN STD_LOGIC;
    m_axi_gmem2_0_RREADY : OUT STD_LOGIC;
    m_axi_gmem2_0_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem2_0_RLAST : IN STD_LOGIC;
    m_axi_gmem2_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_gmem2_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_0_BVALID : IN STD_LOGIC;
    m_axi_gmem2_0_BREADY : OUT STD_LOGIC;
    m_axi_gmem2_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    proj_weights : IN STD_LOGIC_VECTOR (63 downto 0);
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_ce0 : OUT STD_LOGIC;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_d0 : OUT STD_LOGIC_VECTOR (17 downto 0);
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_q0 : IN STD_LOGIC_VECTOR (17 downto 0);
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_we0 : OUT STD_LOGIC;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_ce1 : OUT STD_LOGIC;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_d1 : OUT STD_LOGIC_VECTOR (17 downto 0);
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_q1 : IN STD_LOGIC_VECTOR (17 downto 0);
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_we1 : OUT STD_LOGIC;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_ce0 : OUT STD_LOGIC;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_d0 : OUT STD_LOGIC_VECTOR (17 downto 0);
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_q0 : IN STD_LOGIC_VECTOR (17 downto 0);
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_we0 : OUT STD_LOGIC;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_ce1 : OUT STD_LOGIC;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_d1 : OUT STD_LOGIC_VECTOR (17 downto 0);
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_q1 : IN STD_LOGIC_VECTOR (17 downto 0);
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_we1 : OUT STD_LOGIC;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_ce0 : OUT STD_LOGIC;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_d0 : OUT STD_LOGIC_VECTOR (17 downto 0);
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_q0 : IN STD_LOGIC_VECTOR (17 downto 0);
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_we0 : OUT STD_LOGIC;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_ce1 : OUT STD_LOGIC;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_d1 : OUT STD_LOGIC_VECTOR (17 downto 0);
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_q1 : IN STD_LOGIC_VECTOR (17 downto 0);
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_we1 : OUT STD_LOGIC;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_ce0 : OUT STD_LOGIC;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_d0 : OUT STD_LOGIC_VECTOR (17 downto 0);
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_q0 : IN STD_LOGIC_VECTOR (17 downto 0);
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_we0 : OUT STD_LOGIC;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_ce1 : OUT STD_LOGIC;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_d1 : OUT STD_LOGIC_VECTOR (17 downto 0);
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_q1 : IN STD_LOGIC_VECTOR (17 downto 0);
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_we1 : OUT STD_LOGIC;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_ce0 : OUT STD_LOGIC;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_d0 : OUT STD_LOGIC_VECTOR (17 downto 0);
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_q0 : IN STD_LOGIC_VECTOR (17 downto 0);
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_we0 : OUT STD_LOGIC;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_ce1 : OUT STD_LOGIC;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_d1 : OUT STD_LOGIC_VECTOR (17 downto 0);
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_q1 : IN STD_LOGIC_VECTOR (17 downto 0);
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_we1 : OUT STD_LOGIC;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_ce0 : OUT STD_LOGIC;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_d0 : OUT STD_LOGIC_VECTOR (17 downto 0);
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_q0 : IN STD_LOGIC_VECTOR (17 downto 0);
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_we0 : OUT STD_LOGIC;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_ce1 : OUT STD_LOGIC;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_d1 : OUT STD_LOGIC_VECTOR (17 downto 0);
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_q1 : IN STD_LOGIC_VECTOR (17 downto 0);
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_we1 : OUT STD_LOGIC;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_ce0 : OUT STD_LOGIC;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_d0 : OUT STD_LOGIC_VECTOR (17 downto 0);
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_q0 : IN STD_LOGIC_VECTOR (17 downto 0);
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_we0 : OUT STD_LOGIC;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_ce1 : OUT STD_LOGIC;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_d1 : OUT STD_LOGIC_VECTOR (17 downto 0);
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_q1 : IN STD_LOGIC_VECTOR (17 downto 0);
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_we1 : OUT STD_LOGIC;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_ce0 : OUT STD_LOGIC;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_d0 : OUT STD_LOGIC_VECTOR (17 downto 0);
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_q0 : IN STD_LOGIC_VECTOR (17 downto 0);
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_we0 : OUT STD_LOGIC;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_ce1 : OUT STD_LOGIC;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_d1 : OUT STD_LOGIC_VECTOR (17 downto 0);
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_q1 : IN STD_LOGIC_VECTOR (17 downto 0);
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_we1 : OUT STD_LOGIC;
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    proj_weights_ap_vld : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC );
end;


architecture behav of unet_pvm_top_custom_pvm_layer_config_enc5_s is 
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_lv18_0 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_logic_1 : STD_LOGIC := '1';

attribute shreg_extract : string;
    signal custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_ap_start : STD_LOGIC;
    signal custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_ap_done : STD_LOGIC;
    signal custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_ap_continue : STD_LOGIC;
    signal custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_ap_idle : STD_LOGIC;
    signal custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_ap_ready : STD_LOGIC;
    signal custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_AWVALID : STD_LOGIC;
    signal custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_WVALID : STD_LOGIC;
    signal custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_WDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_WSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_WLAST : STD_LOGIC;
    signal custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARVALID : STD_LOGIC;
    signal custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_RREADY : STD_LOGIC;
    signal custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_BREADY : STD_LOGIC;
    signal custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_ce0 : STD_LOGIC;
    signal custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_address1 : STD_LOGIC_VECTOR (6 downto 0);
    signal custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_ce1 : STD_LOGIC;
    signal custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_ce0 : STD_LOGIC;
    signal custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_address1 : STD_LOGIC_VECTOR (6 downto 0);
    signal custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_ce1 : STD_LOGIC;
    signal custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_ce0 : STD_LOGIC;
    signal custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_address1 : STD_LOGIC_VECTOR (6 downto 0);
    signal custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_ce1 : STD_LOGIC;
    signal custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_ce0 : STD_LOGIC;
    signal custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_address1 : STD_LOGIC_VECTOR (6 downto 0);
    signal custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_ce1 : STD_LOGIC;
    signal custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_ce0 : STD_LOGIC;
    signal custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_we0 : STD_LOGIC;
    signal custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_d0 : STD_LOGIC_VECTOR (17 downto 0);
    signal custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_ce0 : STD_LOGIC;
    signal custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_we0 : STD_LOGIC;
    signal custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_d0 : STD_LOGIC_VECTOR (17 downto 0);
    signal custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_ce0 : STD_LOGIC;
    signal custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_we0 : STD_LOGIC;
    signal custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_d0 : STD_LOGIC_VECTOR (17 downto 0);
    signal custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_ce0 : STD_LOGIC;
    signal custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_we0 : STD_LOGIC;
    signal custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_d0 : STD_LOGIC_VECTOR (17 downto 0);

    component unet_pvm_top_custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        m_axi_gmem2_0_AWVALID : OUT STD_LOGIC;
        m_axi_gmem2_0_AWREADY : IN STD_LOGIC;
        m_axi_gmem2_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem2_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem2_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem2_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem2_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem2_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem2_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem2_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem2_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem2_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem2_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem2_0_WVALID : OUT STD_LOGIC;
        m_axi_gmem2_0_WREADY : IN STD_LOGIC;
        m_axi_gmem2_0_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem2_0_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem2_0_WLAST : OUT STD_LOGIC;
        m_axi_gmem2_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem2_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem2_0_ARVALID : OUT STD_LOGIC;
        m_axi_gmem2_0_ARREADY : IN STD_LOGIC;
        m_axi_gmem2_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem2_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem2_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem2_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem2_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem2_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem2_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem2_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem2_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem2_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem2_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem2_0_RVALID : IN STD_LOGIC;
        m_axi_gmem2_0_RREADY : OUT STD_LOGIC;
        m_axi_gmem2_0_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem2_0_RLAST : IN STD_LOGIC;
        m_axi_gmem2_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem2_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
        m_axi_gmem2_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem2_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem2_0_BVALID : IN STD_LOGIC;
        m_axi_gmem2_0_BREADY : OUT STD_LOGIC;
        m_axi_gmem2_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem2_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem2_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        proj_weights : IN STD_LOGIC_VECTOR (63 downto 0);
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_ce0 : OUT STD_LOGIC;
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_q0 : IN STD_LOGIC_VECTOR (17 downto 0);
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_ce1 : OUT STD_LOGIC;
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_q1 : IN STD_LOGIC_VECTOR (17 downto 0);
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_ce0 : OUT STD_LOGIC;
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_q0 : IN STD_LOGIC_VECTOR (17 downto 0);
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_ce1 : OUT STD_LOGIC;
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_q1 : IN STD_LOGIC_VECTOR (17 downto 0);
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_ce0 : OUT STD_LOGIC;
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_q0 : IN STD_LOGIC_VECTOR (17 downto 0);
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_ce1 : OUT STD_LOGIC;
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_q1 : IN STD_LOGIC_VECTOR (17 downto 0);
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_ce0 : OUT STD_LOGIC;
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_q0 : IN STD_LOGIC_VECTOR (17 downto 0);
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_ce1 : OUT STD_LOGIC;
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_q1 : IN STD_LOGIC_VECTOR (17 downto 0);
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_ce0 : OUT STD_LOGIC;
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_we0 : OUT STD_LOGIC;
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_d0 : OUT STD_LOGIC_VECTOR (17 downto 0);
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_ce0 : OUT STD_LOGIC;
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_we0 : OUT STD_LOGIC;
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_d0 : OUT STD_LOGIC_VECTOR (17 downto 0);
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_ce0 : OUT STD_LOGIC;
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_we0 : OUT STD_LOGIC;
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_d0 : OUT STD_LOGIC_VECTOR (17 downto 0);
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_ce0 : OUT STD_LOGIC;
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_we0 : OUT STD_LOGIC;
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_d0 : OUT STD_LOGIC_VECTOR (17 downto 0) );
    end component;



begin
    custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0 : component unet_pvm_top_custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_ap_start,
        ap_done => custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_ap_done,
        ap_continue => custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_ap_continue,
        ap_idle => custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_ap_idle,
        ap_ready => custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_ap_ready,
        m_axi_gmem2_0_AWVALID => custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_AWVALID,
        m_axi_gmem2_0_AWREADY => ap_const_logic_0,
        m_axi_gmem2_0_AWADDR => custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_AWADDR,
        m_axi_gmem2_0_AWID => custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_AWID,
        m_axi_gmem2_0_AWLEN => custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_AWLEN,
        m_axi_gmem2_0_AWSIZE => custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_AWSIZE,
        m_axi_gmem2_0_AWBURST => custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_AWBURST,
        m_axi_gmem2_0_AWLOCK => custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_AWLOCK,
        m_axi_gmem2_0_AWCACHE => custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_AWCACHE,
        m_axi_gmem2_0_AWPROT => custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_AWPROT,
        m_axi_gmem2_0_AWQOS => custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_AWQOS,
        m_axi_gmem2_0_AWREGION => custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_AWREGION,
        m_axi_gmem2_0_AWUSER => custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_AWUSER,
        m_axi_gmem2_0_WVALID => custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_WVALID,
        m_axi_gmem2_0_WREADY => ap_const_logic_0,
        m_axi_gmem2_0_WDATA => custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_WDATA,
        m_axi_gmem2_0_WSTRB => custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_WSTRB,
        m_axi_gmem2_0_WLAST => custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_WLAST,
        m_axi_gmem2_0_WID => custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_WID,
        m_axi_gmem2_0_WUSER => custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_WUSER,
        m_axi_gmem2_0_ARVALID => custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARVALID,
        m_axi_gmem2_0_ARREADY => m_axi_gmem2_0_ARREADY,
        m_axi_gmem2_0_ARADDR => custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARADDR,
        m_axi_gmem2_0_ARID => custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARID,
        m_axi_gmem2_0_ARLEN => custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARLEN,
        m_axi_gmem2_0_ARSIZE => custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARSIZE,
        m_axi_gmem2_0_ARBURST => custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARBURST,
        m_axi_gmem2_0_ARLOCK => custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARLOCK,
        m_axi_gmem2_0_ARCACHE => custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARCACHE,
        m_axi_gmem2_0_ARPROT => custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARPROT,
        m_axi_gmem2_0_ARQOS => custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARQOS,
        m_axi_gmem2_0_ARREGION => custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARREGION,
        m_axi_gmem2_0_ARUSER => custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARUSER,
        m_axi_gmem2_0_RVALID => m_axi_gmem2_0_RVALID,
        m_axi_gmem2_0_RREADY => custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_RREADY,
        m_axi_gmem2_0_RDATA => m_axi_gmem2_0_RDATA,
        m_axi_gmem2_0_RLAST => m_axi_gmem2_0_RLAST,
        m_axi_gmem2_0_RID => m_axi_gmem2_0_RID,
        m_axi_gmem2_0_RFIFONUM => m_axi_gmem2_0_RFIFONUM,
        m_axi_gmem2_0_RUSER => m_axi_gmem2_0_RUSER,
        m_axi_gmem2_0_RRESP => m_axi_gmem2_0_RRESP,
        m_axi_gmem2_0_BVALID => ap_const_logic_0,
        m_axi_gmem2_0_BREADY => custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_BREADY,
        m_axi_gmem2_0_BRESP => ap_const_lv2_0,
        m_axi_gmem2_0_BID => ap_const_lv1_0,
        m_axi_gmem2_0_BUSER => ap_const_lv1_0,
        proj_weights => proj_weights,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_address0 => custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_address0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_ce0 => custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_ce0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_q0 => unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_q0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_address1 => custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_address1,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_ce1 => custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_ce1,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_q1 => unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_q1,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_address0 => custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_address0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_ce0 => custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_ce0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_q0 => unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_q0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_address1 => custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_address1,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_ce1 => custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_ce1,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_q1 => unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_q1,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_address0 => custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_address0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_ce0 => custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_ce0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_q0 => unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_q0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_address1 => custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_address1,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_ce1 => custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_ce1,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_q1 => unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_q1,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_address0 => custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_address0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_ce0 => custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_ce0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_q0 => unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_q0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_address1 => custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_address1,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_ce1 => custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_ce1,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_q1 => unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_q1,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_address0 => custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_address0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_ce0 => custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_ce0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_we0 => custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_we0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_d0 => custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_d0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_address0 => custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_address0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_ce0 => custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_ce0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_we0 => custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_we0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_d0 => custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_d0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_address0 => custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_address0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_ce0 => custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_ce0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_we0 => custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_we0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_d0 => custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_d0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_address0 => custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_address0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_ce0 => custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_ce0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_we0 => custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_we0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_d0 => custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_d0);




    ap_done <= custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_ap_done;
    ap_idle <= custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_ap_idle;
    ap_ready <= custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_ap_ready;
    custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_ap_continue <= ap_continue;
    custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_ap_start <= ap_start;
    m_axi_gmem2_0_ARADDR <= custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARADDR;
    m_axi_gmem2_0_ARBURST <= custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARBURST;
    m_axi_gmem2_0_ARCACHE <= custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARCACHE;
    m_axi_gmem2_0_ARID <= custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARID;
    m_axi_gmem2_0_ARLEN <= custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARLEN;
    m_axi_gmem2_0_ARLOCK <= custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARLOCK;
    m_axi_gmem2_0_ARPROT <= custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARPROT;
    m_axi_gmem2_0_ARQOS <= custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARQOS;
    m_axi_gmem2_0_ARREGION <= custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARREGION;
    m_axi_gmem2_0_ARSIZE <= custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARSIZE;
    m_axi_gmem2_0_ARUSER <= custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARUSER;
    m_axi_gmem2_0_ARVALID <= custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARVALID;
    m_axi_gmem2_0_AWADDR <= ap_const_lv64_0;
    m_axi_gmem2_0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem2_0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem2_0_AWID <= ap_const_lv1_0;
    m_axi_gmem2_0_AWLEN <= ap_const_lv32_0;
    m_axi_gmem2_0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem2_0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem2_0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem2_0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem2_0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem2_0_AWUSER <= ap_const_lv1_0;
    m_axi_gmem2_0_AWVALID <= ap_const_logic_0;
    m_axi_gmem2_0_BREADY <= ap_const_logic_0;
    m_axi_gmem2_0_RREADY <= custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_RREADY;
    m_axi_gmem2_0_WDATA <= ap_const_lv32_0;
    m_axi_gmem2_0_WID <= ap_const_lv1_0;
    m_axi_gmem2_0_WLAST <= ap_const_logic_0;
    m_axi_gmem2_0_WSTRB <= ap_const_lv4_0;
    m_axi_gmem2_0_WUSER <= ap_const_lv1_0;
    m_axi_gmem2_0_WVALID <= ap_const_logic_0;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_address0 <= custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_address0;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_address1 <= custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_address1;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_ce0 <= custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_ce0;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_ce1 <= custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_ce1;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_d0 <= ap_const_lv18_0;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_d1 <= ap_const_lv18_0;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_we0 <= ap_const_logic_0;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_we1 <= ap_const_logic_0;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_address0 <= custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_address0;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_address1 <= custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_address1;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_ce0 <= custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_ce0;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_ce1 <= custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_ce1;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_d0 <= ap_const_lv18_0;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_d1 <= ap_const_lv18_0;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_we0 <= ap_const_logic_0;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_we1 <= ap_const_logic_0;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_address0 <= custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_address0;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_address1 <= custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_address1;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_ce0 <= custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_ce0;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_ce1 <= custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_ce1;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_d0 <= ap_const_lv18_0;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_d1 <= ap_const_lv18_0;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_we0 <= ap_const_logic_0;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_we1 <= ap_const_logic_0;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_address0 <= custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_address0;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_address1 <= custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_address1;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_ce0 <= custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_ce0;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_ce1 <= custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_ce1;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_d0 <= ap_const_lv18_0;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_d1 <= ap_const_lv18_0;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_we0 <= ap_const_logic_0;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_we1 <= ap_const_logic_0;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_address0 <= custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_address0;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_address1 <= ap_const_lv8_0;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_ce0 <= custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_ce0;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_ce1 <= ap_const_logic_0;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_d0 <= custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_d0;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_d1 <= ap_const_lv18_0;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_we0 <= custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_we0;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_we1 <= ap_const_logic_0;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_address0 <= custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_address0;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_address1 <= ap_const_lv8_0;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_ce0 <= custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_ce0;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_ce1 <= ap_const_logic_0;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_d0 <= custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_d0;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_d1 <= ap_const_lv18_0;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_we0 <= custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_we0;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_we1 <= ap_const_logic_0;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_address0 <= custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_address0;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_address1 <= ap_const_lv8_0;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_ce0 <= custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_ce0;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_ce1 <= ap_const_logic_0;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_d0 <= custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_d0;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_d1 <= ap_const_lv18_0;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_we0 <= custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_we0;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_we1 <= ap_const_logic_0;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_address0 <= custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_address0;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_address1 <= ap_const_lv8_0;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_ce0 <= custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_ce0;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_ce1 <= ap_const_logic_0;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_d0 <= custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_d0;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_d1 <= ap_const_lv18_0;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_we0 <= custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_we0;
    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_we1 <= ap_const_logic_0;
end behav;
