-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity unet_pvm_top_forward_2_Pipeline_VITIS_LOOP_42_3 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    out_vec_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    out_vec_ce0 : OUT STD_LOGIC;
    out_vec_we0 : OUT STD_LOGIC;
    out_vec_d0 : OUT STD_LOGIC_VECTOR (17 downto 0);
    in_vec_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    in_vec_ce0 : OUT STD_LOGIC;
    in_vec_q0 : IN STD_LOGIC_VECTOR (17 downto 0);
    conv7_i95 : IN STD_LOGIC_VECTOR (17 downto 0) );
end;


architecture behav of unet_pvm_top_forward_2_Pipeline_VITIS_LOOP_42_3 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv6_20 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv11_400 : STD_LOGIC_VECTOR (10 downto 0) := "10000000000";
    constant ap_const_lv32_2E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101110";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_25 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100101";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv32_26 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100110";
    constant ap_const_lv9_1FF : STD_LOGIC_VECTOR (8 downto 0) := "111111111";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv18_1FFFF : STD_LOGIC_VECTOR (17 downto 0) := "011111111111111111";
    constant ap_const_lv18_20000 : STD_LOGIC_VECTOR (17 downto 0) := "100000000000000000";
    constant ap_const_lv18_0 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln42_fu_150_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal conv7_i95_cast_fu_138_p1 : STD_LOGIC_VECTOR (35 downto 0);
    signal conv7_i95_cast_reg_466 : STD_LOGIC_VECTOR (35 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal zext_ln42_fu_162_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln42_reg_475 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln42_reg_475_pp0_iter1_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln42_reg_475_pp0_iter2_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln42_1_fu_167_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln42_1_reg_480 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln44_fu_181_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln44_reg_485 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln44_reg_485_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln44_reg_485_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal mul_ln44_fu_196_p2 : STD_LOGIC_VECTOR (35 downto 0);
    signal mul_ln44_reg_495 : STD_LOGIC_VECTOR (35 downto 0);
    signal zext_ln44_6_cast_fu_201_p19 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln44_6_cast_reg_500 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln44_1_fu_134_p2 : STD_LOGIC_VECTOR (46 downto 0);
    signal mul_ln44_1_reg_505 : STD_LOGIC_VECTOR (46 downto 0);
    signal tmp_398_reg_511 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln_reg_517 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_399_reg_522 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln44_1_fu_284_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln44_1_reg_527 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln44_2_fu_300_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln44_2_reg_532 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln44_3_fu_306_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln44_3_reg_539 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal d_fu_98 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal add_ln42_fu_156_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_d_1 : STD_LOGIC_VECTOR (5 downto 0);
    signal in_vec_ce0_local : STD_LOGIC;
    signal out_vec_we0_local : STD_LOGIC;
    signal storemerge_fu_451_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal out_vec_ce0_local : STD_LOGIC;
    signal mul_ln44_1_fu_134_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_fu_171_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal mul_ln44_fu_196_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln44_6_cast_fu_201_p17 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_s_fu_274_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_303_fu_290_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln44_fu_319_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln44_fu_322_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_401_fu_327_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_400_fu_312_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln44_fu_335_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln44_fu_341_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_402_fu_347_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln44_1_fu_360_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln44_1_fu_366_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln44_fu_354_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln44_2_fu_383_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln44_fu_389_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln44_3_fu_395_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln44_2_fu_371_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln44_2_fu_378_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln44_4_fu_406_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln44_1_fu_412_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln44_4_fu_418_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln44_3_fu_400_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln44_5_fu_424_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln44_2_fu_437_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln44_3_fu_429_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal select_ln44_4_fu_443_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal mul_ln44_1_fu_134_p10 : STD_LOGIC_VECTOR (46 downto 0);
    signal zext_ln44_6_cast_fu_201_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln44_6_cast_fu_201_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln44_6_cast_fu_201_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln44_6_cast_fu_201_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln44_6_cast_fu_201_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln44_6_cast_fu_201_p11 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln44_6_cast_fu_201_p13 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln44_6_cast_fu_201_p15 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component unet_pvm_top_mul_36s_11ns_47_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (35 downto 0);
        din1 : IN STD_LOGIC_VECTOR (10 downto 0);
        dout : OUT STD_LOGIC_VECTOR (46 downto 0) );
    end component;


    component unet_pvm_top_mul_18s_18s_36_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (17 downto 0);
        din1 : IN STD_LOGIC_VECTOR (17 downto 0);
        dout : OUT STD_LOGIC_VECTOR (35 downto 0) );
    end component;


    component unet_pvm_top_sparsemux_17_3_11_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (2 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (2 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (2 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (2 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (2 downto 0);
        din4_WIDTH : INTEGER;
        CASE5 : STD_LOGIC_VECTOR (2 downto 0);
        din5_WIDTH : INTEGER;
        CASE6 : STD_LOGIC_VECTOR (2 downto 0);
        din6_WIDTH : INTEGER;
        CASE7 : STD_LOGIC_VECTOR (2 downto 0);
        din7_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (10 downto 0);
        din1 : IN STD_LOGIC_VECTOR (10 downto 0);
        din2 : IN STD_LOGIC_VECTOR (10 downto 0);
        din3 : IN STD_LOGIC_VECTOR (10 downto 0);
        din4 : IN STD_LOGIC_VECTOR (10 downto 0);
        din5 : IN STD_LOGIC_VECTOR (10 downto 0);
        din6 : IN STD_LOGIC_VECTOR (10 downto 0);
        din7 : IN STD_LOGIC_VECTOR (10 downto 0);
        def : IN STD_LOGIC_VECTOR (10 downto 0);
        sel : IN STD_LOGIC_VECTOR (2 downto 0);
        dout : OUT STD_LOGIC_VECTOR (10 downto 0) );
    end component;


    component unet_pvm_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_36s_11ns_47_1_1_U170 : component unet_pvm_top_mul_36s_11ns_47_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 36,
        din1_WIDTH => 11,
        dout_WIDTH => 47)
    port map (
        din0 => mul_ln44_reg_495,
        din1 => mul_ln44_1_fu_134_p1,
        dout => mul_ln44_1_fu_134_p2);

    mul_18s_18s_36_1_1_U171 : component unet_pvm_top_mul_18s_18s_36_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 18,
        din1_WIDTH => 18,
        dout_WIDTH => 36)
    port map (
        din0 => in_vec_q0,
        din1 => mul_ln44_fu_196_p1,
        dout => mul_ln44_fu_196_p2);

    sparsemux_17_3_11_1_1_U172 : component unet_pvm_top_sparsemux_17_3_11_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000",
        din0_WIDTH => 11,
        CASE1 => "001",
        din1_WIDTH => 11,
        CASE2 => "010",
        din2_WIDTH => 11,
        CASE3 => "011",
        din3_WIDTH => 11,
        CASE4 => "100",
        din4_WIDTH => 11,
        CASE5 => "101",
        din5_WIDTH => 11,
        CASE6 => "110",
        din6_WIDTH => 11,
        CASE7 => "111",
        din7_WIDTH => 11,
        def_WIDTH => 11,
        sel_WIDTH => 3,
        dout_WIDTH => 11)
    port map (
        din0 => ap_const_lv11_400,
        din1 => ap_const_lv11_400,
        din2 => ap_const_lv11_400,
        din3 => ap_const_lv11_400,
        din4 => ap_const_lv11_400,
        din5 => ap_const_lv11_400,
        din6 => ap_const_lv11_400,
        din7 => ap_const_lv11_400,
        def => zext_ln44_6_cast_fu_201_p17,
        sel => trunc_ln42_1_reg_480,
        dout => zext_ln44_6_cast_fu_201_p19);

    flow_control_loop_pipe_sequential_init_U : component unet_pvm_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    d_fu_98_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln42_fu_150_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    d_fu_98 <= add_ln42_fu_156_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    d_fu_98 <= ap_const_lv6_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                conv7_i95_cast_reg_466 <= conv7_i95_cast_fu_138_p1;
                icmp_ln44_reg_485 <= icmp_ln44_fu_181_p2;
                icmp_ln44_reg_485_pp0_iter1_reg <= icmp_ln44_reg_485;
                mul_ln44_reg_495 <= mul_ln44_fu_196_p2;
                trunc_ln42_1_reg_480 <= trunc_ln42_1_fu_167_p1;
                    zext_ln42_reg_475(5 downto 0) <= zext_ln42_fu_162_p1(5 downto 0);
                    zext_ln42_reg_475_pp0_iter1_reg(5 downto 0) <= zext_ln42_reg_475(5 downto 0);
                zext_ln44_6_cast_reg_500 <= zext_ln44_6_cast_fu_201_p19;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                icmp_ln44_1_reg_527 <= icmp_ln44_1_fu_284_p2;
                icmp_ln44_2_reg_532 <= icmp_ln44_2_fu_300_p2;
                icmp_ln44_3_reg_539 <= icmp_ln44_3_fu_306_p2;
                icmp_ln44_reg_485_pp0_iter2_reg <= icmp_ln44_reg_485_pp0_iter1_reg;
                mul_ln44_1_reg_505 <= mul_ln44_1_fu_134_p2;
                tmp_398_reg_511 <= mul_ln44_1_fu_134_p2(46 downto 46);
                tmp_399_reg_522 <= mul_ln44_1_fu_134_p2(19 downto 19);
                trunc_ln_reg_517 <= mul_ln44_1_fu_134_p2(37 downto 20);
                    zext_ln42_reg_475_pp0_iter2_reg(5 downto 0) <= zext_ln42_reg_475_pp0_iter1_reg(5 downto 0);
            end if;
        end if;
    end process;
    zext_ln42_reg_475(63 downto 6) <= "0000000000000000000000000000000000000000000000000000000000";
    zext_ln42_reg_475_pp0_iter1_reg(63 downto 6) <= "0000000000000000000000000000000000000000000000000000000000";
    zext_ln42_reg_475_pp0_iter2_reg(63 downto 6) <= "0000000000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln42_fu_156_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_d_1) + unsigned(ap_const_lv6_1));
    add_ln44_fu_322_p2 <= std_logic_vector(unsigned(trunc_ln_reg_517) + unsigned(zext_ln44_fu_319_p1));
    and_ln44_1_fu_366_p2 <= (xor_ln44_1_fu_360_p2 and icmp_ln44_1_reg_527);
    and_ln44_2_fu_378_p2 <= (icmp_ln44_2_reg_532 and and_ln44_fu_341_p2);
    and_ln44_3_fu_400_p2 <= (xor_ln44_3_fu_395_p2 and or_ln44_fu_389_p2);
    and_ln44_4_fu_406_p2 <= (tmp_401_fu_327_p3 and select_ln44_2_fu_371_p3);
    and_ln44_5_fu_424_p2 <= (xor_ln44_4_fu_418_p2 and tmp_398_reg_511);
    and_ln44_fu_341_p2 <= (xor_ln44_fu_335_p2 and tmp_400_fu_312_p3);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln42_fu_150_p2)
    begin
        if (((icmp_ln42_fu_150_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_d_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, d_fu_98, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_d_1 <= ap_const_lv6_0;
        else 
            ap_sig_allocacmp_d_1 <= d_fu_98;
        end if; 
    end process;

        conv7_i95_cast_fu_138_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(conv7_i95),36));

    icmp_ln42_fu_150_p2 <= "1" when (ap_sig_allocacmp_d_1 = ap_const_lv6_20) else "0";
    icmp_ln44_1_fu_284_p2 <= "1" when (tmp_s_fu_274_p4 = ap_const_lv8_FF) else "0";
    icmp_ln44_2_fu_300_p2 <= "1" when (tmp_303_fu_290_p4 = ap_const_lv9_1FF) else "0";
    icmp_ln44_3_fu_306_p2 <= "1" when (tmp_303_fu_290_p4 = ap_const_lv9_0) else "0";
    icmp_ln44_fu_181_p2 <= "1" when (tmp_fu_171_p4 = ap_const_lv3_0) else "0";
    in_vec_address0 <= zext_ln42_fu_162_p1(5 - 1 downto 0);
    in_vec_ce0 <= in_vec_ce0_local;

    in_vec_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_vec_ce0_local <= ap_const_logic_1;
        else 
            in_vec_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    mul_ln44_1_fu_134_p1 <= mul_ln44_1_fu_134_p10(11 - 1 downto 0);
    mul_ln44_1_fu_134_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln44_6_cast_reg_500),47));
    mul_ln44_fu_196_p1 <= conv7_i95_cast_reg_466(18 - 1 downto 0);
    or_ln44_1_fu_412_p2 <= (and_ln44_4_fu_406_p2 or and_ln44_2_fu_378_p2);
    or_ln44_2_fu_437_p2 <= (and_ln44_5_fu_424_p2 or and_ln44_3_fu_400_p2);
    or_ln44_fu_389_p2 <= (xor_ln44_2_fu_383_p2 or tmp_401_fu_327_p3);
    out_vec_address0 <= zext_ln42_reg_475_pp0_iter2_reg(5 - 1 downto 0);
    out_vec_ce0 <= out_vec_ce0_local;

    out_vec_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            out_vec_ce0_local <= ap_const_logic_1;
        else 
            out_vec_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    out_vec_d0 <= storemerge_fu_451_p3;
    out_vec_we0 <= out_vec_we0_local;

    out_vec_we0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            out_vec_we0_local <= ap_const_logic_1;
        else 
            out_vec_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    select_ln44_2_fu_371_p3 <= 
        and_ln44_1_fu_366_p2 when (and_ln44_fu_341_p2(0) = '1') else 
        icmp_ln44_2_reg_532;
    select_ln44_3_fu_429_p3 <= 
        ap_const_lv18_1FFFF when (and_ln44_3_fu_400_p2(0) = '1') else 
        ap_const_lv18_20000;
    select_ln44_4_fu_443_p3 <= 
        select_ln44_3_fu_429_p3 when (or_ln44_2_fu_437_p2(0) = '1') else 
        add_ln44_fu_322_p2;
    select_ln44_fu_354_p3 <= 
        icmp_ln44_2_reg_532 when (and_ln44_fu_341_p2(0) = '1') else 
        icmp_ln44_3_reg_539;
    storemerge_fu_451_p3 <= 
        select_ln44_4_fu_443_p3 when (icmp_ln44_reg_485_pp0_iter2_reg(0) = '1') else 
        ap_const_lv18_0;
    tmp_303_fu_290_p4 <= mul_ln44_1_fu_134_p2(46 downto 38);
    tmp_400_fu_312_p3 <= mul_ln44_1_reg_505(37 downto 37);
    tmp_401_fu_327_p3 <= add_ln44_fu_322_p2(17 downto 17);
    tmp_402_fu_347_p3 <= mul_ln44_1_reg_505(38 downto 38);
    tmp_fu_171_p4 <= ap_sig_allocacmp_d_1(5 downto 3);
    tmp_s_fu_274_p4 <= mul_ln44_1_fu_134_p2(46 downto 39);
    trunc_ln42_1_fu_167_p1 <= ap_sig_allocacmp_d_1(3 - 1 downto 0);
    xor_ln44_1_fu_360_p2 <= (tmp_402_fu_347_p3 xor ap_const_lv1_1);
    xor_ln44_2_fu_383_p2 <= (select_ln44_fu_354_p3 xor ap_const_lv1_1);
    xor_ln44_3_fu_395_p2 <= (tmp_398_reg_511 xor ap_const_lv1_1);
    xor_ln44_4_fu_418_p2 <= (or_ln44_1_fu_412_p2 xor ap_const_lv1_1);
    xor_ln44_fu_335_p2 <= (tmp_401_fu_327_p3 xor ap_const_lv1_1);
    zext_ln42_fu_162_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_d_1),64));
    zext_ln44_6_cast_fu_201_p17 <= "XXXXXXXXXXX";
    zext_ln44_fu_319_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_399_reg_522),18));
end behav;
