// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module unet_pvm_top_forward_19 (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        s_in_norm_dout,
        s_in_norm_empty_n,
        s_in_norm_read,
        s_in_norm_num_data_valid,
        s_in_norm_fifo_cap,
        s_norm_out_din,
        s_norm_out_full_n,
        s_norm_out_write,
        s_norm_out_num_data_valid,
        s_norm_out_fifo_cap
);

parameter    ap_ST_fsm_state1 = 67'd1;
parameter    ap_ST_fsm_state2 = 67'd2;
parameter    ap_ST_fsm_state3 = 67'd4;
parameter    ap_ST_fsm_state4 = 67'd8;
parameter    ap_ST_fsm_state5 = 67'd16;
parameter    ap_ST_fsm_state6 = 67'd32;
parameter    ap_ST_fsm_state7 = 67'd64;
parameter    ap_ST_fsm_state8 = 67'd128;
parameter    ap_ST_fsm_state9 = 67'd256;
parameter    ap_ST_fsm_state10 = 67'd512;
parameter    ap_ST_fsm_state11 = 67'd1024;
parameter    ap_ST_fsm_state12 = 67'd2048;
parameter    ap_ST_fsm_state13 = 67'd4096;
parameter    ap_ST_fsm_state14 = 67'd8192;
parameter    ap_ST_fsm_state15 = 67'd16384;
parameter    ap_ST_fsm_state16 = 67'd32768;
parameter    ap_ST_fsm_state17 = 67'd65536;
parameter    ap_ST_fsm_state18 = 67'd131072;
parameter    ap_ST_fsm_state19 = 67'd262144;
parameter    ap_ST_fsm_state20 = 67'd524288;
parameter    ap_ST_fsm_state21 = 67'd1048576;
parameter    ap_ST_fsm_state22 = 67'd2097152;
parameter    ap_ST_fsm_state23 = 67'd4194304;
parameter    ap_ST_fsm_state24 = 67'd8388608;
parameter    ap_ST_fsm_state25 = 67'd16777216;
parameter    ap_ST_fsm_state26 = 67'd33554432;
parameter    ap_ST_fsm_state27 = 67'd67108864;
parameter    ap_ST_fsm_state28 = 67'd134217728;
parameter    ap_ST_fsm_state29 = 67'd268435456;
parameter    ap_ST_fsm_state30 = 67'd536870912;
parameter    ap_ST_fsm_state31 = 67'd1073741824;
parameter    ap_ST_fsm_state32 = 67'd2147483648;
parameter    ap_ST_fsm_state33 = 67'd4294967296;
parameter    ap_ST_fsm_state34 = 67'd8589934592;
parameter    ap_ST_fsm_state35 = 67'd17179869184;
parameter    ap_ST_fsm_state36 = 67'd34359738368;
parameter    ap_ST_fsm_state37 = 67'd68719476736;
parameter    ap_ST_fsm_state38 = 67'd137438953472;
parameter    ap_ST_fsm_state39 = 67'd274877906944;
parameter    ap_ST_fsm_state40 = 67'd549755813888;
parameter    ap_ST_fsm_state41 = 67'd1099511627776;
parameter    ap_ST_fsm_state42 = 67'd2199023255552;
parameter    ap_ST_fsm_state43 = 67'd4398046511104;
parameter    ap_ST_fsm_state44 = 67'd8796093022208;
parameter    ap_ST_fsm_state45 = 67'd17592186044416;
parameter    ap_ST_fsm_state46 = 67'd35184372088832;
parameter    ap_ST_fsm_state47 = 67'd70368744177664;
parameter    ap_ST_fsm_state48 = 67'd140737488355328;
parameter    ap_ST_fsm_state49 = 67'd281474976710656;
parameter    ap_ST_fsm_state50 = 67'd562949953421312;
parameter    ap_ST_fsm_state51 = 67'd1125899906842624;
parameter    ap_ST_fsm_state52 = 67'd2251799813685248;
parameter    ap_ST_fsm_state53 = 67'd4503599627370496;
parameter    ap_ST_fsm_state54 = 67'd9007199254740992;
parameter    ap_ST_fsm_state55 = 67'd18014398509481984;
parameter    ap_ST_fsm_state56 = 67'd36028797018963968;
parameter    ap_ST_fsm_state57 = 67'd72057594037927936;
parameter    ap_ST_fsm_state58 = 67'd144115188075855872;
parameter    ap_ST_fsm_state59 = 67'd288230376151711744;
parameter    ap_ST_fsm_state60 = 67'd576460752303423488;
parameter    ap_ST_fsm_state61 = 67'd1152921504606846976;
parameter    ap_ST_fsm_state62 = 67'd2305843009213693952;
parameter    ap_ST_fsm_state63 = 67'd4611686018427387904;
parameter    ap_ST_fsm_state64 = 67'd9223372036854775808;
parameter    ap_ST_fsm_state65 = 67'd18446744073709551616;
parameter    ap_ST_fsm_state66 = 67'd36893488147419103232;
parameter    ap_ST_fsm_state67 = 67'd73786976294838206464;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [575:0] s_in_norm_dout;
input   s_in_norm_empty_n;
output   s_in_norm_read;
input  [4:0] s_in_norm_num_data_valid;
input  [4:0] s_in_norm_fifo_cap;
output  [575:0] s_norm_out_din;
input   s_norm_out_full_n;
output   s_norm_out_write;
input  [4:0] s_norm_out_num_data_valid;
input  [4:0] s_norm_out_fifo_cap;

reg ap_done;
reg ap_idle;
reg start_write;
reg s_in_norm_read;
reg s_norm_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [66:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    s_in_norm_blk_n;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln26_fu_961_p2;
reg    s_norm_out_blk_n;
wire    ap_CS_fsm_state67;
reg    ap_block_state1;
reg   [17:0] trunc_ln28_64_reg_2641;
reg    ap_block_state2;
reg   [17:0] trunc_ln28_65_reg_2646;
reg   [17:0] trunc_ln28_66_reg_2651;
reg   [17:0] trunc_ln28_67_reg_2656;
reg   [17:0] trunc_ln28_68_reg_2661;
reg   [17:0] trunc_ln28_69_reg_2666;
reg   [17:0] trunc_ln28_70_reg_2671;
reg   [17:0] trunc_ln28_71_reg_2676;
reg   [17:0] trunc_ln28_72_reg_2681;
reg   [17:0] trunc_ln28_73_reg_2686;
reg   [17:0] trunc_ln28_74_reg_2691;
reg   [17:0] trunc_ln28_75_reg_2696;
reg   [17:0] trunc_ln28_76_reg_2701;
reg   [17:0] trunc_ln28_77_reg_2706;
reg   [17:0] trunc_ln28_78_reg_2711;
reg   [17:0] trunc_ln28_79_reg_2716;
reg   [17:0] trunc_ln28_80_reg_2721;
reg   [17:0] trunc_ln28_81_reg_2726;
reg   [17:0] trunc_ln28_82_reg_2731;
reg   [17:0] trunc_ln28_83_reg_2736;
reg   [17:0] trunc_ln28_84_reg_2741;
reg   [17:0] trunc_ln28_85_reg_2746;
reg   [17:0] trunc_ln28_86_reg_2751;
reg   [17:0] trunc_ln28_87_reg_2756;
reg   [17:0] trunc_ln28_88_reg_2761;
reg   [17:0] trunc_ln28_89_reg_2766;
reg   [17:0] trunc_ln28_90_reg_2771;
reg   [17:0] trunc_ln28_s_reg_2776;
reg   [17:0] trunc_ln28_91_reg_2781;
reg   [17:0] trunc_ln28_92_reg_2786;
wire   [0:0] icmp_ln39_fu_1397_p2;
reg   [0:0] icmp_ln39_reg_2791;
wire    ap_CS_fsm_state20;
wire   [0:0] tmp_514_fu_1403_p3;
reg   [0:0] tmp_514_reg_2796;
wire   [15:0] select_ln39_fu_1417_p3;
reg   [15:0] select_ln39_reg_2801;
wire   [31:0] temp_sum_fu_1532_p3;
reg   [31:0] temp_sum_reg_2807;
wire    ap_CS_fsm_state21;
wire   [31:0] grp_fu_948_p2;
reg   [31:0] tmp_341_reg_2812;
wire    ap_CS_fsm_state33;
wire   [31:0] grp_fu_940_p2;
reg   [31:0] div_reg_2817;
wire    ap_CS_fsm_state45;
reg   [0:0] tmp_516_reg_2822;
wire    ap_CS_fsm_state47;
wire   [11:0] zext_ln40_fu_1563_p1;
reg   [11:0] zext_ln40_reg_2832;
wire   [53:0] zext_ln40_17_fu_1579_p1;
reg   [53:0] zext_ln40_17_reg_2837;
wire   [53:0] sub_ln40_fu_1583_p2;
reg   [53:0] sub_ln40_reg_2842;
wire   [0:0] icmp_ln40_fu_1589_p2;
reg   [0:0] icmp_ln40_reg_2847;
wire   [11:0] sub_ln40_5_fu_1595_p2;
reg   [11:0] sub_ln40_5_reg_2853;
wire   [5:0] trunc_ln40_29_fu_1601_p1;
reg   [5:0] trunc_ln40_29_reg_2862;
wire   [10:0] trunc_ln40_30_fu_1605_p1;
reg   [10:0] trunc_ln40_30_reg_2867;
wire   [17:0] ref_tmp_i_i_fu_1787_p9;
reg   [17:0] ref_tmp_i_i_reg_2872;
wire    ap_CS_fsm_state48;
wire   [0:0] carry_1_i_fu_1813_p2;
reg   [0:0] carry_1_i_reg_2877;
wire   [0:0] icmp_ln40_49_fu_1846_p2;
reg   [0:0] icmp_ln40_49_reg_2884;
reg   [0:0] tmp_521_reg_2889;
wire   [0:0] icmp_ln40_43_fu_1874_p2;
reg   [0:0] icmp_ln40_43_reg_2896;
wire   [0:0] tmp_522_fu_1880_p3;
reg   [0:0] tmp_522_reg_2903;
wire   [0:0] Range2_all_ones_1_i_fu_1966_p3;
reg   [0:0] Range2_all_ones_1_i_reg_2908;
wire   [0:0] xor_ln40_20_fu_1986_p2;
reg   [0:0] xor_ln40_20_reg_2913;
wire   [0:0] Range1_all_ones_2_i_fu_2048_p9;
reg   [0:0] Range1_all_ones_2_i_reg_2918;
wire   [0:0] Range1_all_zeros_2_i_fu_2068_p9;
reg   [0:0] Range1_all_zeros_2_i_reg_2925;
wire   [17:0] rsqrt_fu_2246_p9;
reg   [17:0] rsqrt_reg_2930;
wire    ap_CS_fsm_state49;
reg   [17:0] out_vec_load_reg_2935;
wire    ap_CS_fsm_state52;
reg   [17:0] out_vec_load_63_reg_2940;
reg   [17:0] out_vec_load_64_reg_2945;
wire    ap_CS_fsm_state53;
reg   [17:0] out_vec_load_65_reg_2950;
reg   [17:0] out_vec_load_66_reg_2955;
wire    ap_CS_fsm_state54;
reg   [17:0] out_vec_load_67_reg_2960;
reg   [17:0] out_vec_load_68_reg_2965;
wire    ap_CS_fsm_state55;
reg   [17:0] out_vec_load_69_reg_2970;
reg   [17:0] out_vec_load_70_reg_2975;
wire    ap_CS_fsm_state56;
reg   [17:0] out_vec_load_71_reg_2980;
reg   [17:0] out_vec_load_72_reg_2985;
wire    ap_CS_fsm_state57;
reg   [17:0] out_vec_load_73_reg_2990;
reg   [17:0] out_vec_load_74_reg_2995;
wire    ap_CS_fsm_state58;
reg   [17:0] out_vec_load_75_reg_3000;
reg   [17:0] out_vec_load_76_reg_3005;
wire    ap_CS_fsm_state59;
reg   [17:0] out_vec_load_77_reg_3010;
reg   [17:0] out_vec_load_78_reg_3015;
wire    ap_CS_fsm_state60;
reg   [17:0] out_vec_load_79_reg_3020;
reg   [17:0] out_vec_load_80_reg_3025;
wire    ap_CS_fsm_state61;
reg   [17:0] out_vec_load_81_reg_3030;
reg   [17:0] out_vec_load_82_reg_3035;
wire    ap_CS_fsm_state62;
reg   [17:0] out_vec_load_83_reg_3040;
reg   [17:0] out_vec_load_84_reg_3045;
wire    ap_CS_fsm_state63;
reg   [17:0] out_vec_load_85_reg_3050;
reg   [17:0] out_vec_load_86_reg_3055;
wire    ap_CS_fsm_state64;
reg   [17:0] out_vec_load_87_reg_3060;
reg   [17:0] out_vec_load_88_reg_3065;
wire    ap_CS_fsm_state65;
reg   [17:0] out_vec_load_89_reg_3070;
reg   [17:0] out_vec_load_90_reg_3075;
wire    ap_CS_fsm_state66;
reg   [17:0] out_vec_load_91_reg_3080;
reg   [4:0] in_vec_address0;
reg    in_vec_ce0;
wire   [17:0] in_vec_q0;
reg   [4:0] out_vec_address0;
reg    out_vec_ce0;
reg    out_vec_we0;
wire   [17:0] out_vec_q0;
wire   [17:0] out_vec_q1;
wire    grp_forward_19_Pipeline_VITIS_LOOP_32_2_fu_927_ap_start;
wire    grp_forward_19_Pipeline_VITIS_LOOP_32_2_fu_927_ap_done;
wire    grp_forward_19_Pipeline_VITIS_LOOP_32_2_fu_927_ap_idle;
wire    grp_forward_19_Pipeline_VITIS_LOOP_32_2_fu_927_ap_ready;
wire   [4:0] grp_forward_19_Pipeline_VITIS_LOOP_32_2_fu_927_in_vec_address0;
wire    grp_forward_19_Pipeline_VITIS_LOOP_32_2_fu_927_in_vec_ce0;
wire   [17:0] grp_forward_19_Pipeline_VITIS_LOOP_32_2_fu_927_sum_sq_out;
wire    grp_forward_19_Pipeline_VITIS_LOOP_32_2_fu_927_sum_sq_out_ap_vld;
wire    grp_forward_19_Pipeline_VITIS_LOOP_42_3_fu_933_ap_start;
wire    grp_forward_19_Pipeline_VITIS_LOOP_42_3_fu_933_ap_done;
wire    grp_forward_19_Pipeline_VITIS_LOOP_42_3_fu_933_ap_idle;
wire    grp_forward_19_Pipeline_VITIS_LOOP_42_3_fu_933_ap_ready;
wire   [4:0] grp_forward_19_Pipeline_VITIS_LOOP_42_3_fu_933_out_vec_address0;
wire    grp_forward_19_Pipeline_VITIS_LOOP_42_3_fu_933_out_vec_ce0;
wire    grp_forward_19_Pipeline_VITIS_LOOP_42_3_fu_933_out_vec_we0;
wire   [17:0] grp_forward_19_Pipeline_VITIS_LOOP_42_3_fu_933_out_vec_d0;
wire   [4:0] grp_forward_19_Pipeline_VITIS_LOOP_42_3_fu_933_in_vec_address0;
wire    grp_forward_19_Pipeline_VITIS_LOOP_42_3_fu_933_in_vec_ce0;
reg    grp_forward_19_Pipeline_VITIS_LOOP_32_2_fu_927_ap_start_reg;
wire    ap_CS_fsm_state18;
wire    ap_CS_fsm_state19;
reg    grp_forward_19_Pipeline_VITIS_LOOP_42_3_fu_933_ap_start_reg;
wire    ap_CS_fsm_state50;
reg   [4:0] t_06_fu_368;
wire   [4:0] t_15_fu_967_p2;
reg    in_vec_we1_local;
reg   [17:0] in_vec_d1_local;
wire   [17:0] trunc_ln28_fu_973_p1;
reg    in_vec_ce1_local;
reg   [4:0] in_vec_address1_local;
reg    in_vec_we0_local;
reg   [17:0] in_vec_d0_local;
reg    in_vec_ce0_local;
reg   [4:0] in_vec_address0_local;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state15;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state17;
reg    out_vec_ce1_local;
wire    ap_CS_fsm_state51;
reg   [4:0] out_vec_address1_local;
reg    out_vec_ce0_local;
reg   [4:0] out_vec_address0_local;
wire    ap_CS_fsm_state34;
wire    ap_CS_fsm_state46;
wire    ap_CS_fsm_state22;
wire   [27:0] shl_ln_fu_1321_p3;
wire  signed [28:0] sext_ln39_fu_1329_p1;
wire   [28:0] sub_ln39_7_fu_1341_p2;
wire   [15:0] tmp_41_fu_1347_p4;
wire   [16:0] zext_ln39_fu_1357_p1;
wire   [14:0] trunc_ln39_6_fu_1367_p4;
wire  signed [15:0] sext_ln39_7_fu_1377_p1;
wire   [0:0] tmp_513_fu_1333_p3;
wire   [16:0] sub_ln39_8_fu_1361_p2;
wire   [16:0] zext_ln39_16_fu_1381_p1;
wire   [16:0] select_ln39_6_fu_1385_p3;
wire   [15:0] trunc_ln39_fu_1393_p1;
wire   [15:0] sub_ln39_fu_1411_p2;
wire   [29:0] tmp_s_fu_1428_p1;
wire   [29:0] tmp_s_fu_1428_p3;
wire   [4:0] trunc_ln39_5_fu_1436_p1;
wire   [4:0] add_ln39_fu_1443_p2;
wire   [40:0] zext_ln39_13_fu_1440_p1;
wire   [40:0] zext_ln39_14_fu_1449_p1;
wire   [40:0] shl_ln39_fu_1453_p2;
wire   [39:0] lshr_ln39_3_fu_1459_p4;
wire   [0:0] tmp_515_fu_1473_p3;
wire   [4:0] sub_ln39_9_fu_1489_p2;
wire   [7:0] select_ln39_8_fu_1481_p3;
wire  signed [7:0] sext_ln39_6_fu_1495_p1;
wire   [7:0] add_ln39_3_fu_1499_p2;
wire   [63:0] zext_ln39_15_fu_1469_p1;
wire   [8:0] tmp_fu_1505_p3;
wire   [63:0] pi_assign_fu_1512_p5;
wire   [31:0] LD_fu_1524_p1;
wire   [31:0] bitcast_ln777_fu_1528_p1;
wire   [63:0] grp_fu_945_p1;
wire   [63:0] bitcast_ln735_fu_1539_p1;
wire   [10:0] tmp_342_fu_1555_p3;
wire   [51:0] trunc_ln40_28_fu_1567_p1;
wire   [52:0] zext_ln40_14_cast_fu_1571_p3;
wire   [62:0] trunc_ln40_fu_1543_p1;
wire   [11:0] add_ln40_fu_1619_p2;
wire   [0:0] icmp_ln40_37_fu_1614_p2;
wire   [10:0] trunc_ln40_31_fu_1624_p1;
wire   [10:0] sub_ln40_6_fu_1628_p2;
wire   [53:0] select_ln40_fu_1609_p3;
wire   [10:0] select_ln40_14_fu_1633_p3;
wire   [53:0] zext_ln40_12_fu_1663_p1;
wire   [53:0] ashr_ln40_fu_1667_p2;
wire   [0:0] icmp_ln40_39_fu_1650_p2;
wire   [17:0] trunc_ln40_33_fu_1673_p1;
wire   [17:0] select_ln40_20_fu_1656_p3;
wire   [17:0] trunc_ln40_32_fu_1646_p1;
wire   [17:0] select_ln40_14cast_fu_1697_p1;
wire   [0:0] icmp_ln40_41_fu_1691_p2;
wire   [17:0] shl_ln40_fu_1701_p2;
wire   [5:0] tmp_517_fu_1720_p2;
wire   [0:0] icmp_ln40_40_fu_1685_p2;
wire   [0:0] tmp_517_fu_1720_p3;
wire   [17:0] select_ln40_15_fu_1677_p3;
wire   [0:0] cond64_i_fu_1728_p3;
wire   [17:0] zext_ln40_13_fu_1743_p1;
wire   [17:0] add_ln40_13_fu_1747_p2;
wire   [0:0] tmp_519_fu_1753_p3;
wire   [0:0] icmp_ln40_38_fu_1641_p2;
wire   [0:0] xor_ln40_27_fu_1767_p2;
wire   [0:0] and_ln40_31_fu_1773_p2;
wire   [17:0] ref_tmp_i_i_fu_1787_p6;
wire   [17:0] ref_tmp_i_i_fu_1787_p7;
wire   [1:0] ref_tmp_i_i_fu_1787_p8;
wire   [0:0] tmp_518_fu_1735_p3;
wire   [0:0] and_ln40_32_fu_1807_p2;
wire   [0:0] xor_ln40_fu_1761_p2;
wire   [10:0] or_ln40_s_fu_1819_p3;
wire  signed [11:0] sext_ln40_5_fu_1827_p1;
wire   [11:0] add_ln40_14_fu_1831_p2;
wire   [8:0] tmp_520_fu_1836_p4;
wire   [11:0] add_ln40_15_fu_1852_p2;
wire   [5:0] tobool134_i_fu_1900_p2;
wire   [0:0] icmp_ln40_45_fu_1894_p2;
wire   [0:0] tobool134_i_fu_1900_p3;
wire   [11:0] add_ln40_16_fu_1861_p2;
wire   [5:0] trunc_ln40_36_fu_1926_p1;
wire   [53:0] zext_ln40_16_fu_1930_p1;
wire   [53:0] lshr_ln40_fu_1934_p2;
wire   [53:0] lshr_ln40_3_fu_1940_p2;
wire   [0:0] tmp_523_fu_1952_p3;
wire   [0:0] icmp_ln40_47_fu_1920_p2;
wire   [0:0] icmp_ln40_48_fu_1946_p2;
wire   [0:0] xor_ln40_33_fu_1960_p2;
wire   [0:0] icmp_ln40_46_fu_1914_p2;
wire   [0:0] xor_ln40_32_fu_1888_p2;
wire   [0:0] lD_0_i_fu_1908_p2;
wire   [0:0] icmp_ln40_50_fu_1992_p2;
wire   [0:0] icmp_ln40_52_fu_2010_p2;
wire   [0:0] xor_ln40_34_fu_2022_p2;
wire   [0:0] icmp_ln40_51_fu_2004_p2;
wire   [0:0] or_ln40_12_fu_2028_p2;
wire   [0:0] and_ln40_23_fu_1974_p2;
wire   [0:0] and_ln40_33_fu_2034_p2;
wire   [0:0] Range1_all_ones_2_i_fu_2048_p2;
wire   [0:0] Range1_all_ones_2_i_fu_2048_p7;
wire   [1:0] sel_tmp_fu_2040_p3;
wire   [0:0] Range1_all_zeros_2_i_fu_2068_p2;
wire   [0:0] Range1_all_zeros_2_i_fu_2068_p6;
wire   [0:0] Range1_all_zeros_2_i_fu_2068_p7;
wire   [0:0] or_ln40_8_fu_2097_p2;
wire   [0:0] and_ln40_26_fu_2101_p2;
wire   [0:0] and_ln40_27_fu_2112_p2;
wire   [0:0] cond193_i_fu_2106_p3;
wire   [0:0] not_icmp_ln40_4354_fu_2122_p2;
wire   [0:0] and_ln40_34_fu_2133_p2;
wire   [0:0] neg_src_0_i_fu_2145_p2;
wire   [0:0] neg_src_0_i_fu_2145_p4;
wire   [0:0] neg_src_0_i_fu_2145_p7;
wire   [1:0] neg_src_0_i_fu_2145_p8;
wire   [0:0] select_ln40_17_fu_2092_p3;
wire   [0:0] xor_ln40_29_fu_2165_p2;
wire   [0:0] and_ln40_35_fu_2171_p2;
wire   [0:0] or_ln40_9_fu_2176_p2;
wire   [0:0] xor_ln40_25_fu_2181_p2;
wire   [0:0] deleted_ones_0_i_fu_2127_p2;
wire   [0:0] and_ln40_29_fu_2192_p2;
wire   [0:0] neg_src_0_i_fu_2145_p9;
wire   [0:0] xor_ln40_26_fu_2197_p2;
wire   [0:0] and_ln40_30_fu_2203_p2;
wire   [0:0] and_ln40_28_fu_2186_p2;
wire   [0:0] or_ln40_10_fu_2209_p2;
wire   [0:0] xor_ln40_30_fu_2223_p2;
wire   [0:0] and_ln40_36_fu_2228_p2;
wire   [0:0] and_ln40_37_fu_2234_p2;
wire   [17:0] rsqrt_fu_2246_p4;
wire   [17:0] rsqrt_fu_2246_p7;
wire   [1:0] rsqrt_fu_2246_p8;
reg   [66:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
reg    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
wire    ap_ST_fsm_state34_blk;
wire    ap_ST_fsm_state35_blk;
wire    ap_ST_fsm_state36_blk;
wire    ap_ST_fsm_state37_blk;
wire    ap_ST_fsm_state38_blk;
wire    ap_ST_fsm_state39_blk;
wire    ap_ST_fsm_state40_blk;
wire    ap_ST_fsm_state41_blk;
wire    ap_ST_fsm_state42_blk;
wire    ap_ST_fsm_state43_blk;
wire    ap_ST_fsm_state44_blk;
wire    ap_ST_fsm_state45_blk;
wire    ap_ST_fsm_state46_blk;
wire    ap_ST_fsm_state47_blk;
wire    ap_ST_fsm_state48_blk;
wire    ap_ST_fsm_state49_blk;
reg    ap_ST_fsm_state50_blk;
wire    ap_ST_fsm_state51_blk;
wire    ap_ST_fsm_state52_blk;
wire    ap_ST_fsm_state53_blk;
wire    ap_ST_fsm_state54_blk;
wire    ap_ST_fsm_state55_blk;
wire    ap_ST_fsm_state56_blk;
wire    ap_ST_fsm_state57_blk;
wire    ap_ST_fsm_state58_blk;
wire    ap_ST_fsm_state59_blk;
wire    ap_ST_fsm_state60_blk;
wire    ap_ST_fsm_state61_blk;
wire    ap_ST_fsm_state62_blk;
wire    ap_ST_fsm_state63_blk;
wire    ap_ST_fsm_state64_blk;
wire    ap_ST_fsm_state65_blk;
wire    ap_ST_fsm_state66_blk;
reg    ap_ST_fsm_state67_blk;
wire   [29:0] tmp_s_fu_1428_p0;
wire   [0:0] tmp_s_fu_1428_p2;
wire   [0:0] tmp_517_fu_1720_p0;
wire  signed [1:0] ref_tmp_i_i_fu_1787_p1;
wire   [1:0] ref_tmp_i_i_fu_1787_p3;
wire   [1:0] ref_tmp_i_i_fu_1787_p5;
wire   [0:0] tobool134_i_fu_1900_p0;
wire  signed [1:0] Range1_all_ones_2_i_fu_2048_p1;
wire   [1:0] Range1_all_ones_2_i_fu_2048_p3;
wire   [1:0] Range1_all_ones_2_i_fu_2048_p5;
wire  signed [1:0] Range1_all_zeros_2_i_fu_2068_p1;
wire   [1:0] Range1_all_zeros_2_i_fu_2068_p3;
wire   [1:0] Range1_all_zeros_2_i_fu_2068_p5;
wire  signed [1:0] neg_src_0_i_fu_2145_p1;
wire   [1:0] neg_src_0_i_fu_2145_p3;
wire   [1:0] neg_src_0_i_fu_2145_p5;
wire  signed [1:0] rsqrt_fu_2246_p1;
wire   [1:0] rsqrt_fu_2246_p3;
wire   [1:0] rsqrt_fu_2246_p5;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 67'd1;
#0 grp_forward_19_Pipeline_VITIS_LOOP_32_2_fu_927_ap_start_reg = 1'b0;
#0 grp_forward_19_Pipeline_VITIS_LOOP_42_3_fu_933_ap_start_reg = 1'b0;
#0 t_06_fu_368 = 5'd0;
end

unet_pvm_top_forward_2_in_vec_RAM_AUTO_1R1W #(
    .DataWidth( 18 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
in_vec_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(in_vec_address0),
    .ce0(in_vec_ce0),
    .we0(in_vec_we0_local),
    .d0(in_vec_d0_local),
    .q0(in_vec_q0),
    .address1(in_vec_address1_local),
    .ce1(in_vec_ce1_local),
    .we1(in_vec_we1_local),
    .d1(in_vec_d1_local)
);

unet_pvm_top_forward_2_out_vec_RAM_AUTO_1R1W #(
    .DataWidth( 18 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
out_vec_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(out_vec_address0),
    .ce0(out_vec_ce0),
    .we0(out_vec_we0),
    .d0(grp_forward_19_Pipeline_VITIS_LOOP_42_3_fu_933_out_vec_d0),
    .q0(out_vec_q0),
    .address1(out_vec_address1_local),
    .ce1(out_vec_ce1_local),
    .q1(out_vec_q1)
);

unet_pvm_top_forward_19_Pipeline_VITIS_LOOP_32_2 grp_forward_19_Pipeline_VITIS_LOOP_32_2_fu_927(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_forward_19_Pipeline_VITIS_LOOP_32_2_fu_927_ap_start),
    .ap_done(grp_forward_19_Pipeline_VITIS_LOOP_32_2_fu_927_ap_done),
    .ap_idle(grp_forward_19_Pipeline_VITIS_LOOP_32_2_fu_927_ap_idle),
    .ap_ready(grp_forward_19_Pipeline_VITIS_LOOP_32_2_fu_927_ap_ready),
    .in_vec_address0(grp_forward_19_Pipeline_VITIS_LOOP_32_2_fu_927_in_vec_address0),
    .in_vec_ce0(grp_forward_19_Pipeline_VITIS_LOOP_32_2_fu_927_in_vec_ce0),
    .in_vec_q0(in_vec_q0),
    .sum_sq_out(grp_forward_19_Pipeline_VITIS_LOOP_32_2_fu_927_sum_sq_out),
    .sum_sq_out_ap_vld(grp_forward_19_Pipeline_VITIS_LOOP_32_2_fu_927_sum_sq_out_ap_vld)
);

unet_pvm_top_forward_19_Pipeline_VITIS_LOOP_42_3 grp_forward_19_Pipeline_VITIS_LOOP_42_3_fu_933(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_forward_19_Pipeline_VITIS_LOOP_42_3_fu_933_ap_start),
    .ap_done(grp_forward_19_Pipeline_VITIS_LOOP_42_3_fu_933_ap_done),
    .ap_idle(grp_forward_19_Pipeline_VITIS_LOOP_42_3_fu_933_ap_idle),
    .ap_ready(grp_forward_19_Pipeline_VITIS_LOOP_42_3_fu_933_ap_ready),
    .out_vec_address0(grp_forward_19_Pipeline_VITIS_LOOP_42_3_fu_933_out_vec_address0),
    .out_vec_ce0(grp_forward_19_Pipeline_VITIS_LOOP_42_3_fu_933_out_vec_ce0),
    .out_vec_we0(grp_forward_19_Pipeline_VITIS_LOOP_42_3_fu_933_out_vec_we0),
    .out_vec_d0(grp_forward_19_Pipeline_VITIS_LOOP_42_3_fu_933_out_vec_d0),
    .in_vec_address0(grp_forward_19_Pipeline_VITIS_LOOP_42_3_fu_933_in_vec_address0),
    .in_vec_ce0(grp_forward_19_Pipeline_VITIS_LOOP_42_3_fu_933_in_vec_ce0),
    .in_vec_q0(in_vec_q0),
    .conv7_i95(rsqrt_reg_2930)
);

unet_pvm_top_fdiv_32ns_32ns_32_12_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 12 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fdiv_32ns_32ns_32_12_no_dsp_1_U344(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(32'd1065353216),
    .din1(tmp_341_reg_2812),
    .ce(1'b1),
    .dout(grp_fu_940_p2)
);

unet_pvm_top_fpext_32ns_64_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
fpext_32ns_64_2_no_dsp_1_U345(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(div_reg_2817),
    .ce(1'b1),
    .dout(grp_fu_945_p1)
);

unet_pvm_top_fsqrt_32ns_32ns_32_12_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 12 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fsqrt_32ns_32ns_32_12_no_dsp_1_U346(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(32'd0),
    .din1(temp_sum_reg_2807),
    .ce(1'b1),
    .dout(grp_fu_948_p2)
);

unet_pvm_top_ctlz_30_30_1_1 #(
    .din_WIDTH( 30 ),
    .dout_WIDTH( 30 ))
ctlz_30_30_1_1_U347(
    .din(tmp_s_fu_1428_p1),
    .dout(tmp_s_fu_1428_p3)
);

unet_pvm_top_bitselect_1ns_54ns_6ns_1_1_1 #(
    .DATAWIDTH( 54 ),
    .ADDRWIDTH( 6 ))
bitselect_1ns_54ns_6ns_1_1_1_U348(
    .din(select_ln40_fu_1609_p3),
    .sel(tmp_517_fu_1720_p2),
    .dout(tmp_517_fu_1720_p3)
);

(* dissolve_hierarchy = "yes" *) unet_pvm_top_sparsemux_7_2_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 18 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 18 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 18 ),
    .def_WIDTH( 18 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 18 ))
sparsemux_7_2_18_1_1_U349(
    .din0(trunc_ln40_32_fu_1646_p1),
    .din1(add_ln40_13_fu_1747_p2),
    .din2(ref_tmp_i_i_fu_1787_p6),
    .def(ref_tmp_i_i_fu_1787_p7),
    .sel(ref_tmp_i_i_fu_1787_p8),
    .dout(ref_tmp_i_i_fu_1787_p9)
);

unet_pvm_top_bitselect_1ns_54ns_6ns_1_1_1 #(
    .DATAWIDTH( 54 ),
    .ADDRWIDTH( 6 ))
bitselect_1ns_54ns_6ns_1_1_1_U350(
    .din(select_ln40_fu_1609_p3),
    .sel(tobool134_i_fu_1900_p2),
    .dout(tobool134_i_fu_1900_p3)
);

(* dissolve_hierarchy = "yes" *) unet_pvm_top_sparsemux_7_2_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 1 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 1 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 1 ),
    .def_WIDTH( 1 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 1 ))
sparsemux_7_2_1_1_1_U351(
    .din0(Range1_all_ones_2_i_fu_2048_p2),
    .din1(lD_0_i_fu_1908_p2),
    .din2(xor_ln40_32_fu_1888_p2),
    .def(Range1_all_ones_2_i_fu_2048_p7),
    .sel(sel_tmp_fu_2040_p3),
    .dout(Range1_all_ones_2_i_fu_2048_p9)
);

(* dissolve_hierarchy = "yes" *) unet_pvm_top_sparsemux_7_2_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 1 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 1 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 1 ),
    .def_WIDTH( 1 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 1 ))
sparsemux_7_2_1_1_1_U352(
    .din0(Range1_all_zeros_2_i_fu_2068_p2),
    .din1(xor_ln40_20_fu_1986_p2),
    .din2(Range1_all_zeros_2_i_fu_2068_p6),
    .def(Range1_all_zeros_2_i_fu_2068_p7),
    .sel(sel_tmp_fu_2040_p3),
    .dout(Range1_all_zeros_2_i_fu_2068_p9)
);

(* dissolve_hierarchy = "yes" *) unet_pvm_top_sparsemux_7_2_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 1 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 1 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 1 ),
    .def_WIDTH( 1 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 1 ))
sparsemux_7_2_1_1_1_U353(
    .din0(neg_src_0_i_fu_2145_p2),
    .din1(neg_src_0_i_fu_2145_p4),
    .din2(1'd0),
    .def(neg_src_0_i_fu_2145_p7),
    .sel(neg_src_0_i_fu_2145_p8),
    .dout(neg_src_0_i_fu_2145_p9)
);

(* dissolve_hierarchy = "yes" *) unet_pvm_top_sparsemux_7_2_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 18 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 18 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 18 ),
    .def_WIDTH( 18 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 18 ))
sparsemux_7_2_18_1_1_U354(
    .din0(18'd0),
    .din1(rsqrt_fu_2246_p4),
    .din2(ref_tmp_i_i_reg_2872),
    .def(rsqrt_fu_2246_p7),
    .sel(rsqrt_fu_2246_p8),
    .dout(rsqrt_fu_2246_p9)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2) & (icmp_ln26_fu_961_p2 == 1'd1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_forward_19_Pipeline_VITIS_LOOP_32_2_fu_927_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state18)) begin
            grp_forward_19_Pipeline_VITIS_LOOP_32_2_fu_927_ap_start_reg <= 1'b1;
        end else if ((grp_forward_19_Pipeline_VITIS_LOOP_32_2_fu_927_ap_ready == 1'b1)) begin
            grp_forward_19_Pipeline_VITIS_LOOP_32_2_fu_927_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_forward_19_Pipeline_VITIS_LOOP_42_3_fu_933_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state49)) begin
            grp_forward_19_Pipeline_VITIS_LOOP_42_3_fu_933_ap_start_reg <= 1'b1;
        end else if ((grp_forward_19_Pipeline_VITIS_LOOP_42_3_fu_933_ap_ready == 1'b1)) begin
            grp_forward_19_Pipeline_VITIS_LOOP_42_3_fu_933_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        t_06_fu_368 <= 5'd0;
    end else if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2) & (icmp_ln26_fu_961_p2 == 1'd0))) begin
        t_06_fu_368 <= t_15_fu_967_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state48)) begin
        Range1_all_ones_2_i_reg_2918 <= Range1_all_ones_2_i_fu_2048_p9;
        Range1_all_zeros_2_i_reg_2925 <= Range1_all_zeros_2_i_fu_2068_p9;
        Range2_all_ones_1_i_reg_2908 <= Range2_all_ones_1_i_fu_1966_p3;
        carry_1_i_reg_2877 <= carry_1_i_fu_1813_p2;
        icmp_ln40_43_reg_2896 <= icmp_ln40_43_fu_1874_p2;
        icmp_ln40_49_reg_2884 <= icmp_ln40_49_fu_1846_p2;
        ref_tmp_i_i_reg_2872 <= ref_tmp_i_i_fu_1787_p9;
        tmp_521_reg_2889 <= ref_tmp_i_i_fu_1787_p9[32'd17];
        tmp_522_reg_2903 <= add_ln40_15_fu_1852_p2[32'd11];
        xor_ln40_20_reg_2913 <= xor_ln40_20_fu_1986_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state45)) begin
        div_reg_2817 <= grp_fu_940_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        icmp_ln39_reg_2791 <= icmp_ln39_fu_1397_p2;
        select_ln39_reg_2801 <= select_ln39_fu_1417_p3;
        tmp_514_reg_2796 <= select_ln39_6_fu_1385_p3[32'd16];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state47)) begin
        icmp_ln40_reg_2847 <= icmp_ln40_fu_1589_p2;
        sub_ln40_5_reg_2853 <= sub_ln40_5_fu_1595_p2;
        sub_ln40_reg_2842 <= sub_ln40_fu_1583_p2;
        tmp_516_reg_2822 <= bitcast_ln735_fu_1539_p1[32'd63];
        trunc_ln40_29_reg_2862 <= trunc_ln40_29_fu_1601_p1;
        trunc_ln40_30_reg_2867 <= trunc_ln40_30_fu_1605_p1;
        zext_ln40_17_reg_2837[51 : 0] <= zext_ln40_17_fu_1579_p1[51 : 0];
        zext_ln40_reg_2832[10 : 0] <= zext_ln40_fu_1563_p1[10 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state52)) begin
        out_vec_load_63_reg_2940 <= out_vec_q0;
        out_vec_load_reg_2935 <= out_vec_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state53)) begin
        out_vec_load_64_reg_2945 <= out_vec_q1;
        out_vec_load_65_reg_2950 <= out_vec_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state54)) begin
        out_vec_load_66_reg_2955 <= out_vec_q1;
        out_vec_load_67_reg_2960 <= out_vec_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state55)) begin
        out_vec_load_68_reg_2965 <= out_vec_q1;
        out_vec_load_69_reg_2970 <= out_vec_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        out_vec_load_70_reg_2975 <= out_vec_q1;
        out_vec_load_71_reg_2980 <= out_vec_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state57)) begin
        out_vec_load_72_reg_2985 <= out_vec_q1;
        out_vec_load_73_reg_2990 <= out_vec_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state58)) begin
        out_vec_load_74_reg_2995 <= out_vec_q1;
        out_vec_load_75_reg_3000 <= out_vec_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state59)) begin
        out_vec_load_76_reg_3005 <= out_vec_q1;
        out_vec_load_77_reg_3010 <= out_vec_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state60)) begin
        out_vec_load_78_reg_3015 <= out_vec_q1;
        out_vec_load_79_reg_3020 <= out_vec_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state61)) begin
        out_vec_load_80_reg_3025 <= out_vec_q1;
        out_vec_load_81_reg_3030 <= out_vec_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state62)) begin
        out_vec_load_82_reg_3035 <= out_vec_q1;
        out_vec_load_83_reg_3040 <= out_vec_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state63)) begin
        out_vec_load_84_reg_3045 <= out_vec_q1;
        out_vec_load_85_reg_3050 <= out_vec_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state64)) begin
        out_vec_load_86_reg_3055 <= out_vec_q1;
        out_vec_load_87_reg_3060 <= out_vec_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state65)) begin
        out_vec_load_88_reg_3065 <= out_vec_q1;
        out_vec_load_89_reg_3070 <= out_vec_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state66)) begin
        out_vec_load_90_reg_3075 <= out_vec_q1;
        out_vec_load_91_reg_3080 <= out_vec_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state49)) begin
        rsqrt_reg_2930 <= rsqrt_fu_2246_p9;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        temp_sum_reg_2807 <= temp_sum_fu_1532_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state33)) begin
        tmp_341_reg_2812 <= grp_fu_948_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2))) begin
        trunc_ln28_64_reg_2641 <= {{s_in_norm_dout[53:36]}};
        trunc_ln28_65_reg_2646 <= {{s_in_norm_dout[71:54]}};
        trunc_ln28_66_reg_2651 <= {{s_in_norm_dout[89:72]}};
        trunc_ln28_67_reg_2656 <= {{s_in_norm_dout[107:90]}};
        trunc_ln28_68_reg_2661 <= {{s_in_norm_dout[125:108]}};
        trunc_ln28_69_reg_2666 <= {{s_in_norm_dout[143:126]}};
        trunc_ln28_70_reg_2671 <= {{s_in_norm_dout[161:144]}};
        trunc_ln28_71_reg_2676 <= {{s_in_norm_dout[179:162]}};
        trunc_ln28_72_reg_2681 <= {{s_in_norm_dout[197:180]}};
        trunc_ln28_73_reg_2686 <= {{s_in_norm_dout[215:198]}};
        trunc_ln28_74_reg_2691 <= {{s_in_norm_dout[233:216]}};
        trunc_ln28_75_reg_2696 <= {{s_in_norm_dout[251:234]}};
        trunc_ln28_76_reg_2701 <= {{s_in_norm_dout[269:252]}};
        trunc_ln28_77_reg_2706 <= {{s_in_norm_dout[287:270]}};
        trunc_ln28_78_reg_2711 <= {{s_in_norm_dout[305:288]}};
        trunc_ln28_79_reg_2716 <= {{s_in_norm_dout[323:306]}};
        trunc_ln28_80_reg_2721 <= {{s_in_norm_dout[341:324]}};
        trunc_ln28_81_reg_2726 <= {{s_in_norm_dout[359:342]}};
        trunc_ln28_82_reg_2731 <= {{s_in_norm_dout[377:360]}};
        trunc_ln28_83_reg_2736 <= {{s_in_norm_dout[395:378]}};
        trunc_ln28_84_reg_2741 <= {{s_in_norm_dout[413:396]}};
        trunc_ln28_85_reg_2746 <= {{s_in_norm_dout[431:414]}};
        trunc_ln28_86_reg_2751 <= {{s_in_norm_dout[449:432]}};
        trunc_ln28_87_reg_2756 <= {{s_in_norm_dout[467:450]}};
        trunc_ln28_88_reg_2761 <= {{s_in_norm_dout[485:468]}};
        trunc_ln28_89_reg_2766 <= {{s_in_norm_dout[503:486]}};
        trunc_ln28_90_reg_2771 <= {{s_in_norm_dout[521:504]}};
        trunc_ln28_91_reg_2781 <= {{s_in_norm_dout[557:540]}};
        trunc_ln28_92_reg_2786 <= {{s_in_norm_dout[575:558]}};
        trunc_ln28_s_reg_2776 <= {{s_in_norm_dout[539:522]}};
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

always @ (*) begin
    if ((grp_forward_19_Pipeline_VITIS_LOOP_32_2_fu_927_ap_done == 1'b0)) begin
        ap_ST_fsm_state19_blk = 1'b1;
    end else begin
        ap_ST_fsm_state19_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state2)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

assign ap_ST_fsm_state34_blk = 1'b0;

assign ap_ST_fsm_state35_blk = 1'b0;

assign ap_ST_fsm_state36_blk = 1'b0;

assign ap_ST_fsm_state37_blk = 1'b0;

assign ap_ST_fsm_state38_blk = 1'b0;

assign ap_ST_fsm_state39_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state40_blk = 1'b0;

assign ap_ST_fsm_state41_blk = 1'b0;

assign ap_ST_fsm_state42_blk = 1'b0;

assign ap_ST_fsm_state43_blk = 1'b0;

assign ap_ST_fsm_state44_blk = 1'b0;

assign ap_ST_fsm_state45_blk = 1'b0;

assign ap_ST_fsm_state46_blk = 1'b0;

assign ap_ST_fsm_state47_blk = 1'b0;

assign ap_ST_fsm_state48_blk = 1'b0;

assign ap_ST_fsm_state49_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_forward_19_Pipeline_VITIS_LOOP_42_3_fu_933_ap_done == 1'b0)) begin
        ap_ST_fsm_state50_blk = 1'b1;
    end else begin
        ap_ST_fsm_state50_blk = 1'b0;
    end
end

assign ap_ST_fsm_state51_blk = 1'b0;

assign ap_ST_fsm_state52_blk = 1'b0;

assign ap_ST_fsm_state53_blk = 1'b0;

assign ap_ST_fsm_state54_blk = 1'b0;

assign ap_ST_fsm_state55_blk = 1'b0;

assign ap_ST_fsm_state56_blk = 1'b0;

assign ap_ST_fsm_state57_blk = 1'b0;

assign ap_ST_fsm_state58_blk = 1'b0;

assign ap_ST_fsm_state59_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state60_blk = 1'b0;

assign ap_ST_fsm_state61_blk = 1'b0;

assign ap_ST_fsm_state62_blk = 1'b0;

assign ap_ST_fsm_state63_blk = 1'b0;

assign ap_ST_fsm_state64_blk = 1'b0;

assign ap_ST_fsm_state65_blk = 1'b0;

assign ap_ST_fsm_state66_blk = 1'b0;

always @ (*) begin
    if ((s_norm_out_full_n == 1'b0)) begin
        ap_ST_fsm_state67_blk = 1'b1;
    end else begin
        ap_ST_fsm_state67_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2) & (icmp_ln26_fu_961_p2 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state50)) begin
        in_vec_address0 = grp_forward_19_Pipeline_VITIS_LOOP_42_3_fu_933_in_vec_address0;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        in_vec_address0 = grp_forward_19_Pipeline_VITIS_LOOP_32_2_fu_927_in_vec_address0;
    end else begin
        in_vec_address0 = in_vec_address0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        in_vec_address0_local = 64'd31;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        in_vec_address0_local = 64'd29;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        in_vec_address0_local = 64'd27;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        in_vec_address0_local = 64'd25;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        in_vec_address0_local = 64'd23;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        in_vec_address0_local = 64'd21;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        in_vec_address0_local = 64'd19;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        in_vec_address0_local = 64'd17;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        in_vec_address0_local = 64'd15;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        in_vec_address0_local = 64'd13;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        in_vec_address0_local = 64'd11;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        in_vec_address0_local = 64'd9;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        in_vec_address0_local = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        in_vec_address0_local = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        in_vec_address0_local = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        in_vec_address0_local = 64'd1;
    end else begin
        in_vec_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        in_vec_address1_local = 64'd30;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        in_vec_address1_local = 64'd28;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        in_vec_address1_local = 64'd26;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        in_vec_address1_local = 64'd24;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        in_vec_address1_local = 64'd22;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        in_vec_address1_local = 64'd20;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        in_vec_address1_local = 64'd18;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        in_vec_address1_local = 64'd16;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        in_vec_address1_local = 64'd14;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        in_vec_address1_local = 64'd12;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        in_vec_address1_local = 64'd10;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        in_vec_address1_local = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        in_vec_address1_local = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        in_vec_address1_local = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        in_vec_address1_local = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        in_vec_address1_local = 64'd0;
    end else begin
        in_vec_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state50)) begin
        in_vec_ce0 = grp_forward_19_Pipeline_VITIS_LOOP_42_3_fu_933_in_vec_ce0;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        in_vec_ce0 = grp_forward_19_Pipeline_VITIS_LOOP_32_2_fu_927_in_vec_ce0;
    end else begin
        in_vec_ce0 = in_vec_ce0_local;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | ((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2)))) begin
        in_vec_ce0_local = 1'b1;
    end else begin
        in_vec_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | ((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2)))) begin
        in_vec_ce1_local = 1'b1;
    end else begin
        in_vec_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        in_vec_d0_local = trunc_ln28_92_reg_2786;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        in_vec_d0_local = trunc_ln28_s_reg_2776;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        in_vec_d0_local = trunc_ln28_89_reg_2766;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        in_vec_d0_local = trunc_ln28_87_reg_2756;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        in_vec_d0_local = trunc_ln28_85_reg_2746;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        in_vec_d0_local = trunc_ln28_83_reg_2736;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        in_vec_d0_local = trunc_ln28_81_reg_2726;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        in_vec_d0_local = trunc_ln28_79_reg_2716;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        in_vec_d0_local = trunc_ln28_77_reg_2706;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        in_vec_d0_local = trunc_ln28_75_reg_2696;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        in_vec_d0_local = trunc_ln28_73_reg_2686;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        in_vec_d0_local = trunc_ln28_71_reg_2676;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        in_vec_d0_local = trunc_ln28_69_reg_2666;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        in_vec_d0_local = trunc_ln28_67_reg_2656;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        in_vec_d0_local = trunc_ln28_65_reg_2646;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        in_vec_d0_local = {{s_in_norm_dout[35:18]}};
    end else begin
        in_vec_d0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        in_vec_d1_local = trunc_ln28_91_reg_2781;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        in_vec_d1_local = trunc_ln28_90_reg_2771;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        in_vec_d1_local = trunc_ln28_88_reg_2761;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        in_vec_d1_local = trunc_ln28_86_reg_2751;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        in_vec_d1_local = trunc_ln28_84_reg_2741;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        in_vec_d1_local = trunc_ln28_82_reg_2731;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        in_vec_d1_local = trunc_ln28_80_reg_2721;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        in_vec_d1_local = trunc_ln28_78_reg_2711;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        in_vec_d1_local = trunc_ln28_76_reg_2701;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        in_vec_d1_local = trunc_ln28_74_reg_2691;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        in_vec_d1_local = trunc_ln28_72_reg_2681;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        in_vec_d1_local = trunc_ln28_70_reg_2671;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        in_vec_d1_local = trunc_ln28_68_reg_2661;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        in_vec_d1_local = trunc_ln28_66_reg_2651;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        in_vec_d1_local = trunc_ln28_64_reg_2641;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        in_vec_d1_local = trunc_ln28_fu_973_p1;
    end else begin
        in_vec_d1_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | ((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2) & (icmp_ln26_fu_961_p2 == 1'd0)))) begin
        in_vec_we0_local = 1'b1;
    end else begin
        in_vec_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | ((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2) & (icmp_ln26_fu_961_p2 == 1'd0)))) begin
        in_vec_we1_local = 1'b1;
    end else begin
        in_vec_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2) & (icmp_ln26_fu_961_p2 == 1'd1))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state50)) begin
        out_vec_address0 = grp_forward_19_Pipeline_VITIS_LOOP_42_3_fu_933_out_vec_address0;
    end else begin
        out_vec_address0 = out_vec_address0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state66)) begin
        out_vec_address0_local = 64'd31;
    end else if ((1'b1 == ap_CS_fsm_state65)) begin
        out_vec_address0_local = 64'd29;
    end else if ((1'b1 == ap_CS_fsm_state64)) begin
        out_vec_address0_local = 64'd27;
    end else if ((1'b1 == ap_CS_fsm_state63)) begin
        out_vec_address0_local = 64'd25;
    end else if ((1'b1 == ap_CS_fsm_state62)) begin
        out_vec_address0_local = 64'd23;
    end else if ((1'b1 == ap_CS_fsm_state61)) begin
        out_vec_address0_local = 64'd21;
    end else if ((1'b1 == ap_CS_fsm_state60)) begin
        out_vec_address0_local = 64'd19;
    end else if ((1'b1 == ap_CS_fsm_state59)) begin
        out_vec_address0_local = 64'd17;
    end else if ((1'b1 == ap_CS_fsm_state58)) begin
        out_vec_address0_local = 64'd15;
    end else if ((1'b1 == ap_CS_fsm_state57)) begin
        out_vec_address0_local = 64'd13;
    end else if ((1'b1 == ap_CS_fsm_state56)) begin
        out_vec_address0_local = 64'd11;
    end else if ((1'b1 == ap_CS_fsm_state55)) begin
        out_vec_address0_local = 64'd9;
    end else if ((1'b1 == ap_CS_fsm_state54)) begin
        out_vec_address0_local = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state53)) begin
        out_vec_address0_local = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state52)) begin
        out_vec_address0_local = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state51)) begin
        out_vec_address0_local = 64'd1;
    end else begin
        out_vec_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state66)) begin
        out_vec_address1_local = 64'd30;
    end else if ((1'b1 == ap_CS_fsm_state65)) begin
        out_vec_address1_local = 64'd28;
    end else if ((1'b1 == ap_CS_fsm_state64)) begin
        out_vec_address1_local = 64'd26;
    end else if ((1'b1 == ap_CS_fsm_state63)) begin
        out_vec_address1_local = 64'd24;
    end else if ((1'b1 == ap_CS_fsm_state62)) begin
        out_vec_address1_local = 64'd22;
    end else if ((1'b1 == ap_CS_fsm_state61)) begin
        out_vec_address1_local = 64'd20;
    end else if ((1'b1 == ap_CS_fsm_state60)) begin
        out_vec_address1_local = 64'd18;
    end else if ((1'b1 == ap_CS_fsm_state59)) begin
        out_vec_address1_local = 64'd16;
    end else if ((1'b1 == ap_CS_fsm_state58)) begin
        out_vec_address1_local = 64'd14;
    end else if ((1'b1 == ap_CS_fsm_state57)) begin
        out_vec_address1_local = 64'd12;
    end else if ((1'b1 == ap_CS_fsm_state56)) begin
        out_vec_address1_local = 64'd10;
    end else if ((1'b1 == ap_CS_fsm_state55)) begin
        out_vec_address1_local = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state54)) begin
        out_vec_address1_local = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state53)) begin
        out_vec_address1_local = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state52)) begin
        out_vec_address1_local = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state51)) begin
        out_vec_address1_local = 64'd0;
    end else begin
        out_vec_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state50)) begin
        out_vec_ce0 = grp_forward_19_Pipeline_VITIS_LOOP_42_3_fu_933_out_vec_ce0;
    end else begin
        out_vec_ce0 = out_vec_ce0_local;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state51) | (1'b1 == ap_CS_fsm_state66) | (1'b1 == ap_CS_fsm_state65) | (1'b1 == ap_CS_fsm_state64) | (1'b1 == ap_CS_fsm_state63) | (1'b1 == ap_CS_fsm_state62) | (1'b1 == ap_CS_fsm_state61) | (1'b1 == ap_CS_fsm_state60) | (1'b1 == ap_CS_fsm_state59) | (1'b1 == ap_CS_fsm_state58) | (1'b1 == ap_CS_fsm_state57) | (1'b1 == ap_CS_fsm_state56) | (1'b1 == ap_CS_fsm_state55) | (1'b1 == ap_CS_fsm_state54) | (1'b1 == ap_CS_fsm_state53) | (1'b1 == ap_CS_fsm_state52))) begin
        out_vec_ce0_local = 1'b1;
    end else begin
        out_vec_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state51) | (1'b1 == ap_CS_fsm_state66) | (1'b1 == ap_CS_fsm_state65) | (1'b1 == ap_CS_fsm_state64) | (1'b1 == ap_CS_fsm_state63) | (1'b1 == ap_CS_fsm_state62) | (1'b1 == ap_CS_fsm_state61) | (1'b1 == ap_CS_fsm_state60) | (1'b1 == ap_CS_fsm_state59) | (1'b1 == ap_CS_fsm_state58) | (1'b1 == ap_CS_fsm_state57) | (1'b1 == ap_CS_fsm_state56) | (1'b1 == ap_CS_fsm_state55) | (1'b1 == ap_CS_fsm_state54) | (1'b1 == ap_CS_fsm_state53) | (1'b1 == ap_CS_fsm_state52))) begin
        out_vec_ce1_local = 1'b1;
    end else begin
        out_vec_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state50)) begin
        out_vec_we0 = grp_forward_19_Pipeline_VITIS_LOOP_42_3_fu_933_out_vec_we0;
    end else begin
        out_vec_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln26_fu_961_p2 == 1'd0))) begin
        s_in_norm_blk_n = s_in_norm_empty_n;
    end else begin
        s_in_norm_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2) & (icmp_ln26_fu_961_p2 == 1'd0))) begin
        s_in_norm_read = 1'b1;
    end else begin
        s_in_norm_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state67)) begin
        s_norm_out_blk_n = s_norm_out_full_n;
    end else begin
        s_norm_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state67) & (s_norm_out_full_n == 1'b1))) begin
        s_norm_out_write = 1'b1;
    end else begin
        s_norm_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2) & (icmp_ln26_fu_961_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2) & (icmp_ln26_fu_961_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            if (((grp_forward_19_Pipeline_VITIS_LOOP_32_2_fu_927_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            ap_NS_fsm = ap_ST_fsm_state50;
        end
        ap_ST_fsm_state50 : begin
            if (((grp_forward_19_Pipeline_VITIS_LOOP_42_3_fu_933_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state50))) begin
                ap_NS_fsm = ap_ST_fsm_state51;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state50;
            end
        end
        ap_ST_fsm_state51 : begin
            ap_NS_fsm = ap_ST_fsm_state52;
        end
        ap_ST_fsm_state52 : begin
            ap_NS_fsm = ap_ST_fsm_state53;
        end
        ap_ST_fsm_state53 : begin
            ap_NS_fsm = ap_ST_fsm_state54;
        end
        ap_ST_fsm_state54 : begin
            ap_NS_fsm = ap_ST_fsm_state55;
        end
        ap_ST_fsm_state55 : begin
            ap_NS_fsm = ap_ST_fsm_state56;
        end
        ap_ST_fsm_state56 : begin
            ap_NS_fsm = ap_ST_fsm_state57;
        end
        ap_ST_fsm_state57 : begin
            ap_NS_fsm = ap_ST_fsm_state58;
        end
        ap_ST_fsm_state58 : begin
            ap_NS_fsm = ap_ST_fsm_state59;
        end
        ap_ST_fsm_state59 : begin
            ap_NS_fsm = ap_ST_fsm_state60;
        end
        ap_ST_fsm_state60 : begin
            ap_NS_fsm = ap_ST_fsm_state61;
        end
        ap_ST_fsm_state61 : begin
            ap_NS_fsm = ap_ST_fsm_state62;
        end
        ap_ST_fsm_state62 : begin
            ap_NS_fsm = ap_ST_fsm_state63;
        end
        ap_ST_fsm_state63 : begin
            ap_NS_fsm = ap_ST_fsm_state64;
        end
        ap_ST_fsm_state64 : begin
            ap_NS_fsm = ap_ST_fsm_state65;
        end
        ap_ST_fsm_state65 : begin
            ap_NS_fsm = ap_ST_fsm_state66;
        end
        ap_ST_fsm_state66 : begin
            ap_NS_fsm = ap_ST_fsm_state67;
        end
        ap_ST_fsm_state67 : begin
            if (((1'b1 == ap_CS_fsm_state67) & (s_norm_out_full_n == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state67;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign LD_fu_1524_p1 = pi_assign_fu_1512_p5[31:0];

assign Range1_all_ones_2_i_fu_2048_p2 = (lD_0_i_fu_1908_p2 & Range2_all_ones_1_i_fu_1966_p3);

assign Range1_all_ones_2_i_fu_2048_p7 = 'bx;

assign Range1_all_zeros_2_i_fu_2068_p2 = (xor_ln40_20_fu_1986_p2 & icmp_ln40_50_fu_1992_p2);

assign Range1_all_zeros_2_i_fu_2068_p6 = (xor_ln40_32_fu_1888_p2 | icmp_ln40_52_fu_2010_p2);

assign Range1_all_zeros_2_i_fu_2068_p7 = 'bx;

assign Range2_all_ones_1_i_fu_1966_p3 = ((icmp_ln40_47_fu_1920_p2[0:0] == 1'b1) ? icmp_ln40_48_fu_1946_p2 : xor_ln40_33_fu_1960_p2);

assign add_ln39_3_fu_1499_p2 = ($signed(select_ln39_8_fu_1481_p3) + $signed(sext_ln39_6_fu_1495_p1));

assign add_ln39_fu_1443_p2 = ($signed(trunc_ln39_5_fu_1436_p1) + $signed(5'd27));

assign add_ln40_13_fu_1747_p2 = (select_ln40_15_fu_1677_p3 + zext_ln40_13_fu_1743_p1);

assign add_ln40_14_fu_1831_p2 = ($signed(sext_ln40_5_fu_1827_p1) + $signed(zext_ln40_reg_2832));

assign add_ln40_15_fu_1852_p2 = (sub_ln40_5_reg_2853 + 12'd8);

assign add_ln40_16_fu_1861_p2 = (sub_ln40_5_reg_2853 + 12'd9);

assign add_ln40_fu_1619_p2 = ($signed(sub_ln40_5_reg_2853) + $signed(12'd4086));

assign and_ln40_23_fu_1974_p2 = (xor_ln40_32_fu_1888_p2 & icmp_ln40_46_fu_1914_p2);

assign and_ln40_26_fu_2101_p2 = (or_ln40_8_fu_2097_p2 & Range2_all_ones_1_i_reg_2908);

assign and_ln40_27_fu_2112_p2 = (carry_1_i_reg_2877 & Range1_all_ones_2_i_reg_2918);

assign and_ln40_28_fu_2186_p2 = (xor_ln40_25_fu_2181_p2 & or_ln40_9_fu_2176_p2);

assign and_ln40_29_fu_2192_p2 = (tmp_521_reg_2889 & deleted_ones_0_i_fu_2127_p2);

assign and_ln40_30_fu_2203_p2 = (xor_ln40_26_fu_2197_p2 & neg_src_0_i_fu_2145_p9);

assign and_ln40_31_fu_1773_p2 = (xor_ln40_27_fu_1767_p2 & icmp_ln40_37_fu_1614_p2);

assign and_ln40_32_fu_1807_p2 = (tmp_518_fu_1735_p3 & and_ln40_31_fu_1773_p2);

assign and_ln40_33_fu_2034_p2 = (or_ln40_12_fu_2028_p2 & icmp_ln40_51_fu_2004_p2);

assign and_ln40_34_fu_2133_p2 = (tmp_516_reg_2822 & icmp_ln40_43_reg_2896);

assign and_ln40_35_fu_2171_p2 = (xor_ln40_29_fu_2165_p2 & icmp_ln40_43_reg_2896);

assign and_ln40_36_fu_2228_p2 = (xor_ln40_30_fu_2223_p2 & or_ln40_10_fu_2209_p2);

assign and_ln40_37_fu_2234_p2 = (icmp_ln40_49_reg_2884 & and_ln40_36_fu_2228_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state33 = ap_CS_fsm[32'd32];

assign ap_CS_fsm_state34 = ap_CS_fsm[32'd33];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state45 = ap_CS_fsm[32'd44];

assign ap_CS_fsm_state46 = ap_CS_fsm[32'd45];

assign ap_CS_fsm_state47 = ap_CS_fsm[32'd46];

assign ap_CS_fsm_state48 = ap_CS_fsm[32'd47];

assign ap_CS_fsm_state49 = ap_CS_fsm[32'd48];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state50 = ap_CS_fsm[32'd49];

assign ap_CS_fsm_state51 = ap_CS_fsm[32'd50];

assign ap_CS_fsm_state52 = ap_CS_fsm[32'd51];

assign ap_CS_fsm_state53 = ap_CS_fsm[32'd52];

assign ap_CS_fsm_state54 = ap_CS_fsm[32'd53];

assign ap_CS_fsm_state55 = ap_CS_fsm[32'd54];

assign ap_CS_fsm_state56 = ap_CS_fsm[32'd55];

assign ap_CS_fsm_state57 = ap_CS_fsm[32'd56];

assign ap_CS_fsm_state58 = ap_CS_fsm[32'd57];

assign ap_CS_fsm_state59 = ap_CS_fsm[32'd58];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state60 = ap_CS_fsm[32'd59];

assign ap_CS_fsm_state61 = ap_CS_fsm[32'd60];

assign ap_CS_fsm_state62 = ap_CS_fsm[32'd61];

assign ap_CS_fsm_state63 = ap_CS_fsm[32'd62];

assign ap_CS_fsm_state64 = ap_CS_fsm[32'd63];

assign ap_CS_fsm_state65 = ap_CS_fsm[32'd64];

assign ap_CS_fsm_state66 = ap_CS_fsm[32'd65];

assign ap_CS_fsm_state67 = ap_CS_fsm[32'd66];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (real_start == 1'b0));
end

always @ (*) begin
    ap_block_state2 = ((icmp_ln26_fu_961_p2 == 1'd0) & (s_in_norm_empty_n == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign ashr_ln40_fu_1667_p2 = $signed(select_ln40_fu_1609_p3) >>> zext_ln40_12_fu_1663_p1;

assign bitcast_ln735_fu_1539_p1 = grp_fu_945_p1;

assign bitcast_ln777_fu_1528_p1 = LD_fu_1524_p1;

assign carry_1_i_fu_1813_p2 = (xor_ln40_fu_1761_p2 & and_ln40_32_fu_1807_p2);

assign cond193_i_fu_2106_p3 = ((carry_1_i_reg_2877[0:0] == 1'b1) ? and_ln40_26_fu_2101_p2 : Range1_all_ones_2_i_reg_2918);

assign cond64_i_fu_1728_p3 = ((icmp_ln40_40_fu_1685_p2[0:0] == 1'b1) ? tmp_516_reg_2822 : tmp_517_fu_1720_p3);

assign deleted_ones_0_i_fu_2127_p2 = (not_icmp_ln40_4354_fu_2122_p2 | cond193_i_fu_2106_p3);

assign grp_forward_19_Pipeline_VITIS_LOOP_32_2_fu_927_ap_start = grp_forward_19_Pipeline_VITIS_LOOP_32_2_fu_927_ap_start_reg;

assign grp_forward_19_Pipeline_VITIS_LOOP_42_3_fu_933_ap_start = grp_forward_19_Pipeline_VITIS_LOOP_42_3_fu_933_ap_start_reg;

assign icmp_ln26_fu_961_p2 = ((t_06_fu_368 == 5'd16) ? 1'b1 : 1'b0);

assign icmp_ln39_fu_1397_p2 = ((select_ln39_6_fu_1385_p3 == 17'd0) ? 1'b1 : 1'b0);

assign icmp_ln40_37_fu_1614_p2 = (($signed(sub_ln40_5_reg_2853) > $signed(12'd10)) ? 1'b1 : 1'b0);

assign icmp_ln40_38_fu_1641_p2 = ((sub_ln40_5_reg_2853 == 12'd10) ? 1'b1 : 1'b0);

assign icmp_ln40_39_fu_1650_p2 = ((select_ln40_14_fu_1633_p3 < 11'd54) ? 1'b1 : 1'b0);

assign icmp_ln40_40_fu_1685_p2 = (($signed(add_ln40_fu_1619_p2) > $signed(12'd54)) ? 1'b1 : 1'b0);

assign icmp_ln40_41_fu_1691_p2 = ((select_ln40_14_fu_1633_p3 < 11'd18) ? 1'b1 : 1'b0);

assign icmp_ln40_43_fu_1874_p2 = (($signed(add_ln40_15_fu_1852_p2) < $signed(12'd54)) ? 1'b1 : 1'b0);

assign icmp_ln40_45_fu_1894_p2 = ((add_ln40_15_fu_1852_p2 < 12'd54) ? 1'b1 : 1'b0);

assign icmp_ln40_46_fu_1914_p2 = (($signed(add_ln40_16_fu_1861_p2) < $signed(12'd54)) ? 1'b1 : 1'b0);

assign icmp_ln40_47_fu_1920_p2 = ((add_ln40_16_fu_1861_p2 < 12'd54) ? 1'b1 : 1'b0);

assign icmp_ln40_48_fu_1946_p2 = ((lshr_ln40_fu_1934_p2 == lshr_ln40_3_fu_1940_p2) ? 1'b1 : 1'b0);

assign icmp_ln40_49_fu_1846_p2 = (($signed(tmp_520_fu_1836_p4) > $signed(9'd0)) ? 1'b1 : 1'b0);

assign icmp_ln40_50_fu_1992_p2 = ((lshr_ln40_fu_1934_p2 == 54'd0) ? 1'b1 : 1'b0);

assign icmp_ln40_51_fu_2004_p2 = ((add_ln40_16_fu_1861_p2 == 12'd54) ? 1'b1 : 1'b0);

assign icmp_ln40_52_fu_2010_p2 = ((select_ln40_fu_1609_p3 == 54'd0) ? 1'b1 : 1'b0);

assign icmp_ln40_fu_1589_p2 = ((trunc_ln40_fu_1543_p1 == 63'd0) ? 1'b1 : 1'b0);

assign lD_0_i_fu_1908_p2 = (tobool134_i_fu_1900_p3 & icmp_ln40_45_fu_1894_p2);

assign lshr_ln39_3_fu_1459_p4 = {{shl_ln39_fu_1453_p2[40:1]}};

assign lshr_ln40_3_fu_1940_p2 = 54'd18014398509481983 >> zext_ln40_16_fu_1930_p1;

assign lshr_ln40_fu_1934_p2 = select_ln40_fu_1609_p3 >> zext_ln40_16_fu_1930_p1;

assign neg_src_0_i_fu_2145_p2 = (tmp_521_reg_2889 & tmp_516_reg_2822);

assign neg_src_0_i_fu_2145_p4 = (1'd1 ^ and_ln40_27_fu_2112_p2);

assign neg_src_0_i_fu_2145_p7 = 'bx;

assign neg_src_0_i_fu_2145_p8 = {{not_icmp_ln40_4354_fu_2122_p2}, {and_ln40_34_fu_2133_p2}};

assign not_icmp_ln40_4354_fu_2122_p2 = (icmp_ln40_43_reg_2896 ^ 1'd1);

assign or_ln40_10_fu_2209_p2 = (and_ln40_30_fu_2203_p2 | and_ln40_28_fu_2186_p2);

assign or_ln40_12_fu_2028_p2 = (xor_ln40_34_fu_2022_p2 | tmp_522_fu_1880_p3);

assign or_ln40_8_fu_2097_p2 = (xor_ln40_20_reg_2913 | tmp_522_reg_2903);

assign or_ln40_9_fu_2176_p2 = (tmp_521_reg_2889 | and_ln40_35_fu_2171_p2);

assign or_ln40_s_fu_1819_p3 = {{10'd513}, {icmp_ln40_37_fu_1614_p2}};

assign pi_assign_fu_1512_p5 = {{zext_ln39_15_fu_1469_p1[63:32]}, {tmp_fu_1505_p3}, {zext_ln39_15_fu_1469_p1[22:0]}};

assign ref_tmp_i_i_fu_1787_p6 = ((icmp_ln40_41_fu_1691_p2[0:0] == 1'b1) ? shl_ln40_fu_1701_p2 : 18'd0);

assign ref_tmp_i_i_fu_1787_p7 = 'bx;

assign ref_tmp_i_i_fu_1787_p8 = {{icmp_ln40_38_fu_1641_p2}, {and_ln40_31_fu_1773_p2}};

assign rsqrt_fu_2246_p4 = ((and_ln40_28_fu_2186_p2[0:0] == 1'b1) ? 18'd131071 : 18'd131072);

assign rsqrt_fu_2246_p7 = 'bx;

assign rsqrt_fu_2246_p8 = {{icmp_ln40_reg_2847}, {and_ln40_37_fu_2234_p2}};

assign s_norm_out_din = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{out_vec_q0}, {out_vec_q1}}, {out_vec_load_91_reg_3080}}, {out_vec_load_90_reg_3075}}, {out_vec_load_89_reg_3070}}, {out_vec_load_88_reg_3065}}, {out_vec_load_87_reg_3060}}, {out_vec_load_86_reg_3055}}, {out_vec_load_85_reg_3050}}, {out_vec_load_84_reg_3045}}, {out_vec_load_83_reg_3040}}, {out_vec_load_82_reg_3035}}, {out_vec_load_81_reg_3030}}, {out_vec_load_80_reg_3025}}, {out_vec_load_79_reg_3020}}, {out_vec_load_78_reg_3015}}, {out_vec_load_77_reg_3010}}, {out_vec_load_76_reg_3005}}, {out_vec_load_75_reg_3000}}, {out_vec_load_74_reg_2995}}, {out_vec_load_73_reg_2990}}, {out_vec_load_72_reg_2985}}, {out_vec_load_71_reg_2980}}, {out_vec_load_70_reg_2975}}, {out_vec_load_69_reg_2970}}, {out_vec_load_68_reg_2965}}, {out_vec_load_67_reg_2960}}, {out_vec_load_66_reg_2955}}, {out_vec_load_65_reg_2950}}, {out_vec_load_64_reg_2945}}, {out_vec_load_63_reg_2940}}, {out_vec_load_reg_2935}};

assign sel_tmp_fu_2040_p3 = {{and_ln40_23_fu_1974_p2}, {and_ln40_33_fu_2034_p2}};

assign select_ln39_6_fu_1385_p3 = ((tmp_513_fu_1333_p3[0:0] == 1'b1) ? sub_ln39_8_fu_1361_p2 : zext_ln39_16_fu_1381_p1);

assign select_ln39_8_fu_1481_p3 = ((tmp_515_fu_1473_p3[0:0] == 1'b1) ? 8'd127 : 8'd126);

assign select_ln39_fu_1417_p3 = ((tmp_514_fu_1403_p3[0:0] == 1'b1) ? sub_ln39_fu_1411_p2 : trunc_ln39_fu_1393_p1);

assign select_ln40_14_fu_1633_p3 = ((icmp_ln40_37_fu_1614_p2[0:0] == 1'b1) ? trunc_ln40_31_fu_1624_p1 : sub_ln40_6_fu_1628_p2);

assign select_ln40_14cast_fu_1697_p1 = select_ln40_14_fu_1633_p3;

assign select_ln40_15_fu_1677_p3 = ((icmp_ln40_39_fu_1650_p2[0:0] == 1'b1) ? trunc_ln40_33_fu_1673_p1 : select_ln40_20_fu_1656_p3);

assign select_ln40_17_fu_2092_p3 = ((carry_1_i_reg_2877[0:0] == 1'b1) ? Range1_all_ones_2_i_reg_2918 : Range1_all_zeros_2_i_reg_2925);

assign select_ln40_20_fu_1656_p3 = ((tmp_516_reg_2822[0:0] == 1'b1) ? 18'd262143 : 18'd0);

assign select_ln40_fu_1609_p3 = ((tmp_516_reg_2822[0:0] == 1'b1) ? sub_ln40_reg_2842 : zext_ln40_17_reg_2837);

assign sext_ln39_6_fu_1495_p1 = $signed(sub_ln39_9_fu_1489_p2);

assign sext_ln39_7_fu_1377_p1 = $signed(trunc_ln39_6_fu_1367_p4);

assign sext_ln39_fu_1329_p1 = $signed(shl_ln_fu_1321_p3);

assign sext_ln40_5_fu_1827_p1 = $signed(or_ln40_s_fu_1819_p3);

assign shl_ln39_fu_1453_p2 = zext_ln39_13_fu_1440_p1 << zext_ln39_14_fu_1449_p1;

assign shl_ln40_fu_1701_p2 = trunc_ln40_32_fu_1646_p1 << select_ln40_14cast_fu_1697_p1;

assign shl_ln_fu_1321_p3 = {{grp_forward_19_Pipeline_VITIS_LOOP_32_2_fu_927_sum_sq_out}, {10'd0}};

assign start_out = real_start;

assign sub_ln39_7_fu_1341_p2 = ($signed(29'd0) - $signed(sext_ln39_fu_1329_p1));

assign sub_ln39_8_fu_1361_p2 = (17'd0 - zext_ln39_fu_1357_p1);

assign sub_ln39_9_fu_1489_p2 = ($signed(5'd20) - $signed(trunc_ln39_5_fu_1436_p1));

assign sub_ln39_fu_1411_p2 = (16'd0 - trunc_ln39_fu_1393_p1);

assign sub_ln40_5_fu_1595_p2 = (12'd1075 - zext_ln40_fu_1563_p1);

assign sub_ln40_6_fu_1628_p2 = (11'd10 - trunc_ln40_30_reg_2867);

assign sub_ln40_fu_1583_p2 = (54'd0 - zext_ln40_17_fu_1579_p1);

assign t_15_fu_967_p2 = (t_06_fu_368 + 5'd1);

assign temp_sum_fu_1532_p3 = ((icmp_ln39_reg_2791[0:0] == 1'b1) ? 32'd0 : bitcast_ln777_fu_1528_p1);

assign tmp_342_fu_1555_p3 = {{bitcast_ln735_fu_1539_p1[62:52]}};

assign tmp_41_fu_1347_p4 = {{sub_ln39_7_fu_1341_p2[28:13]}};

assign tmp_513_fu_1333_p3 = grp_forward_19_Pipeline_VITIS_LOOP_32_2_fu_927_sum_sq_out[32'd17];

assign tmp_514_fu_1403_p3 = select_ln39_6_fu_1385_p3[32'd16];

assign tmp_515_fu_1473_p3 = shl_ln39_fu_1453_p2[32'd25];

assign tmp_517_fu_1720_p2 = ($signed(trunc_ln40_29_reg_2862) + $signed(6'd53));

assign tmp_518_fu_1735_p3 = select_ln40_15_fu_1677_p3[32'd17];

assign tmp_519_fu_1753_p3 = add_ln40_13_fu_1747_p2[32'd17];

assign tmp_520_fu_1836_p4 = {{add_ln40_14_fu_1831_p2[11:3]}};

assign tmp_522_fu_1880_p3 = add_ln40_15_fu_1852_p2[32'd11];

assign tmp_523_fu_1952_p3 = add_ln40_16_fu_1861_p2[32'd11];

assign tmp_fu_1505_p3 = {{tmp_514_reg_2796}, {add_ln39_3_fu_1499_p2}};

assign tmp_s_fu_1428_p1 = select_ln39_reg_2801;

assign tobool134_i_fu_1900_p2 = add_ln40_15_fu_1852_p2[5:0];

assign trunc_ln28_fu_973_p1 = s_in_norm_dout[17:0];

assign trunc_ln39_5_fu_1436_p1 = tmp_s_fu_1428_p3[4:0];

assign trunc_ln39_6_fu_1367_p4 = {{grp_forward_19_Pipeline_VITIS_LOOP_32_2_fu_927_sum_sq_out[17:3]}};

assign trunc_ln39_fu_1393_p1 = select_ln39_6_fu_1385_p3[15:0];

assign trunc_ln40_28_fu_1567_p1 = bitcast_ln735_fu_1539_p1[51:0];

assign trunc_ln40_29_fu_1601_p1 = sub_ln40_5_fu_1595_p2[5:0];

assign trunc_ln40_30_fu_1605_p1 = sub_ln40_5_fu_1595_p2[10:0];

assign trunc_ln40_31_fu_1624_p1 = add_ln40_fu_1619_p2[10:0];

assign trunc_ln40_32_fu_1646_p1 = select_ln40_fu_1609_p3[17:0];

assign trunc_ln40_33_fu_1673_p1 = ashr_ln40_fu_1667_p2[17:0];

assign trunc_ln40_36_fu_1926_p1 = add_ln40_16_fu_1861_p2[5:0];

assign trunc_ln40_fu_1543_p1 = bitcast_ln735_fu_1539_p1[62:0];

assign xor_ln40_20_fu_1986_p2 = (lD_0_i_fu_1908_p2 ^ 1'd1);

assign xor_ln40_25_fu_2181_p2 = (tmp_516_reg_2822 ^ 1'd1);

assign xor_ln40_26_fu_2197_p2 = (1'd1 ^ and_ln40_29_fu_2192_p2);

assign xor_ln40_27_fu_1767_p2 = (icmp_ln40_38_fu_1641_p2 ^ 1'd1);

assign xor_ln40_29_fu_2165_p2 = (select_ln40_17_fu_2092_p3 ^ 1'd1);

assign xor_ln40_30_fu_2223_p2 = (icmp_ln40_reg_2847 ^ 1'd1);

assign xor_ln40_32_fu_1888_p2 = (tmp_522_fu_1880_p3 ^ 1'd1);

assign xor_ln40_33_fu_1960_p2 = (tmp_523_fu_1952_p3 ^ 1'd1);

assign xor_ln40_34_fu_2022_p2 = (icmp_ln40_46_fu_1914_p2 ^ 1'd1);

assign xor_ln40_fu_1761_p2 = (tmp_519_fu_1753_p3 ^ 1'd1);

assign zext_ln39_13_fu_1440_p1 = select_ln39_reg_2801;

assign zext_ln39_14_fu_1449_p1 = add_ln39_fu_1443_p2;

assign zext_ln39_15_fu_1469_p1 = lshr_ln39_3_fu_1459_p4;

assign zext_ln39_16_fu_1381_p1 = $unsigned(sext_ln39_7_fu_1377_p1);

assign zext_ln39_fu_1357_p1 = tmp_41_fu_1347_p4;

assign zext_ln40_12_fu_1663_p1 = select_ln40_14_fu_1633_p3;

assign zext_ln40_13_fu_1743_p1 = cond64_i_fu_1728_p3;

assign zext_ln40_14_cast_fu_1571_p3 = {{1'd1}, {trunc_ln40_28_fu_1567_p1}};

assign zext_ln40_16_fu_1930_p1 = trunc_ln40_36_fu_1926_p1;

assign zext_ln40_17_fu_1579_p1 = zext_ln40_14_cast_fu_1571_p3;

assign zext_ln40_fu_1563_p1 = tmp_342_fu_1555_p3;

always @ (posedge ap_clk) begin
    zext_ln40_reg_2832[11] <= 1'b0;
    zext_ln40_17_reg_2837[53:52] <= 2'b01;
end

endmodule //unet_pvm_top_forward_19
