// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module unet_pvm_top_pvm_split_and_norm_config_enc5_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        mamba_in_0_din,
        mamba_in_0_full_n,
        mamba_in_0_write,
        mamba_in_1_din,
        mamba_in_1_full_n,
        mamba_in_1_write,
        mamba_in_2_din,
        mamba_in_2_full_n,
        mamba_in_2_write,
        mamba_in_3_din,
        mamba_in_3_full_n,
        mamba_in_3_write,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_address0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_ce0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_q0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_address0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_ce0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_q0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_address0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_ce0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_q0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_address0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_ce0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_q0,
        grp_fu_356_p_din0,
        grp_fu_356_p_din1,
        grp_fu_356_p_dout0,
        grp_fu_356_p_ce,
        grp_fu_360_p_din0,
        grp_fu_360_p_dout0,
        grp_fu_360_p_ce,
        grp_fu_363_p_din0,
        grp_fu_363_p_din1,
        grp_fu_363_p_dout0,
        grp_fu_363_p_ce
);

parameter    ap_ST_fsm_state1 = 37'd1;
parameter    ap_ST_fsm_state2 = 37'd2;
parameter    ap_ST_fsm_state3 = 37'd4;
parameter    ap_ST_fsm_state4 = 37'd8;
parameter    ap_ST_fsm_state5 = 37'd16;
parameter    ap_ST_fsm_state6 = 37'd32;
parameter    ap_ST_fsm_state7 = 37'd64;
parameter    ap_ST_fsm_state8 = 37'd128;
parameter    ap_ST_fsm_state9 = 37'd256;
parameter    ap_ST_fsm_state10 = 37'd512;
parameter    ap_ST_fsm_state11 = 37'd1024;
parameter    ap_ST_fsm_state12 = 37'd2048;
parameter    ap_ST_fsm_state13 = 37'd4096;
parameter    ap_ST_fsm_state14 = 37'd8192;
parameter    ap_ST_fsm_state15 = 37'd16384;
parameter    ap_ST_fsm_state16 = 37'd32768;
parameter    ap_ST_fsm_state17 = 37'd65536;
parameter    ap_ST_fsm_state18 = 37'd131072;
parameter    ap_ST_fsm_state19 = 37'd262144;
parameter    ap_ST_fsm_state20 = 37'd524288;
parameter    ap_ST_fsm_state21 = 37'd1048576;
parameter    ap_ST_fsm_state22 = 37'd2097152;
parameter    ap_ST_fsm_state23 = 37'd4194304;
parameter    ap_ST_fsm_state24 = 37'd8388608;
parameter    ap_ST_fsm_state25 = 37'd16777216;
parameter    ap_ST_fsm_state26 = 37'd33554432;
parameter    ap_ST_fsm_state27 = 37'd67108864;
parameter    ap_ST_fsm_state28 = 37'd134217728;
parameter    ap_ST_fsm_state29 = 37'd268435456;
parameter    ap_ST_fsm_state30 = 37'd536870912;
parameter    ap_ST_fsm_state31 = 37'd1073741824;
parameter    ap_ST_fsm_state32 = 37'd2147483648;
parameter    ap_ST_fsm_state33 = 37'd4294967296;
parameter    ap_ST_fsm_state34 = 37'd8589934592;
parameter    ap_ST_fsm_state35 = 37'd17179869184;
parameter    ap_ST_fsm_state36 = 37'd34359738368;
parameter    ap_ST_fsm_state37 = 37'd68719476736;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [575:0] mamba_in_0_din;
input   mamba_in_0_full_n;
output   mamba_in_0_write;
output  [575:0] mamba_in_1_din;
input   mamba_in_1_full_n;
output   mamba_in_1_write;
output  [575:0] mamba_in_2_din;
input   mamba_in_2_full_n;
output   mamba_in_2_write;
output  [575:0] mamba_in_3_din;
input   mamba_in_3_full_n;
output   mamba_in_3_write;
output  [6:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_address0;
output   unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_ce0;
input  [17:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_q0;
output  [6:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_address0;
output   unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_ce0;
input  [17:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_q0;
output  [6:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_address0;
output   unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_ce0;
input  [17:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_q0;
output  [6:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_address0;
output   unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_ce0;
input  [17:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_q0;
output  [31:0] grp_fu_356_p_din0;
output  [31:0] grp_fu_356_p_din1;
input  [31:0] grp_fu_356_p_dout0;
output   grp_fu_356_p_ce;
output  [31:0] grp_fu_360_p_din0;
input  [63:0] grp_fu_360_p_dout0;
output   grp_fu_360_p_ce;
output  [31:0] grp_fu_363_p_din0;
output  [31:0] grp_fu_363_p_din1;
input  [31:0] grp_fu_363_p_dout0;
output   grp_fu_363_p_ce;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [36:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [3:0] trunc_ln22_fu_481_p1;
reg   [3:0] trunc_ln22_reg_1904;
wire    ap_CS_fsm_state2;
wire   [17:0] mean_fu_710_p3;
reg   [17:0] mean_reg_2005;
wire    ap_CS_fsm_state4;
wire   [0:0] icmp_ln44_fu_822_p2;
reg   [0:0] icmp_ln44_reg_2011;
wire    ap_CS_fsm_state6;
wire   [0:0] tmp_73_fu_828_p3;
reg   [0:0] tmp_73_reg_2016;
wire   [16:0] select_ln44_fu_842_p3;
reg   [16:0] select_ln44_reg_2021;
wire   [31:0] temp_var_fu_957_p3;
reg   [31:0] temp_var_reg_2027;
wire    ap_CS_fsm_state7;
reg   [31:0] tmp_20_reg_2032;
wire    ap_CS_fsm_state19;
reg   [31:0] div_reg_2037;
wire    ap_CS_fsm_state31;
reg   [0:0] tmp_75_reg_2042;
wire    ap_CS_fsm_state33;
wire   [11:0] zext_ln45_fu_988_p1;
reg   [11:0] zext_ln45_reg_2052;
wire   [53:0] zext_ln45_1_fu_1004_p1;
reg   [53:0] zext_ln45_1_reg_2057;
wire   [53:0] sub_ln45_fu_1008_p2;
reg   [53:0] sub_ln45_reg_2062;
wire   [0:0] icmp_ln45_fu_1014_p2;
reg   [0:0] icmp_ln45_reg_2067;
wire   [11:0] sub_ln45_1_fu_1020_p2;
reg   [11:0] sub_ln45_1_reg_2073;
wire   [5:0] trunc_ln45_2_fu_1026_p1;
reg   [5:0] trunc_ln45_2_reg_2082;
wire   [10:0] trunc_ln45_3_fu_1030_p1;
reg   [10:0] trunc_ln45_3_reg_2087;
wire   [17:0] ref_tmp_i_i_fu_1212_p9;
reg   [17:0] ref_tmp_i_i_reg_2092;
wire    ap_CS_fsm_state34;
wire   [0:0] carry_1_i_fu_1238_p2;
reg   [0:0] carry_1_i_reg_2097;
wire   [0:0] icmp_ln45_6_fu_1271_p2;
reg   [0:0] icmp_ln45_6_reg_2104;
reg   [0:0] tmp_80_reg_2109;
wire   [0:0] icmp_ln45_7_fu_1299_p2;
reg   [0:0] icmp_ln45_7_reg_2116;
wire   [0:0] tmp_81_fu_1305_p3;
reg   [0:0] tmp_81_reg_2123;
wire   [0:0] Range2_all_ones_1_i_fu_1391_p3;
reg   [0:0] Range2_all_ones_1_i_reg_2128;
wire   [0:0] xor_ln45_1_fu_1411_p2;
reg   [0:0] xor_ln45_1_reg_2133;
wire   [0:0] Range1_all_ones_2_i_fu_1473_p9;
reg   [0:0] Range1_all_ones_2_i_reg_2138;
wire   [0:0] Range1_all_zeros_2_i_fu_1493_p9;
reg   [0:0] Range1_all_zeros_2_i_reg_2145;
wire   [17:0] rsqrt_fu_1671_p9;
reg   [17:0] rsqrt_reg_2150;
wire    ap_CS_fsm_state35;
wire    grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_ap_start;
wire    grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_ap_done;
wire    grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_ap_idle;
wire    grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_ap_ready;
wire   [17:0] grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_31_out;
wire    grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_31_out_ap_vld;
wire   [17:0] grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_30_out;
wire    grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_30_out_ap_vld;
wire   [17:0] grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_29_out;
wire    grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_29_out_ap_vld;
wire   [17:0] grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_28_out;
wire    grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_28_out_ap_vld;
wire   [17:0] grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_27_out;
wire    grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_27_out_ap_vld;
wire   [17:0] grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_26_out;
wire    grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_26_out_ap_vld;
wire   [17:0] grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_25_out;
wire    grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_25_out_ap_vld;
wire   [17:0] grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_24_out;
wire    grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_24_out_ap_vld;
wire   [17:0] grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_23_out;
wire    grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_23_out_ap_vld;
wire   [17:0] grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_22_out;
wire    grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_22_out_ap_vld;
wire   [17:0] grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_21_out;
wire    grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_21_out_ap_vld;
wire   [17:0] grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_20_out;
wire    grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_20_out_ap_vld;
wire   [17:0] grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_19_out;
wire    grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_19_out_ap_vld;
wire   [17:0] grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_18_out;
wire    grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_18_out_ap_vld;
wire   [17:0] grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_17_out;
wire    grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_17_out_ap_vld;
wire   [17:0] grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_16_out;
wire    grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_16_out_ap_vld;
wire   [17:0] grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_15_out;
wire    grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_15_out_ap_vld;
wire   [17:0] grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_14_out;
wire    grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_14_out_ap_vld;
wire   [17:0] grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_13_out;
wire    grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_13_out_ap_vld;
wire   [17:0] grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_12_out;
wire    grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_12_out_ap_vld;
wire   [17:0] grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_11_out;
wire    grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_11_out_ap_vld;
wire   [17:0] grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_10_out;
wire    grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_10_out_ap_vld;
wire   [17:0] grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_9_out;
wire    grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_9_out_ap_vld;
wire   [17:0] grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_8_out;
wire    grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_8_out_ap_vld;
wire   [17:0] grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_7_out;
wire    grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_7_out_ap_vld;
wire   [17:0] grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_6_out;
wire    grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_6_out_ap_vld;
wire   [17:0] grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_5_out;
wire    grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_5_out_ap_vld;
wire   [17:0] grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_4_out;
wire    grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_4_out_ap_vld;
wire   [17:0] grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_3_out;
wire    grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_3_out_ap_vld;
wire   [17:0] grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_2_out;
wire    grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_2_out_ap_vld;
wire   [17:0] grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_1_out;
wire    grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_1_out_ap_vld;
wire   [17:0] grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_out;
wire    grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_out_ap_vld;
wire   [17:0] grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_mean_1_out;
wire    grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_mean_1_out_ap_vld;
wire   [6:0] grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_address0;
wire    grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_ce0;
wire   [6:0] grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_address0;
wire    grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_ce0;
wire   [6:0] grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_address0;
wire    grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_ce0;
wire   [6:0] grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_address0;
wire    grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_ce0;
wire    grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_37_3_fu_364_ap_start;
wire    grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_37_3_fu_364_ap_done;
wire    grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_37_3_fu_364_ap_idle;
wire    grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_37_3_fu_364_ap_ready;
wire   [17:0] grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_37_3_fu_364_var_1_out;
wire    grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_37_3_fu_364_var_1_out_ap_vld;
wire    grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_48_4_fu_402_ap_start;
wire    grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_48_4_fu_402_ap_done;
wire    grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_48_4_fu_402_ap_idle;
wire    grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_48_4_fu_402_ap_ready;
wire   [575:0] grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_48_4_fu_402_mamba_in_2_din;
wire    grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_48_4_fu_402_mamba_in_2_write;
wire   [575:0] grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_48_4_fu_402_mamba_in_1_din;
wire    grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_48_4_fu_402_mamba_in_1_write;
wire   [575:0] grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_48_4_fu_402_mamba_in_0_din;
wire    grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_48_4_fu_402_mamba_in_0_write;
wire   [575:0] grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_48_4_fu_402_mamba_in_3_din;
wire    grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_48_4_fu_402_mamba_in_3_write;
reg    grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_ap_start_reg;
wire   [0:0] icmp_ln22_fu_469_p2;
wire    ap_CS_fsm_state3;
reg    grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_37_3_fu_364_ap_start_reg;
wire    ap_CS_fsm_state5;
reg    grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_48_4_fu_402_ap_start_reg;
wire    ap_CS_fsm_state36;
wire    ap_CS_fsm_state37;
reg   [4:0] t_fu_178;
wire   [4:0] add_ln22_fu_475_p2;
wire   [12:0] trunc_ln_fu_630_p4;
wire   [0:0] tmp_68_fu_644_p3;
wire  signed [13:0] sext_ln34_fu_640_p1;
wire   [13:0] zext_ln34_fu_652_p1;
wire  signed [13:0] add_ln34_fu_656_p2;
wire   [0:0] tmp_fu_622_p3;
wire   [0:0] tmp_69_fu_666_p3;
wire   [0:0] xor_ln34_fu_674_p2;
wire   [0:0] or_ln34_1_fu_680_p2;
wire   [0:0] xor_ln34_1_fu_686_p2;
wire   [0:0] xor_ln34_2_fu_692_p2;
wire   [0:0] or_ln34_fu_698_p2;
wire   [0:0] and_ln34_fu_704_p2;
wire  signed [17:0] sext_ln34_1_fu_662_p1;
wire   [12:0] trunc_ln4_fu_730_p4;
wire   [0:0] tmp_71_fu_744_p3;
wire  signed [13:0] sext_ln42_fu_740_p1;
wire   [13:0] zext_ln42_fu_752_p1;
wire  signed [13:0] add_ln42_fu_756_p2;
wire   [0:0] tmp_70_fu_722_p3;
wire   [0:0] tmp_72_fu_766_p3;
wire   [0:0] xor_ln42_fu_774_p2;
wire   [0:0] or_ln42_1_fu_780_p2;
wire   [0:0] xor_ln42_1_fu_786_p2;
wire   [0:0] xor_ln42_2_fu_792_p2;
wire   [0:0] or_ln42_fu_798_p2;
wire   [0:0] and_ln42_fu_804_p2;
wire  signed [17:0] sext_ln42_1_fu_762_p1;
wire   [17:0] var_fu_810_p3;
wire   [16:0] trunc_ln44_fu_818_p1;
wire   [16:0] sub_ln44_fu_836_p2;
wire   [18:0] tmp_17_fu_853_p1;
wire   [18:0] tmp_17_fu_853_p3;
wire   [4:0] trunc_ln44_1_fu_861_p1;
wire   [4:0] add_ln44_fu_868_p2;
wire   [41:0] zext_ln44_1_fu_865_p1;
wire   [41:0] zext_ln44_2_fu_874_p1;
wire   [41:0] shl_ln44_fu_878_p2;
wire   [40:0] lshr_ln44_1_fu_884_p4;
wire   [0:0] tmp_74_fu_898_p3;
wire   [4:0] sub_ln44_1_fu_914_p2;
wire   [7:0] select_ln44_1_fu_906_p3;
wire  signed [7:0] sext_ln44_fu_920_p1;
wire   [7:0] add_ln44_1_fu_924_p2;
wire   [63:0] zext_ln44_3_fu_894_p1;
wire   [8:0] tmp_19_fu_930_p3;
wire   [63:0] pi_assign_fu_937_p5;
wire   [31:0] LD_fu_949_p1;
wire   [31:0] bitcast_ln777_fu_953_p1;
wire   [63:0] bitcast_ln735_fu_964_p1;
wire   [10:0] tmp_22_fu_980_p3;
wire   [51:0] trunc_ln45_1_fu_992_p1;
wire   [52:0] zext_ln45_1_cast_fu_996_p3;
wire   [62:0] trunc_ln45_fu_968_p1;
wire   [11:0] add_ln45_fu_1044_p2;
wire   [0:0] icmp_ln45_1_fu_1039_p2;
wire   [10:0] trunc_ln45_4_fu_1049_p1;
wire   [10:0] sub_ln45_2_fu_1053_p2;
wire   [53:0] select_ln45_fu_1034_p3;
wire   [10:0] select_ln45_1_fu_1058_p3;
wire   [53:0] zext_ln45_2_fu_1088_p1;
wire   [53:0] ashr_ln45_fu_1092_p2;
wire   [0:0] icmp_ln45_3_fu_1075_p2;
wire   [17:0] trunc_ln45_6_fu_1098_p1;
wire   [17:0] select_ln45_6_fu_1081_p3;
wire   [17:0] trunc_ln45_5_fu_1071_p1;
wire   [17:0] select_ln45_1cast_fu_1122_p1;
wire   [0:0] icmp_ln45_5_fu_1116_p2;
wire   [17:0] shl_ln45_fu_1126_p2;
wire   [5:0] tmp_76_fu_1145_p2;
wire   [0:0] icmp_ln45_4_fu_1110_p2;
wire   [0:0] tmp_76_fu_1145_p3;
wire   [17:0] select_ln45_2_fu_1102_p3;
wire   [0:0] cond64_i_fu_1153_p3;
wire   [17:0] zext_ln45_3_fu_1168_p1;
wire   [17:0] add_ln45_2_fu_1172_p2;
wire   [0:0] tmp_78_fu_1178_p3;
wire   [0:0] icmp_ln45_2_fu_1066_p2;
wire   [0:0] xor_ln45_2_fu_1192_p2;
wire   [0:0] and_ln45_9_fu_1198_p2;
wire   [17:0] ref_tmp_i_i_fu_1212_p6;
wire   [17:0] ref_tmp_i_i_fu_1212_p7;
wire   [1:0] ref_tmp_i_i_fu_1212_p8;
wire   [0:0] tmp_77_fu_1160_p3;
wire   [0:0] and_ln45_10_fu_1232_p2;
wire   [0:0] xor_ln45_fu_1186_p2;
wire   [10:0] or_ln45_4_fu_1244_p3;
wire  signed [11:0] sext_ln45_1_fu_1252_p1;
wire   [11:0] add_ln45_3_fu_1256_p2;
wire   [8:0] tmp_79_fu_1261_p4;
wire   [11:0] add_ln45_4_fu_1277_p2;
wire   [5:0] tobool134_i_fu_1325_p2;
wire   [0:0] icmp_ln45_8_fu_1319_p2;
wire   [0:0] tobool134_i_fu_1325_p3;
wire   [11:0] add_ln45_5_fu_1286_p2;
wire   [5:0] trunc_ln45_9_fu_1351_p1;
wire   [53:0] zext_ln45_5_fu_1355_p1;
wire   [53:0] lshr_ln45_fu_1359_p2;
wire   [53:0] lshr_ln45_1_fu_1365_p2;
wire   [0:0] tmp_82_fu_1377_p3;
wire   [0:0] icmp_ln45_10_fu_1345_p2;
wire   [0:0] icmp_ln45_11_fu_1371_p2;
wire   [0:0] xor_ln45_10_fu_1385_p2;
wire   [0:0] icmp_ln45_9_fu_1339_p2;
wire   [0:0] xor_ln45_9_fu_1313_p2;
wire   [0:0] lD_0_i_fu_1333_p2;
wire   [0:0] icmp_ln45_12_fu_1417_p2;
wire   [0:0] icmp_ln45_14_fu_1435_p2;
wire   [0:0] xor_ln45_11_fu_1447_p2;
wire   [0:0] icmp_ln45_13_fu_1429_p2;
wire   [0:0] or_ln45_5_fu_1453_p2;
wire   [0:0] and_ln45_1_fu_1399_p2;
wire   [0:0] and_ln45_11_fu_1459_p2;
wire   [0:0] Range1_all_ones_2_i_fu_1473_p2;
wire   [0:0] Range1_all_ones_2_i_fu_1473_p7;
wire   [1:0] sel_tmp_fu_1465_p3;
wire   [0:0] Range1_all_zeros_2_i_fu_1493_p2;
wire   [0:0] Range1_all_zeros_2_i_fu_1493_p6;
wire   [0:0] Range1_all_zeros_2_i_fu_1493_p7;
wire   [0:0] or_ln45_1_fu_1522_p2;
wire   [0:0] and_ln45_4_fu_1526_p2;
wire   [0:0] and_ln45_5_fu_1537_p2;
wire   [0:0] cond193_i_fu_1531_p3;
wire   [0:0] not_icmp_ln45_756_fu_1547_p2;
wire   [0:0] and_ln45_12_fu_1558_p2;
wire   [0:0] neg_src_0_i_fu_1570_p2;
wire   [0:0] neg_src_0_i_fu_1570_p4;
wire   [0:0] neg_src_0_i_fu_1570_p7;
wire   [1:0] neg_src_0_i_fu_1570_p8;
wire   [0:0] select_ln45_4_fu_1517_p3;
wire   [0:0] xor_ln45_5_fu_1590_p2;
wire   [0:0] and_ln45_13_fu_1596_p2;
wire   [0:0] or_ln45_2_fu_1601_p2;
wire   [0:0] xor_ln45_6_fu_1606_p2;
wire   [0:0] deleted_ones_0_i_fu_1552_p2;
wire   [0:0] and_ln45_7_fu_1617_p2;
wire   [0:0] neg_src_0_i_fu_1570_p9;
wire   [0:0] xor_ln45_7_fu_1622_p2;
wire   [0:0] and_ln45_8_fu_1628_p2;
wire   [0:0] and_ln45_6_fu_1611_p2;
wire   [0:0] or_ln45_3_fu_1634_p2;
wire   [0:0] xor_ln45_8_fu_1648_p2;
wire   [0:0] and_ln45_14_fu_1653_p2;
wire   [0:0] and_ln45_15_fu_1659_p2;
wire   [17:0] rsqrt_fu_1671_p4;
wire   [17:0] rsqrt_fu_1671_p7;
wire   [1:0] rsqrt_fu_1671_p8;
reg   [36:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
wire    ap_ST_fsm_state34_blk;
wire    ap_ST_fsm_state35_blk;
wire    ap_ST_fsm_state36_blk;
reg    ap_ST_fsm_state37_blk;
wire   [18:0] tmp_17_fu_853_p0;
wire   [0:0] tmp_17_fu_853_p2;
wire   [0:0] tmp_76_fu_1145_p0;
wire  signed [1:0] ref_tmp_i_i_fu_1212_p1;
wire   [1:0] ref_tmp_i_i_fu_1212_p3;
wire   [1:0] ref_tmp_i_i_fu_1212_p5;
wire   [0:0] tobool134_i_fu_1325_p0;
wire  signed [1:0] Range1_all_ones_2_i_fu_1473_p1;
wire   [1:0] Range1_all_ones_2_i_fu_1473_p3;
wire   [1:0] Range1_all_ones_2_i_fu_1473_p5;
wire  signed [1:0] Range1_all_zeros_2_i_fu_1493_p1;
wire   [1:0] Range1_all_zeros_2_i_fu_1493_p3;
wire   [1:0] Range1_all_zeros_2_i_fu_1493_p5;
wire  signed [1:0] neg_src_0_i_fu_1570_p1;
wire   [1:0] neg_src_0_i_fu_1570_p3;
wire   [1:0] neg_src_0_i_fu_1570_p5;
wire  signed [1:0] rsqrt_fu_1671_p1;
wire   [1:0] rsqrt_fu_1671_p3;
wire   [1:0] rsqrt_fu_1671_p5;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 37'd1;
#0 grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_ap_start_reg = 1'b0;
#0 grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_37_3_fu_364_ap_start_reg = 1'b0;
#0 grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_48_4_fu_402_ap_start_reg = 1'b0;
#0 t_fu_178 = 5'd0;
end

unet_pvm_top_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2 grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_ap_start),
    .ap_done(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_ap_done),
    .ap_idle(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_ap_idle),
    .ap_ready(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_ap_ready),
    .t(trunc_ln22_reg_1904),
    .x_31_out(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_31_out),
    .x_31_out_ap_vld(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_31_out_ap_vld),
    .x_30_out(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_30_out),
    .x_30_out_ap_vld(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_30_out_ap_vld),
    .x_29_out(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_29_out),
    .x_29_out_ap_vld(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_29_out_ap_vld),
    .x_28_out(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_28_out),
    .x_28_out_ap_vld(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_28_out_ap_vld),
    .x_27_out(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_27_out),
    .x_27_out_ap_vld(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_27_out_ap_vld),
    .x_26_out(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_26_out),
    .x_26_out_ap_vld(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_26_out_ap_vld),
    .x_25_out(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_25_out),
    .x_25_out_ap_vld(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_25_out_ap_vld),
    .x_24_out(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_24_out),
    .x_24_out_ap_vld(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_24_out_ap_vld),
    .x_23_out(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_23_out),
    .x_23_out_ap_vld(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_23_out_ap_vld),
    .x_22_out(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_22_out),
    .x_22_out_ap_vld(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_22_out_ap_vld),
    .x_21_out(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_21_out),
    .x_21_out_ap_vld(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_21_out_ap_vld),
    .x_20_out(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_20_out),
    .x_20_out_ap_vld(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_20_out_ap_vld),
    .x_19_out(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_19_out),
    .x_19_out_ap_vld(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_19_out_ap_vld),
    .x_18_out(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_18_out),
    .x_18_out_ap_vld(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_18_out_ap_vld),
    .x_17_out(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_17_out),
    .x_17_out_ap_vld(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_17_out_ap_vld),
    .x_16_out(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_16_out),
    .x_16_out_ap_vld(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_16_out_ap_vld),
    .x_15_out(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_15_out),
    .x_15_out_ap_vld(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_15_out_ap_vld),
    .x_14_out(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_14_out),
    .x_14_out_ap_vld(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_14_out_ap_vld),
    .x_13_out(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_13_out),
    .x_13_out_ap_vld(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_13_out_ap_vld),
    .x_12_out(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_12_out),
    .x_12_out_ap_vld(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_12_out_ap_vld),
    .x_11_out(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_11_out),
    .x_11_out_ap_vld(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_11_out_ap_vld),
    .x_10_out(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_10_out),
    .x_10_out_ap_vld(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_10_out_ap_vld),
    .x_9_out(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_9_out),
    .x_9_out_ap_vld(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_9_out_ap_vld),
    .x_8_out(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_8_out),
    .x_8_out_ap_vld(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_8_out_ap_vld),
    .x_7_out(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_7_out),
    .x_7_out_ap_vld(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_7_out_ap_vld),
    .x_6_out(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_6_out),
    .x_6_out_ap_vld(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_6_out_ap_vld),
    .x_5_out(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_5_out),
    .x_5_out_ap_vld(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_5_out_ap_vld),
    .x_4_out(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_4_out),
    .x_4_out_ap_vld(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_4_out_ap_vld),
    .x_3_out(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_3_out),
    .x_3_out_ap_vld(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_3_out_ap_vld),
    .x_2_out(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_2_out),
    .x_2_out_ap_vld(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_2_out_ap_vld),
    .x_1_out(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_1_out),
    .x_1_out_ap_vld(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_1_out_ap_vld),
    .x_out(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_out),
    .x_out_ap_vld(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_out_ap_vld),
    .mean_1_out(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_mean_1_out),
    .mean_1_out_ap_vld(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_mean_1_out_ap_vld),
    .unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_address0(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_address0),
    .unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_ce0(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_ce0),
    .unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_q0(unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_q0),
    .unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_address0(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_address0),
    .unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_ce0(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_ce0),
    .unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_q0(unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_q0),
    .unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_address0(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_address0),
    .unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_ce0(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_ce0),
    .unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_q0(unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_q0),
    .unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_address0(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_address0),
    .unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_ce0(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_ce0),
    .unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_q0(unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_q0)
);

unet_pvm_top_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_37_3 grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_37_3_fu_364(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_37_3_fu_364_ap_start),
    .ap_done(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_37_3_fu_364_ap_done),
    .ap_idle(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_37_3_fu_364_ap_idle),
    .ap_ready(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_37_3_fu_364_ap_ready),
    .x_reload(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_out),
    .x_1_reload(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_1_out),
    .x_2_reload(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_2_out),
    .x_3_reload(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_3_out),
    .x_4_reload(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_4_out),
    .x_5_reload(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_5_out),
    .x_6_reload(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_6_out),
    .x_7_reload(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_7_out),
    .x_8_reload(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_8_out),
    .x_9_reload(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_9_out),
    .x_10_reload(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_10_out),
    .x_11_reload(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_11_out),
    .x_12_reload(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_12_out),
    .x_13_reload(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_13_out),
    .x_14_reload(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_14_out),
    .x_15_reload(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_15_out),
    .x_16_reload(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_16_out),
    .x_17_reload(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_17_out),
    .x_18_reload(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_18_out),
    .x_19_reload(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_19_out),
    .x_20_reload(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_20_out),
    .x_21_reload(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_21_out),
    .x_22_reload(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_22_out),
    .x_23_reload(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_23_out),
    .x_24_reload(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_24_out),
    .x_25_reload(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_25_out),
    .x_26_reload(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_26_out),
    .x_27_reload(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_27_out),
    .x_28_reload(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_28_out),
    .x_29_reload(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_29_out),
    .x_30_reload(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_30_out),
    .x_31_reload(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_31_out),
    .conv_i_i16_i691(mean_reg_2005),
    .var_1_out(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_37_3_fu_364_var_1_out),
    .var_1_out_ap_vld(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_37_3_fu_364_var_1_out_ap_vld)
);

unet_pvm_top_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_48_4 grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_48_4_fu_402(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_48_4_fu_402_ap_start),
    .ap_done(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_48_4_fu_402_ap_done),
    .ap_idle(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_48_4_fu_402_ap_idle),
    .ap_ready(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_48_4_fu_402_ap_ready),
    .mamba_in_2_din(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_48_4_fu_402_mamba_in_2_din),
    .mamba_in_2_full_n(mamba_in_2_full_n),
    .mamba_in_2_write(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_48_4_fu_402_mamba_in_2_write),
    .mamba_in_1_din(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_48_4_fu_402_mamba_in_1_din),
    .mamba_in_1_full_n(mamba_in_1_full_n),
    .mamba_in_1_write(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_48_4_fu_402_mamba_in_1_write),
    .mamba_in_0_din(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_48_4_fu_402_mamba_in_0_din),
    .mamba_in_0_full_n(mamba_in_0_full_n),
    .mamba_in_0_write(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_48_4_fu_402_mamba_in_0_write),
    .mamba_in_3_din(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_48_4_fu_402_mamba_in_3_din),
    .mamba_in_3_full_n(mamba_in_3_full_n),
    .mamba_in_3_write(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_48_4_fu_402_mamba_in_3_write),
    .x_reload(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_out),
    .x_8_reload(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_8_out),
    .x_16_reload(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_16_out),
    .x_24_reload(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_24_out),
    .conv_i_i16_i691(mean_reg_2005),
    .conv7_i(rsqrt_reg_2150),
    .x_1_reload(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_1_out),
    .x_9_reload(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_9_out),
    .x_17_reload(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_17_out),
    .x_25_reload(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_25_out),
    .x_2_reload(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_2_out),
    .x_10_reload(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_10_out),
    .x_18_reload(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_18_out),
    .x_26_reload(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_26_out),
    .x_3_reload(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_3_out),
    .x_11_reload(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_11_out),
    .x_19_reload(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_19_out),
    .x_27_reload(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_27_out),
    .x_4_reload(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_4_out),
    .x_12_reload(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_12_out),
    .x_20_reload(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_20_out),
    .x_28_reload(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_28_out),
    .x_5_reload(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_5_out),
    .x_13_reload(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_13_out),
    .x_21_reload(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_21_out),
    .x_29_reload(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_29_out),
    .x_6_reload(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_6_out),
    .x_14_reload(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_14_out),
    .x_22_reload(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_22_out),
    .x_30_reload(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_30_out),
    .x_7_reload(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_7_out),
    .x_15_reload(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_15_out),
    .x_23_reload(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_23_out),
    .x_31_reload(grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_x_31_out)
);

unet_pvm_top_ctlz_19_19_1_1 #(
    .din_WIDTH( 19 ),
    .dout_WIDTH( 19 ))
ctlz_19_19_1_1_U143(
    .din(tmp_17_fu_853_p1),
    .dout(tmp_17_fu_853_p3)
);

unet_pvm_top_bitselect_1ns_54ns_6ns_1_1_1 #(
    .DATAWIDTH( 54 ),
    .ADDRWIDTH( 6 ))
bitselect_1ns_54ns_6ns_1_1_1_U144(
    .din(select_ln45_fu_1034_p3),
    .sel(tmp_76_fu_1145_p2),
    .dout(tmp_76_fu_1145_p3)
);

(* dissolve_hierarchy = "yes" *) unet_pvm_top_sparsemux_7_2_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 18 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 18 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 18 ),
    .def_WIDTH( 18 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 18 ))
sparsemux_7_2_18_1_1_U145(
    .din0(trunc_ln45_5_fu_1071_p1),
    .din1(add_ln45_2_fu_1172_p2),
    .din2(ref_tmp_i_i_fu_1212_p6),
    .def(ref_tmp_i_i_fu_1212_p7),
    .sel(ref_tmp_i_i_fu_1212_p8),
    .dout(ref_tmp_i_i_fu_1212_p9)
);

unet_pvm_top_bitselect_1ns_54ns_6ns_1_1_1 #(
    .DATAWIDTH( 54 ),
    .ADDRWIDTH( 6 ))
bitselect_1ns_54ns_6ns_1_1_1_U146(
    .din(select_ln45_fu_1034_p3),
    .sel(tobool134_i_fu_1325_p2),
    .dout(tobool134_i_fu_1325_p3)
);

(* dissolve_hierarchy = "yes" *) unet_pvm_top_sparsemux_7_2_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 1 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 1 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 1 ),
    .def_WIDTH( 1 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 1 ))
sparsemux_7_2_1_1_1_U147(
    .din0(Range1_all_ones_2_i_fu_1473_p2),
    .din1(lD_0_i_fu_1333_p2),
    .din2(xor_ln45_9_fu_1313_p2),
    .def(Range1_all_ones_2_i_fu_1473_p7),
    .sel(sel_tmp_fu_1465_p3),
    .dout(Range1_all_ones_2_i_fu_1473_p9)
);

(* dissolve_hierarchy = "yes" *) unet_pvm_top_sparsemux_7_2_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 1 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 1 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 1 ),
    .def_WIDTH( 1 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 1 ))
sparsemux_7_2_1_1_1_U148(
    .din0(Range1_all_zeros_2_i_fu_1493_p2),
    .din1(xor_ln45_1_fu_1411_p2),
    .din2(Range1_all_zeros_2_i_fu_1493_p6),
    .def(Range1_all_zeros_2_i_fu_1493_p7),
    .sel(sel_tmp_fu_1465_p3),
    .dout(Range1_all_zeros_2_i_fu_1493_p9)
);

(* dissolve_hierarchy = "yes" *) unet_pvm_top_sparsemux_7_2_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 1 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 1 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 1 ),
    .def_WIDTH( 1 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 1 ))
sparsemux_7_2_1_1_1_U149(
    .din0(neg_src_0_i_fu_1570_p2),
    .din1(neg_src_0_i_fu_1570_p4),
    .din2(1'd0),
    .def(neg_src_0_i_fu_1570_p7),
    .sel(neg_src_0_i_fu_1570_p8),
    .dout(neg_src_0_i_fu_1570_p9)
);

(* dissolve_hierarchy = "yes" *) unet_pvm_top_sparsemux_7_2_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 18 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 18 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 18 ),
    .def_WIDTH( 18 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 18 ))
sparsemux_7_2_18_1_1_U150(
    .din0(18'd0),
    .din1(rsqrt_fu_1671_p4),
    .din2(ref_tmp_i_i_reg_2092),
    .def(rsqrt_fu_1671_p7),
    .sel(rsqrt_fu_1671_p8),
    .dout(rsqrt_fu_1671_p9)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln22_fu_469_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_ap_start_reg <= 1'b1;
        end else if ((grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_ap_ready == 1'b1)) begin
            grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_37_3_fu_364_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_37_3_fu_364_ap_start_reg <= 1'b1;
        end else if ((grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_37_3_fu_364_ap_ready == 1'b1)) begin
            grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_37_3_fu_364_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_48_4_fu_402_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state36)) begin
            grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_48_4_fu_402_ap_start_reg <= 1'b1;
        end else if ((grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_48_4_fu_402_ap_ready == 1'b1)) begin
            grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_48_4_fu_402_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        t_fu_178 <= 5'd0;
    end else if (((icmp_ln22_fu_469_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        t_fu_178 <= add_ln22_fu_475_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state34)) begin
        Range1_all_ones_2_i_reg_2138 <= Range1_all_ones_2_i_fu_1473_p9;
        Range1_all_zeros_2_i_reg_2145 <= Range1_all_zeros_2_i_fu_1493_p9;
        Range2_all_ones_1_i_reg_2128 <= Range2_all_ones_1_i_fu_1391_p3;
        carry_1_i_reg_2097 <= carry_1_i_fu_1238_p2;
        icmp_ln45_6_reg_2104 <= icmp_ln45_6_fu_1271_p2;
        icmp_ln45_7_reg_2116 <= icmp_ln45_7_fu_1299_p2;
        ref_tmp_i_i_reg_2092 <= ref_tmp_i_i_fu_1212_p9;
        tmp_80_reg_2109 <= ref_tmp_i_i_fu_1212_p9[32'd17];
        tmp_81_reg_2123 <= add_ln45_4_fu_1277_p2[32'd11];
        xor_ln45_1_reg_2133 <= xor_ln45_1_fu_1411_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state31)) begin
        div_reg_2037 <= grp_fu_356_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        icmp_ln44_reg_2011 <= icmp_ln44_fu_822_p2;
        select_ln44_reg_2021 <= select_ln44_fu_842_p3;
        tmp_73_reg_2016 <= var_fu_810_p3[32'd17];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state33)) begin
        icmp_ln45_reg_2067 <= icmp_ln45_fu_1014_p2;
        sub_ln45_1_reg_2073 <= sub_ln45_1_fu_1020_p2;
        sub_ln45_reg_2062 <= sub_ln45_fu_1008_p2;
        tmp_75_reg_2042 <= bitcast_ln735_fu_964_p1[32'd63];
        trunc_ln45_2_reg_2082 <= trunc_ln45_2_fu_1026_p1;
        trunc_ln45_3_reg_2087 <= trunc_ln45_3_fu_1030_p1;
        zext_ln45_1_reg_2057[51 : 0] <= zext_ln45_1_fu_1004_p1[51 : 0];
        zext_ln45_reg_2052[10 : 0] <= zext_ln45_fu_988_p1[10 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        mean_reg_2005 <= mean_fu_710_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state35)) begin
        rsqrt_reg_2150 <= rsqrt_fu_1671_p9;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        temp_var_reg_2027 <= temp_var_fu_957_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        tmp_20_reg_2032 <= grp_fu_363_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        trunc_ln22_reg_1904 <= trunc_ln22_fu_481_p1;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

assign ap_ST_fsm_state34_blk = 1'b0;

assign ap_ST_fsm_state35_blk = 1'b0;

assign ap_ST_fsm_state36_blk = 1'b0;

always @ (*) begin
    if ((grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_48_4_fu_402_ap_done == 1'b0)) begin
        ap_ST_fsm_state37_blk = 1'b1;
    end else begin
        ap_ST_fsm_state37_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_37_3_fu_364_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((icmp_ln22_fu_469_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln22_fu_469_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln22_fu_469_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_37_3_fu_364_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            if (((grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_48_4_fu_402_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state37))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state37;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign LD_fu_949_p1 = pi_assign_fu_937_p5[31:0];

assign Range1_all_ones_2_i_fu_1473_p2 = (lD_0_i_fu_1333_p2 & Range2_all_ones_1_i_fu_1391_p3);

assign Range1_all_ones_2_i_fu_1473_p7 = 'bx;

assign Range1_all_zeros_2_i_fu_1493_p2 = (xor_ln45_1_fu_1411_p2 & icmp_ln45_12_fu_1417_p2);

assign Range1_all_zeros_2_i_fu_1493_p6 = (xor_ln45_9_fu_1313_p2 | icmp_ln45_14_fu_1435_p2);

assign Range1_all_zeros_2_i_fu_1493_p7 = 'bx;

assign Range2_all_ones_1_i_fu_1391_p3 = ((icmp_ln45_10_fu_1345_p2[0:0] == 1'b1) ? icmp_ln45_11_fu_1371_p2 : xor_ln45_10_fu_1385_p2);

assign add_ln22_fu_475_p2 = (t_fu_178 + 5'd1);

assign add_ln34_fu_656_p2 = ($signed(sext_ln34_fu_640_p1) + $signed(zext_ln34_fu_652_p1));

assign add_ln42_fu_756_p2 = ($signed(sext_ln42_fu_740_p1) + $signed(zext_ln42_fu_752_p1));

assign add_ln44_1_fu_924_p2 = ($signed(select_ln44_1_fu_906_p3) + $signed(sext_ln44_fu_920_p1));

assign add_ln44_fu_868_p2 = (trunc_ln44_1_fu_861_p1 + 5'd6);

assign add_ln45_2_fu_1172_p2 = (select_ln45_2_fu_1102_p3 + zext_ln45_3_fu_1168_p1);

assign add_ln45_3_fu_1256_p2 = ($signed(sext_ln45_1_fu_1252_p1) + $signed(zext_ln45_reg_2052));

assign add_ln45_4_fu_1277_p2 = (sub_ln45_1_reg_2073 + 12'd8);

assign add_ln45_5_fu_1286_p2 = (sub_ln45_1_reg_2073 + 12'd9);

assign add_ln45_fu_1044_p2 = ($signed(sub_ln45_1_reg_2073) + $signed(12'd4086));

assign and_ln34_fu_704_p2 = (xor_ln34_fu_674_p2 & or_ln34_fu_698_p2);

assign and_ln42_fu_804_p2 = (xor_ln42_fu_774_p2 & or_ln42_fu_798_p2);

assign and_ln45_10_fu_1232_p2 = (tmp_77_fu_1160_p3 & and_ln45_9_fu_1198_p2);

assign and_ln45_11_fu_1459_p2 = (or_ln45_5_fu_1453_p2 & icmp_ln45_13_fu_1429_p2);

assign and_ln45_12_fu_1558_p2 = (tmp_75_reg_2042 & icmp_ln45_7_reg_2116);

assign and_ln45_13_fu_1596_p2 = (xor_ln45_5_fu_1590_p2 & icmp_ln45_7_reg_2116);

assign and_ln45_14_fu_1653_p2 = (xor_ln45_8_fu_1648_p2 & or_ln45_3_fu_1634_p2);

assign and_ln45_15_fu_1659_p2 = (icmp_ln45_6_reg_2104 & and_ln45_14_fu_1653_p2);

assign and_ln45_1_fu_1399_p2 = (xor_ln45_9_fu_1313_p2 & icmp_ln45_9_fu_1339_p2);

assign and_ln45_4_fu_1526_p2 = (or_ln45_1_fu_1522_p2 & Range2_all_ones_1_i_reg_2128);

assign and_ln45_5_fu_1537_p2 = (carry_1_i_reg_2097 & Range1_all_ones_2_i_reg_2138);

assign and_ln45_6_fu_1611_p2 = (xor_ln45_6_fu_1606_p2 & or_ln45_2_fu_1601_p2);

assign and_ln45_7_fu_1617_p2 = (tmp_80_reg_2109 & deleted_ones_0_i_fu_1552_p2);

assign and_ln45_8_fu_1628_p2 = (xor_ln45_7_fu_1622_p2 & neg_src_0_i_fu_1570_p9);

assign and_ln45_9_fu_1198_p2 = (xor_ln45_2_fu_1192_p2 & icmp_ln45_1_fu_1039_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state31 = ap_CS_fsm[32'd30];

assign ap_CS_fsm_state33 = ap_CS_fsm[32'd32];

assign ap_CS_fsm_state34 = ap_CS_fsm[32'd33];

assign ap_CS_fsm_state35 = ap_CS_fsm[32'd34];

assign ap_CS_fsm_state36 = ap_CS_fsm[32'd35];

assign ap_CS_fsm_state37 = ap_CS_fsm[32'd36];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ashr_ln45_fu_1092_p2 = $signed(select_ln45_fu_1034_p3) >>> zext_ln45_2_fu_1088_p1;

assign bitcast_ln735_fu_964_p1 = grp_fu_360_p_dout0;

assign bitcast_ln777_fu_953_p1 = LD_fu_949_p1;

assign carry_1_i_fu_1238_p2 = (xor_ln45_fu_1186_p2 & and_ln45_10_fu_1232_p2);

assign cond193_i_fu_1531_p3 = ((carry_1_i_reg_2097[0:0] == 1'b1) ? and_ln45_4_fu_1526_p2 : Range1_all_ones_2_i_reg_2138);

assign cond64_i_fu_1153_p3 = ((icmp_ln45_4_fu_1110_p2[0:0] == 1'b1) ? tmp_75_reg_2042 : tmp_76_fu_1145_p3);

assign deleted_ones_0_i_fu_1552_p2 = (not_icmp_ln45_756_fu_1547_p2 | cond193_i_fu_1531_p3);

assign grp_fu_356_p_ce = 1'b1;

assign grp_fu_356_p_din0 = 32'd1065353216;

assign grp_fu_356_p_din1 = tmp_20_reg_2032;

assign grp_fu_360_p_ce = 1'b1;

assign grp_fu_360_p_din0 = div_reg_2037;

assign grp_fu_363_p_ce = 1'b1;

assign grp_fu_363_p_din0 = 32'd0;

assign grp_fu_363_p_din1 = temp_var_reg_2027;

assign grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_ap_start = grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_ap_start_reg;

assign grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_37_3_fu_364_ap_start = grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_37_3_fu_364_ap_start_reg;

assign grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_48_4_fu_402_ap_start = grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_48_4_fu_402_ap_start_reg;

assign icmp_ln22_fu_469_p2 = ((t_fu_178 == 5'd16) ? 1'b1 : 1'b0);

assign icmp_ln44_fu_822_p2 = ((var_fu_810_p3 == 18'd0) ? 1'b1 : 1'b0);

assign icmp_ln45_10_fu_1345_p2 = ((add_ln45_5_fu_1286_p2 < 12'd54) ? 1'b1 : 1'b0);

assign icmp_ln45_11_fu_1371_p2 = ((lshr_ln45_fu_1359_p2 == lshr_ln45_1_fu_1365_p2) ? 1'b1 : 1'b0);

assign icmp_ln45_12_fu_1417_p2 = ((lshr_ln45_fu_1359_p2 == 54'd0) ? 1'b1 : 1'b0);

assign icmp_ln45_13_fu_1429_p2 = ((add_ln45_5_fu_1286_p2 == 12'd54) ? 1'b1 : 1'b0);

assign icmp_ln45_14_fu_1435_p2 = ((select_ln45_fu_1034_p3 == 54'd0) ? 1'b1 : 1'b0);

assign icmp_ln45_1_fu_1039_p2 = (($signed(sub_ln45_1_reg_2073) > $signed(12'd10)) ? 1'b1 : 1'b0);

assign icmp_ln45_2_fu_1066_p2 = ((sub_ln45_1_reg_2073 == 12'd10) ? 1'b1 : 1'b0);

assign icmp_ln45_3_fu_1075_p2 = ((select_ln45_1_fu_1058_p3 < 11'd54) ? 1'b1 : 1'b0);

assign icmp_ln45_4_fu_1110_p2 = (($signed(add_ln45_fu_1044_p2) > $signed(12'd54)) ? 1'b1 : 1'b0);

assign icmp_ln45_5_fu_1116_p2 = ((select_ln45_1_fu_1058_p3 < 11'd18) ? 1'b1 : 1'b0);

assign icmp_ln45_6_fu_1271_p2 = (($signed(tmp_79_fu_1261_p4) > $signed(9'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_7_fu_1299_p2 = (($signed(add_ln45_4_fu_1277_p2) < $signed(12'd54)) ? 1'b1 : 1'b0);

assign icmp_ln45_8_fu_1319_p2 = ((add_ln45_4_fu_1277_p2 < 12'd54) ? 1'b1 : 1'b0);

assign icmp_ln45_9_fu_1339_p2 = (($signed(add_ln45_5_fu_1286_p2) < $signed(12'd54)) ? 1'b1 : 1'b0);

assign icmp_ln45_fu_1014_p2 = ((trunc_ln45_fu_968_p1 == 63'd0) ? 1'b1 : 1'b0);

assign lD_0_i_fu_1333_p2 = (tobool134_i_fu_1325_p3 & icmp_ln45_8_fu_1319_p2);

assign lshr_ln44_1_fu_884_p4 = {{shl_ln44_fu_878_p2[41:1]}};

assign lshr_ln45_1_fu_1365_p2 = 54'd18014398509481983 >> zext_ln45_5_fu_1355_p1;

assign lshr_ln45_fu_1359_p2 = select_ln45_fu_1034_p3 >> zext_ln45_5_fu_1355_p1;

assign mamba_in_0_din = grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_48_4_fu_402_mamba_in_0_din;

assign mamba_in_0_write = grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_48_4_fu_402_mamba_in_0_write;

assign mamba_in_1_din = grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_48_4_fu_402_mamba_in_1_din;

assign mamba_in_1_write = grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_48_4_fu_402_mamba_in_1_write;

assign mamba_in_2_din = grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_48_4_fu_402_mamba_in_2_din;

assign mamba_in_2_write = grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_48_4_fu_402_mamba_in_2_write;

assign mamba_in_3_din = grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_48_4_fu_402_mamba_in_3_din;

assign mamba_in_3_write = grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_48_4_fu_402_mamba_in_3_write;

assign mean_fu_710_p3 = ((and_ln34_fu_704_p2[0:0] == 1'b1) ? 18'd131071 : sext_ln34_1_fu_662_p1);

assign neg_src_0_i_fu_1570_p2 = (tmp_80_reg_2109 & tmp_75_reg_2042);

assign neg_src_0_i_fu_1570_p4 = (1'd1 ^ and_ln45_5_fu_1537_p2);

assign neg_src_0_i_fu_1570_p7 = 'bx;

assign neg_src_0_i_fu_1570_p8 = {{not_icmp_ln45_756_fu_1547_p2}, {and_ln45_12_fu_1558_p2}};

assign not_icmp_ln45_756_fu_1547_p2 = (icmp_ln45_7_reg_2116 ^ 1'd1);

assign or_ln34_1_fu_680_p2 = (xor_ln34_fu_674_p2 | tmp_69_fu_666_p3);

assign or_ln34_fu_698_p2 = (xor_ln34_2_fu_692_p2 | tmp_69_fu_666_p3);

assign or_ln42_1_fu_780_p2 = (xor_ln42_fu_774_p2 | tmp_72_fu_766_p3);

assign or_ln42_fu_798_p2 = (xor_ln42_2_fu_792_p2 | tmp_72_fu_766_p3);

assign or_ln45_1_fu_1522_p2 = (xor_ln45_1_reg_2133 | tmp_81_reg_2123);

assign or_ln45_2_fu_1601_p2 = (tmp_80_reg_2109 | and_ln45_13_fu_1596_p2);

assign or_ln45_3_fu_1634_p2 = (and_ln45_8_fu_1628_p2 | and_ln45_6_fu_1611_p2);

assign or_ln45_4_fu_1244_p3 = {{10'd513}, {icmp_ln45_1_fu_1039_p2}};

assign or_ln45_5_fu_1453_p2 = (xor_ln45_11_fu_1447_p2 | tmp_81_fu_1305_p3);

assign pi_assign_fu_937_p5 = {{zext_ln44_3_fu_894_p1[63:32]}, {tmp_19_fu_930_p3}, {zext_ln44_3_fu_894_p1[22:0]}};

assign ref_tmp_i_i_fu_1212_p6 = ((icmp_ln45_5_fu_1116_p2[0:0] == 1'b1) ? shl_ln45_fu_1126_p2 : 18'd0);

assign ref_tmp_i_i_fu_1212_p7 = 'bx;

assign ref_tmp_i_i_fu_1212_p8 = {{icmp_ln45_2_fu_1066_p2}, {and_ln45_9_fu_1198_p2}};

assign rsqrt_fu_1671_p4 = ((and_ln45_6_fu_1611_p2[0:0] == 1'b1) ? 18'd131071 : 18'd131072);

assign rsqrt_fu_1671_p7 = 'bx;

assign rsqrt_fu_1671_p8 = {{icmp_ln45_reg_2067}, {and_ln45_15_fu_1659_p2}};

assign sel_tmp_fu_1465_p3 = {{and_ln45_1_fu_1399_p2}, {and_ln45_11_fu_1459_p2}};

assign select_ln44_1_fu_906_p3 = ((tmp_74_fu_898_p3[0:0] == 1'b1) ? 8'd127 : 8'd126);

assign select_ln44_fu_842_p3 = ((tmp_73_fu_828_p3[0:0] == 1'b1) ? sub_ln44_fu_836_p2 : trunc_ln44_fu_818_p1);

assign select_ln45_1_fu_1058_p3 = ((icmp_ln45_1_fu_1039_p2[0:0] == 1'b1) ? trunc_ln45_4_fu_1049_p1 : sub_ln45_2_fu_1053_p2);

assign select_ln45_1cast_fu_1122_p1 = select_ln45_1_fu_1058_p3;

assign select_ln45_2_fu_1102_p3 = ((icmp_ln45_3_fu_1075_p2[0:0] == 1'b1) ? trunc_ln45_6_fu_1098_p1 : select_ln45_6_fu_1081_p3);

assign select_ln45_4_fu_1517_p3 = ((carry_1_i_reg_2097[0:0] == 1'b1) ? Range1_all_ones_2_i_reg_2138 : Range1_all_zeros_2_i_reg_2145);

assign select_ln45_6_fu_1081_p3 = ((tmp_75_reg_2042[0:0] == 1'b1) ? 18'd262143 : 18'd0);

assign select_ln45_fu_1034_p3 = ((tmp_75_reg_2042[0:0] == 1'b1) ? sub_ln45_reg_2062 : zext_ln45_1_reg_2057);

assign sext_ln34_1_fu_662_p1 = add_ln34_fu_656_p2;

assign sext_ln34_fu_640_p1 = $signed(trunc_ln_fu_630_p4);

assign sext_ln42_1_fu_762_p1 = add_ln42_fu_756_p2;

assign sext_ln42_fu_740_p1 = $signed(trunc_ln4_fu_730_p4);

assign sext_ln44_fu_920_p1 = $signed(sub_ln44_1_fu_914_p2);

assign sext_ln45_1_fu_1252_p1 = $signed(or_ln45_4_fu_1244_p3);

assign shl_ln44_fu_878_p2 = zext_ln44_1_fu_865_p1 << zext_ln44_2_fu_874_p1;

assign shl_ln45_fu_1126_p2 = trunc_ln45_5_fu_1071_p1 << select_ln45_1cast_fu_1122_p1;

assign sub_ln44_1_fu_914_p2 = (5'd9 - trunc_ln44_1_fu_861_p1);

assign sub_ln44_fu_836_p2 = (17'd0 - trunc_ln44_fu_818_p1);

assign sub_ln45_1_fu_1020_p2 = (12'd1075 - zext_ln45_fu_988_p1);

assign sub_ln45_2_fu_1053_p2 = (11'd10 - trunc_ln45_3_reg_2087);

assign sub_ln45_fu_1008_p2 = (54'd0 - zext_ln45_1_fu_1004_p1);

assign temp_var_fu_957_p3 = ((icmp_ln44_reg_2011[0:0] == 1'b1) ? 32'd0 : bitcast_ln777_fu_953_p1);

assign tmp_17_fu_853_p1 = select_ln44_reg_2021;

assign tmp_19_fu_930_p3 = {{tmp_73_reg_2016}, {add_ln44_1_fu_924_p2}};

assign tmp_22_fu_980_p3 = {{bitcast_ln735_fu_964_p1[62:52]}};

assign tmp_68_fu_644_p3 = grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_mean_1_out[32'd4];

assign tmp_69_fu_666_p3 = add_ln34_fu_656_p2[32'd13];

assign tmp_70_fu_722_p3 = grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_37_3_fu_364_var_1_out[32'd17];

assign tmp_71_fu_744_p3 = grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_37_3_fu_364_var_1_out[32'd4];

assign tmp_72_fu_766_p3 = add_ln42_fu_756_p2[32'd13];

assign tmp_73_fu_828_p3 = var_fu_810_p3[32'd17];

assign tmp_74_fu_898_p3 = shl_ln44_fu_878_p2[32'd25];

assign tmp_76_fu_1145_p2 = ($signed(trunc_ln45_2_reg_2082) + $signed(6'd53));

assign tmp_77_fu_1160_p3 = select_ln45_2_fu_1102_p3[32'd17];

assign tmp_78_fu_1178_p3 = add_ln45_2_fu_1172_p2[32'd17];

assign tmp_79_fu_1261_p4 = {{add_ln45_3_fu_1256_p2[11:3]}};

assign tmp_81_fu_1305_p3 = add_ln45_4_fu_1277_p2[32'd11];

assign tmp_82_fu_1377_p3 = add_ln45_5_fu_1286_p2[32'd11];

assign tmp_fu_622_p3 = grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_mean_1_out[32'd17];

assign tobool134_i_fu_1325_p2 = add_ln45_4_fu_1277_p2[5:0];

assign trunc_ln22_fu_481_p1 = t_fu_178[3:0];

assign trunc_ln44_1_fu_861_p1 = tmp_17_fu_853_p3[4:0];

assign trunc_ln44_fu_818_p1 = var_fu_810_p3[16:0];

assign trunc_ln45_1_fu_992_p1 = bitcast_ln735_fu_964_p1[51:0];

assign trunc_ln45_2_fu_1026_p1 = sub_ln45_1_fu_1020_p2[5:0];

assign trunc_ln45_3_fu_1030_p1 = sub_ln45_1_fu_1020_p2[10:0];

assign trunc_ln45_4_fu_1049_p1 = add_ln45_fu_1044_p2[10:0];

assign trunc_ln45_5_fu_1071_p1 = select_ln45_fu_1034_p3[17:0];

assign trunc_ln45_6_fu_1098_p1 = ashr_ln45_fu_1092_p2[17:0];

assign trunc_ln45_9_fu_1351_p1 = add_ln45_5_fu_1286_p2[5:0];

assign trunc_ln45_fu_968_p1 = bitcast_ln735_fu_964_p1[62:0];

assign trunc_ln4_fu_730_p4 = {{grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_37_3_fu_364_var_1_out[17:5]}};

assign trunc_ln_fu_630_p4 = {{grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_mean_1_out[17:5]}};

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_address0 = grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_address0;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_ce0 = grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_ce0;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_address0 = grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_address0;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_ce0 = grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_ce0;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_address0 = grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_address0;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_ce0 = grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_ce0;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_address0 = grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_address0;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_ce0 = grp_pvm_split_and_norm_config_enc5_Pipeline_VITIS_LOOP_29_2_fu_318_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_ce0;

assign var_fu_810_p3 = ((and_ln42_fu_804_p2[0:0] == 1'b1) ? 18'd131071 : sext_ln42_1_fu_762_p1);

assign xor_ln34_1_fu_686_p2 = (tmp_fu_622_p3 ^ or_ln34_1_fu_680_p2);

assign xor_ln34_2_fu_692_p2 = (xor_ln34_1_fu_686_p2 ^ 1'd1);

assign xor_ln34_fu_674_p2 = (tmp_fu_622_p3 ^ 1'd1);

assign xor_ln42_1_fu_786_p2 = (tmp_70_fu_722_p3 ^ or_ln42_1_fu_780_p2);

assign xor_ln42_2_fu_792_p2 = (xor_ln42_1_fu_786_p2 ^ 1'd1);

assign xor_ln42_fu_774_p2 = (tmp_70_fu_722_p3 ^ 1'd1);

assign xor_ln45_10_fu_1385_p2 = (tmp_82_fu_1377_p3 ^ 1'd1);

assign xor_ln45_11_fu_1447_p2 = (icmp_ln45_9_fu_1339_p2 ^ 1'd1);

assign xor_ln45_1_fu_1411_p2 = (lD_0_i_fu_1333_p2 ^ 1'd1);

assign xor_ln45_2_fu_1192_p2 = (icmp_ln45_2_fu_1066_p2 ^ 1'd1);

assign xor_ln45_5_fu_1590_p2 = (select_ln45_4_fu_1517_p3 ^ 1'd1);

assign xor_ln45_6_fu_1606_p2 = (tmp_75_reg_2042 ^ 1'd1);

assign xor_ln45_7_fu_1622_p2 = (1'd1 ^ and_ln45_7_fu_1617_p2);

assign xor_ln45_8_fu_1648_p2 = (icmp_ln45_reg_2067 ^ 1'd1);

assign xor_ln45_9_fu_1313_p2 = (tmp_81_fu_1305_p3 ^ 1'd1);

assign xor_ln45_fu_1186_p2 = (tmp_78_fu_1178_p3 ^ 1'd1);

assign zext_ln34_fu_652_p1 = tmp_68_fu_644_p3;

assign zext_ln42_fu_752_p1 = tmp_71_fu_744_p3;

assign zext_ln44_1_fu_865_p1 = select_ln44_reg_2021;

assign zext_ln44_2_fu_874_p1 = add_ln44_fu_868_p2;

assign zext_ln44_3_fu_894_p1 = lshr_ln44_1_fu_884_p4;

assign zext_ln45_1_cast_fu_996_p3 = {{1'd1}, {trunc_ln45_1_fu_992_p1}};

assign zext_ln45_1_fu_1004_p1 = zext_ln45_1_cast_fu_996_p3;

assign zext_ln45_2_fu_1088_p1 = select_ln45_1_fu_1058_p3;

assign zext_ln45_3_fu_1168_p1 = cond64_i_fu_1153_p3;

assign zext_ln45_5_fu_1355_p1 = trunc_ln45_9_fu_1351_p1;

assign zext_ln45_fu_988_p1 = tmp_22_fu_980_p3;

always @ (posedge ap_clk) begin
    zext_ln45_reg_2052[11] <= 1'b0;
    zext_ln45_1_reg_2057[53:52] <= 2'b01;
end

endmodule //unet_pvm_top_pvm_split_and_norm_config_enc5_s
