// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module unet_pvm_top_custom_pvm_layer_config_enc5_s (
        m_axi_gmem2_0_AWVALID,
        m_axi_gmem2_0_AWREADY,
        m_axi_gmem2_0_AWADDR,
        m_axi_gmem2_0_AWID,
        m_axi_gmem2_0_AWLEN,
        m_axi_gmem2_0_AWSIZE,
        m_axi_gmem2_0_AWBURST,
        m_axi_gmem2_0_AWLOCK,
        m_axi_gmem2_0_AWCACHE,
        m_axi_gmem2_0_AWPROT,
        m_axi_gmem2_0_AWQOS,
        m_axi_gmem2_0_AWREGION,
        m_axi_gmem2_0_AWUSER,
        m_axi_gmem2_0_WVALID,
        m_axi_gmem2_0_WREADY,
        m_axi_gmem2_0_WDATA,
        m_axi_gmem2_0_WSTRB,
        m_axi_gmem2_0_WLAST,
        m_axi_gmem2_0_WID,
        m_axi_gmem2_0_WUSER,
        m_axi_gmem2_0_ARVALID,
        m_axi_gmem2_0_ARREADY,
        m_axi_gmem2_0_ARADDR,
        m_axi_gmem2_0_ARID,
        m_axi_gmem2_0_ARLEN,
        m_axi_gmem2_0_ARSIZE,
        m_axi_gmem2_0_ARBURST,
        m_axi_gmem2_0_ARLOCK,
        m_axi_gmem2_0_ARCACHE,
        m_axi_gmem2_0_ARPROT,
        m_axi_gmem2_0_ARQOS,
        m_axi_gmem2_0_ARREGION,
        m_axi_gmem2_0_ARUSER,
        m_axi_gmem2_0_RVALID,
        m_axi_gmem2_0_RREADY,
        m_axi_gmem2_0_RDATA,
        m_axi_gmem2_0_RLAST,
        m_axi_gmem2_0_RID,
        m_axi_gmem2_0_RFIFONUM,
        m_axi_gmem2_0_RUSER,
        m_axi_gmem2_0_RRESP,
        m_axi_gmem2_0_BVALID,
        m_axi_gmem2_0_BREADY,
        m_axi_gmem2_0_BRESP,
        m_axi_gmem2_0_BID,
        m_axi_gmem2_0_BUSER,
        proj_weights,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_address0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_ce0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_d0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_q0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_we0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_address1,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_ce1,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_d1,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_q1,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_we1,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_address0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_ce0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_d0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_q0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_we0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_address1,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_ce1,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_d1,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_q1,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_we1,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_address0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_ce0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_d0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_q0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_we0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_address1,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_ce1,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_d1,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_q1,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_we1,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_address0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_ce0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_d0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_q0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_we0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_address1,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_ce1,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_d1,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_q1,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_we1,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_address0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_ce0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_d0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_q0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_we0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_address1,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_ce1,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_d1,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_q1,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_we1,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_address0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_ce0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_d0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_q0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_we0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_address1,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_ce1,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_d1,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_q1,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_we1,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_address0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_ce0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_d0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_q0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_we0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_address1,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_ce1,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_d1,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_q1,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_we1,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_address0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_ce0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_d0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_q0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_we0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_address1,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_ce1,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_d1,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_q1,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_we1,
        ap_clk,
        ap_rst,
        proj_weights_ap_vld,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


output   m_axi_gmem2_0_AWVALID;
input   m_axi_gmem2_0_AWREADY;
output  [63:0] m_axi_gmem2_0_AWADDR;
output  [0:0] m_axi_gmem2_0_AWID;
output  [31:0] m_axi_gmem2_0_AWLEN;
output  [2:0] m_axi_gmem2_0_AWSIZE;
output  [1:0] m_axi_gmem2_0_AWBURST;
output  [1:0] m_axi_gmem2_0_AWLOCK;
output  [3:0] m_axi_gmem2_0_AWCACHE;
output  [2:0] m_axi_gmem2_0_AWPROT;
output  [3:0] m_axi_gmem2_0_AWQOS;
output  [3:0] m_axi_gmem2_0_AWREGION;
output  [0:0] m_axi_gmem2_0_AWUSER;
output   m_axi_gmem2_0_WVALID;
input   m_axi_gmem2_0_WREADY;
output  [31:0] m_axi_gmem2_0_WDATA;
output  [3:0] m_axi_gmem2_0_WSTRB;
output   m_axi_gmem2_0_WLAST;
output  [0:0] m_axi_gmem2_0_WID;
output  [0:0] m_axi_gmem2_0_WUSER;
output   m_axi_gmem2_0_ARVALID;
input   m_axi_gmem2_0_ARREADY;
output  [63:0] m_axi_gmem2_0_ARADDR;
output  [0:0] m_axi_gmem2_0_ARID;
output  [31:0] m_axi_gmem2_0_ARLEN;
output  [2:0] m_axi_gmem2_0_ARSIZE;
output  [1:0] m_axi_gmem2_0_ARBURST;
output  [1:0] m_axi_gmem2_0_ARLOCK;
output  [3:0] m_axi_gmem2_0_ARCACHE;
output  [2:0] m_axi_gmem2_0_ARPROT;
output  [3:0] m_axi_gmem2_0_ARQOS;
output  [3:0] m_axi_gmem2_0_ARREGION;
output  [0:0] m_axi_gmem2_0_ARUSER;
input   m_axi_gmem2_0_RVALID;
output   m_axi_gmem2_0_RREADY;
input  [31:0] m_axi_gmem2_0_RDATA;
input   m_axi_gmem2_0_RLAST;
input  [0:0] m_axi_gmem2_0_RID;
input  [8:0] m_axi_gmem2_0_RFIFONUM;
input  [0:0] m_axi_gmem2_0_RUSER;
input  [1:0] m_axi_gmem2_0_RRESP;
input   m_axi_gmem2_0_BVALID;
output   m_axi_gmem2_0_BREADY;
input  [1:0] m_axi_gmem2_0_BRESP;
input  [0:0] m_axi_gmem2_0_BID;
input  [0:0] m_axi_gmem2_0_BUSER;
input  [63:0] proj_weights;
output  [6:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_address0;
output   unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_ce0;
output  [17:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_d0;
input  [17:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_q0;
output   unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_we0;
output  [6:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_address1;
output   unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_ce1;
output  [17:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_d1;
input  [17:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_q1;
output   unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_we1;
output  [6:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_address0;
output   unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_ce0;
output  [17:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_d0;
input  [17:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_q0;
output   unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_we0;
output  [6:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_address1;
output   unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_ce1;
output  [17:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_d1;
input  [17:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_q1;
output   unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_we1;
output  [6:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_address0;
output   unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_ce0;
output  [17:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_d0;
input  [17:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_q0;
output   unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_we0;
output  [6:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_address1;
output   unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_ce1;
output  [17:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_d1;
input  [17:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_q1;
output   unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_we1;
output  [6:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_address0;
output   unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_ce0;
output  [17:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_d0;
input  [17:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_q0;
output   unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_we0;
output  [6:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_address1;
output   unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_ce1;
output  [17:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_d1;
input  [17:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_q1;
output   unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_we1;
output  [7:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_address0;
output   unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_ce0;
output  [17:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_d0;
input  [17:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_q0;
output   unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_we0;
output  [7:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_address1;
output   unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_ce1;
output  [17:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_d1;
input  [17:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_q1;
output   unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_we1;
output  [7:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_address0;
output   unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_ce0;
output  [17:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_d0;
input  [17:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_q0;
output   unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_we0;
output  [7:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_address1;
output   unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_ce1;
output  [17:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_d1;
input  [17:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_q1;
output   unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_we1;
output  [7:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_address0;
output   unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_ce0;
output  [17:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_d0;
input  [17:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_q0;
output   unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_we0;
output  [7:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_address1;
output   unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_ce1;
output  [17:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_d1;
input  [17:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_q1;
output   unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_we1;
output  [7:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_address0;
output   unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_ce0;
output  [17:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_d0;
input  [17:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_q0;
output   unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_we0;
output  [7:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_address1;
output   unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_ce1;
output  [17:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_d1;
input  [17:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_q1;
output   unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_we1;
input   ap_clk;
input   ap_rst;
input   proj_weights_ap_vld;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire    custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_ap_start;
wire    custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_ap_done;
wire    custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_ap_continue;
wire    custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_ap_idle;
wire    custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_ap_ready;
wire    custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_AWVALID;
wire   [63:0] custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_AWADDR;
wire   [0:0] custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_AWID;
wire   [31:0] custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_AWLEN;
wire   [2:0] custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_AWSIZE;
wire   [1:0] custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_AWBURST;
wire   [1:0] custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_AWLOCK;
wire   [3:0] custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_AWCACHE;
wire   [2:0] custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_AWPROT;
wire   [3:0] custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_AWQOS;
wire   [3:0] custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_AWREGION;
wire   [0:0] custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_AWUSER;
wire    custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_WVALID;
wire   [31:0] custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_WDATA;
wire   [3:0] custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_WSTRB;
wire    custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_WLAST;
wire   [0:0] custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_WID;
wire   [0:0] custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_WUSER;
wire    custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARVALID;
wire   [63:0] custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARADDR;
wire   [0:0] custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARID;
wire   [31:0] custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARLEN;
wire   [2:0] custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARSIZE;
wire   [1:0] custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARBURST;
wire   [1:0] custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARLOCK;
wire   [3:0] custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARCACHE;
wire   [2:0] custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARPROT;
wire   [3:0] custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARQOS;
wire   [3:0] custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARREGION;
wire   [0:0] custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARUSER;
wire    custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_RREADY;
wire    custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_BREADY;
wire   [6:0] custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_address0;
wire    custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_ce0;
wire   [6:0] custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_address1;
wire    custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_ce1;
wire   [6:0] custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_address0;
wire    custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_ce0;
wire   [6:0] custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_address1;
wire    custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_ce1;
wire   [6:0] custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_address0;
wire    custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_ce0;
wire   [6:0] custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_address1;
wire    custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_ce1;
wire   [6:0] custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_address0;
wire    custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_ce0;
wire   [6:0] custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_address1;
wire    custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_ce1;
wire   [7:0] custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_address0;
wire    custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_ce0;
wire    custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_we0;
wire   [17:0] custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_d0;
wire   [7:0] custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_address0;
wire    custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_ce0;
wire    custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_we0;
wire   [17:0] custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_d0;
wire   [7:0] custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_address0;
wire    custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_ce0;
wire    custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_we0;
wire   [17:0] custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_d0;
wire   [7:0] custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_address0;
wire    custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_ce0;
wire    custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_we0;
wire   [17:0] custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_d0;

unet_pvm_top_custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_ap_start),
    .ap_done(custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_ap_done),
    .ap_continue(custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_ap_continue),
    .ap_idle(custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_ap_idle),
    .ap_ready(custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_ap_ready),
    .m_axi_gmem2_0_AWVALID(custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_AWVALID),
    .m_axi_gmem2_0_AWREADY(1'b0),
    .m_axi_gmem2_0_AWADDR(custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_AWADDR),
    .m_axi_gmem2_0_AWID(custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_AWID),
    .m_axi_gmem2_0_AWLEN(custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_AWLEN),
    .m_axi_gmem2_0_AWSIZE(custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_AWSIZE),
    .m_axi_gmem2_0_AWBURST(custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_AWBURST),
    .m_axi_gmem2_0_AWLOCK(custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_AWLOCK),
    .m_axi_gmem2_0_AWCACHE(custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_AWCACHE),
    .m_axi_gmem2_0_AWPROT(custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_AWPROT),
    .m_axi_gmem2_0_AWQOS(custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_AWQOS),
    .m_axi_gmem2_0_AWREGION(custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_AWREGION),
    .m_axi_gmem2_0_AWUSER(custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_AWUSER),
    .m_axi_gmem2_0_WVALID(custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_WVALID),
    .m_axi_gmem2_0_WREADY(1'b0),
    .m_axi_gmem2_0_WDATA(custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_WDATA),
    .m_axi_gmem2_0_WSTRB(custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_WSTRB),
    .m_axi_gmem2_0_WLAST(custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_WLAST),
    .m_axi_gmem2_0_WID(custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_WID),
    .m_axi_gmem2_0_WUSER(custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_WUSER),
    .m_axi_gmem2_0_ARVALID(custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARVALID),
    .m_axi_gmem2_0_ARREADY(m_axi_gmem2_0_ARREADY),
    .m_axi_gmem2_0_ARADDR(custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARADDR),
    .m_axi_gmem2_0_ARID(custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARID),
    .m_axi_gmem2_0_ARLEN(custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARLEN),
    .m_axi_gmem2_0_ARSIZE(custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARSIZE),
    .m_axi_gmem2_0_ARBURST(custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARBURST),
    .m_axi_gmem2_0_ARLOCK(custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARLOCK),
    .m_axi_gmem2_0_ARCACHE(custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARCACHE),
    .m_axi_gmem2_0_ARPROT(custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARPROT),
    .m_axi_gmem2_0_ARQOS(custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARQOS),
    .m_axi_gmem2_0_ARREGION(custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARREGION),
    .m_axi_gmem2_0_ARUSER(custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARUSER),
    .m_axi_gmem2_0_RVALID(m_axi_gmem2_0_RVALID),
    .m_axi_gmem2_0_RREADY(custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_RREADY),
    .m_axi_gmem2_0_RDATA(m_axi_gmem2_0_RDATA),
    .m_axi_gmem2_0_RLAST(m_axi_gmem2_0_RLAST),
    .m_axi_gmem2_0_RID(m_axi_gmem2_0_RID),
    .m_axi_gmem2_0_RFIFONUM(m_axi_gmem2_0_RFIFONUM),
    .m_axi_gmem2_0_RUSER(m_axi_gmem2_0_RUSER),
    .m_axi_gmem2_0_RRESP(m_axi_gmem2_0_RRESP),
    .m_axi_gmem2_0_BVALID(1'b0),
    .m_axi_gmem2_0_BREADY(custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_BREADY),
    .m_axi_gmem2_0_BRESP(2'd0),
    .m_axi_gmem2_0_BID(1'd0),
    .m_axi_gmem2_0_BUSER(1'd0),
    .proj_weights(proj_weights),
    .unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_address0(custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_address0),
    .unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_ce0(custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_ce0),
    .unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_q0(unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_q0),
    .unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_address1(custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_address1),
    .unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_ce1(custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_ce1),
    .unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_q1(unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_q1),
    .unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_address0(custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_address0),
    .unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_ce0(custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_ce0),
    .unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_q0(unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_q0),
    .unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_address1(custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_address1),
    .unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_ce1(custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_ce1),
    .unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_q1(unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_q1),
    .unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_address0(custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_address0),
    .unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_ce0(custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_ce0),
    .unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_q0(unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_q0),
    .unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_address1(custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_address1),
    .unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_ce1(custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_ce1),
    .unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_q1(unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_q1),
    .unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_address0(custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_address0),
    .unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_ce0(custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_ce0),
    .unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_q0(unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_q0),
    .unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_address1(custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_address1),
    .unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_ce1(custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_ce1),
    .unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_q1(unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_q1),
    .unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_address0(custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_address0),
    .unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_ce0(custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_ce0),
    .unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_we0(custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_we0),
    .unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_d0(custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_d0),
    .unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_address0(custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_address0),
    .unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_ce0(custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_ce0),
    .unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_we0(custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_we0),
    .unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_d0(custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_d0),
    .unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_address0(custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_address0),
    .unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_ce0(custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_ce0),
    .unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_we0(custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_we0),
    .unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_d0(custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_d0),
    .unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_address0(custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_address0),
    .unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_ce0(custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_ce0),
    .unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_we0(custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_we0),
    .unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_d0(custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_d0)
);

assign ap_done = custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_ap_done;

assign ap_idle = custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_ap_idle;

assign ap_ready = custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_ap_ready;

assign custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_ap_continue = ap_continue;

assign custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_ap_start = ap_start;

assign m_axi_gmem2_0_ARADDR = custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARADDR;

assign m_axi_gmem2_0_ARBURST = custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARBURST;

assign m_axi_gmem2_0_ARCACHE = custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARCACHE;

assign m_axi_gmem2_0_ARID = custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARID;

assign m_axi_gmem2_0_ARLEN = custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARLEN;

assign m_axi_gmem2_0_ARLOCK = custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARLOCK;

assign m_axi_gmem2_0_ARPROT = custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARPROT;

assign m_axi_gmem2_0_ARQOS = custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARQOS;

assign m_axi_gmem2_0_ARREGION = custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARREGION;

assign m_axi_gmem2_0_ARSIZE = custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARSIZE;

assign m_axi_gmem2_0_ARUSER = custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARUSER;

assign m_axi_gmem2_0_ARVALID = custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_ARVALID;

assign m_axi_gmem2_0_AWADDR = 64'd0;

assign m_axi_gmem2_0_AWBURST = 2'd0;

assign m_axi_gmem2_0_AWCACHE = 4'd0;

assign m_axi_gmem2_0_AWID = 1'd0;

assign m_axi_gmem2_0_AWLEN = 32'd0;

assign m_axi_gmem2_0_AWLOCK = 2'd0;

assign m_axi_gmem2_0_AWPROT = 3'd0;

assign m_axi_gmem2_0_AWQOS = 4'd0;

assign m_axi_gmem2_0_AWREGION = 4'd0;

assign m_axi_gmem2_0_AWSIZE = 3'd0;

assign m_axi_gmem2_0_AWUSER = 1'd0;

assign m_axi_gmem2_0_AWVALID = 1'b0;

assign m_axi_gmem2_0_BREADY = 1'b0;

assign m_axi_gmem2_0_RREADY = custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_m_axi_gmem2_0_RREADY;

assign m_axi_gmem2_0_WDATA = 32'd0;

assign m_axi_gmem2_0_WID = 1'd0;

assign m_axi_gmem2_0_WLAST = 1'b0;

assign m_axi_gmem2_0_WSTRB = 4'd0;

assign m_axi_gmem2_0_WUSER = 1'd0;

assign m_axi_gmem2_0_WVALID = 1'b0;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_address0 = custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_address0;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_address1 = custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_address1;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_ce0 = custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_ce0;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_ce1 = custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_ce1;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_d0 = 18'd0;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_d1 = 18'd0;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_we0 = 1'b0;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_we1 = 1'b0;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_address0 = custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_address0;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_address1 = custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_address1;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_ce0 = custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_ce0;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_ce1 = custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_ce1;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_d0 = 18'd0;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_d1 = 18'd0;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_we0 = 1'b0;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_we1 = 1'b0;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_address0 = custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_address0;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_address1 = custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_address1;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_ce0 = custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_ce0;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_ce1 = custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_ce1;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_d0 = 18'd0;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_d1 = 18'd0;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_we0 = 1'b0;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_we1 = 1'b0;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_address0 = custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_address0;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_address1 = custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_address1;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_ce0 = custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_ce0;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_ce1 = custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_ce1;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_d0 = 18'd0;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_d1 = 18'd0;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_we0 = 1'b0;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_we1 = 1'b0;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_address0 = custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_address0;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_address1 = 8'd0;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_ce0 = custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_ce0;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_ce1 = 1'b0;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_d0 = custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_d0;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_d1 = 18'd0;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_we0 = custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_we0;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_1_we1 = 1'b0;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_address0 = custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_address0;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_address1 = 8'd0;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_ce0 = custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_ce0;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_ce1 = 1'b0;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_d0 = custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_d0;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_d1 = 18'd0;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_we0 = custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_we0;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_2_we1 = 1'b0;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_address0 = custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_address0;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_address1 = 8'd0;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_ce0 = custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_ce0;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_ce1 = 1'b0;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_d0 = custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_d0;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_d1 = 18'd0;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_we0 = custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_we0;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_3_we1 = 1'b0;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_address0 = custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_address0;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_address1 = 8'd0;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_ce0 = custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_ce0;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_ce1 = 1'b0;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_d0 = custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_d0;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_d1 = 18'd0;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_we0 = custom_pvm_layer_config_enc5_Block_entry_enc4_out_rd_proc_U0_unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_we0;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc5_out_we1 = 1'b0;

endmodule //unet_pvm_top_custom_pvm_layer_config_enc5_s
