// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module unet_pvm_top_pvm_merge_and_project_config_enc5_Pipeline_VITIS_LOOP_103_4 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        mamba_out_2_dout,
        mamba_out_2_empty_n,
        mamba_out_2_read,
        mamba_out_1_dout,
        mamba_out_1_empty_n,
        mamba_out_1_read,
        mamba_out_0_dout,
        mamba_out_0_empty_n,
        mamba_out_0_read,
        mamba_out_3_dout,
        mamba_out_3_empty_n,
        mamba_out_3_read,
        t,
        merged_31_out,
        merged_31_out_ap_vld,
        merged_30_out,
        merged_30_out_ap_vld,
        merged_29_out,
        merged_29_out_ap_vld,
        merged_28_out,
        merged_28_out_ap_vld,
        merged_27_out,
        merged_27_out_ap_vld,
        merged_26_out,
        merged_26_out_ap_vld,
        merged_25_out,
        merged_25_out_ap_vld,
        merged_24_out,
        merged_24_out_ap_vld,
        merged_23_out,
        merged_23_out_ap_vld,
        merged_22_out,
        merged_22_out_ap_vld,
        merged_21_out,
        merged_21_out_ap_vld,
        merged_20_out,
        merged_20_out_ap_vld,
        merged_19_out,
        merged_19_out_ap_vld,
        merged_18_out,
        merged_18_out_ap_vld,
        merged_17_out,
        merged_17_out_ap_vld,
        merged_16_out,
        merged_16_out_ap_vld,
        merged_15_out,
        merged_15_out_ap_vld,
        merged_14_out,
        merged_14_out_ap_vld,
        merged_13_out,
        merged_13_out_ap_vld,
        merged_12_out,
        merged_12_out_ap_vld,
        merged_11_out,
        merged_11_out_ap_vld,
        merged_10_out,
        merged_10_out_ap_vld,
        merged_9_out,
        merged_9_out_ap_vld,
        merged_8_out,
        merged_8_out_ap_vld,
        merged_7_out,
        merged_7_out_ap_vld,
        merged_6_out,
        merged_6_out_ap_vld,
        merged_5_out,
        merged_5_out_ap_vld,
        merged_4_out,
        merged_4_out_ap_vld,
        merged_3_out,
        merged_3_out_ap_vld,
        merged_2_out,
        merged_2_out_ap_vld,
        merged_1_out,
        merged_1_out_ap_vld,
        merged_out,
        merged_out_ap_vld,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_address0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_ce0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_q0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_address1,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_ce1,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_q1,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_address0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_ce0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_q0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_address1,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_ce1,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_q1,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_address0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_ce0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_q0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_address1,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_ce1,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_q1,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_address0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_ce0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_q0,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_address1,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_ce1,
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_q1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [575:0] mamba_out_2_dout;
input   mamba_out_2_empty_n;
output   mamba_out_2_read;
input  [575:0] mamba_out_1_dout;
input   mamba_out_1_empty_n;
output   mamba_out_1_read;
input  [575:0] mamba_out_0_dout;
input   mamba_out_0_empty_n;
output   mamba_out_0_read;
input  [575:0] mamba_out_3_dout;
input   mamba_out_3_empty_n;
output   mamba_out_3_read;
input  [3:0] t;
output  [17:0] merged_31_out;
output   merged_31_out_ap_vld;
output  [17:0] merged_30_out;
output   merged_30_out_ap_vld;
output  [17:0] merged_29_out;
output   merged_29_out_ap_vld;
output  [17:0] merged_28_out;
output   merged_28_out_ap_vld;
output  [17:0] merged_27_out;
output   merged_27_out_ap_vld;
output  [17:0] merged_26_out;
output   merged_26_out_ap_vld;
output  [17:0] merged_25_out;
output   merged_25_out_ap_vld;
output  [17:0] merged_24_out;
output   merged_24_out_ap_vld;
output  [17:0] merged_23_out;
output   merged_23_out_ap_vld;
output  [17:0] merged_22_out;
output   merged_22_out_ap_vld;
output  [17:0] merged_21_out;
output   merged_21_out_ap_vld;
output  [17:0] merged_20_out;
output   merged_20_out_ap_vld;
output  [17:0] merged_19_out;
output   merged_19_out_ap_vld;
output  [17:0] merged_18_out;
output   merged_18_out_ap_vld;
output  [17:0] merged_17_out;
output   merged_17_out_ap_vld;
output  [17:0] merged_16_out;
output   merged_16_out_ap_vld;
output  [17:0] merged_15_out;
output   merged_15_out_ap_vld;
output  [17:0] merged_14_out;
output   merged_14_out_ap_vld;
output  [17:0] merged_13_out;
output   merged_13_out_ap_vld;
output  [17:0] merged_12_out;
output   merged_12_out_ap_vld;
output  [17:0] merged_11_out;
output   merged_11_out_ap_vld;
output  [17:0] merged_10_out;
output   merged_10_out_ap_vld;
output  [17:0] merged_9_out;
output   merged_9_out_ap_vld;
output  [17:0] merged_8_out;
output   merged_8_out_ap_vld;
output  [17:0] merged_7_out;
output   merged_7_out_ap_vld;
output  [17:0] merged_6_out;
output   merged_6_out_ap_vld;
output  [17:0] merged_5_out;
output   merged_5_out_ap_vld;
output  [17:0] merged_4_out;
output   merged_4_out_ap_vld;
output  [17:0] merged_3_out;
output   merged_3_out_ap_vld;
output  [17:0] merged_2_out;
output   merged_2_out_ap_vld;
output  [17:0] merged_1_out;
output   merged_1_out_ap_vld;
output  [17:0] merged_out;
output   merged_out_ap_vld;
output  [6:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_address0;
output   unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_ce0;
input  [17:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_q0;
output  [6:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_address1;
output   unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_ce1;
input  [17:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_q1;
output  [6:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_address0;
output   unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_ce0;
input  [17:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_q0;
output  [6:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_address1;
output   unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_ce1;
input  [17:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_q1;
output  [6:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_address0;
output   unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_ce0;
input  [17:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_q0;
output  [6:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_address1;
output   unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_ce1;
input  [17:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_q1;
output  [6:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_address0;
output   unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_ce0;
input  [17:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_q0;
output  [6:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_address1;
output   unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_ce1;
input  [17:0] unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_q1;

reg ap_idle;
reg mamba_out_2_read;
reg mamba_out_1_read;
reg mamba_out_0_read;
reg mamba_out_3_read;
reg merged_31_out_ap_vld;
reg merged_30_out_ap_vld;
reg merged_29_out_ap_vld;
reg merged_28_out_ap_vld;
reg merged_27_out_ap_vld;
reg merged_26_out_ap_vld;
reg merged_25_out_ap_vld;
reg merged_24_out_ap_vld;
reg merged_23_out_ap_vld;
reg merged_22_out_ap_vld;
reg merged_21_out_ap_vld;
reg merged_20_out_ap_vld;
reg merged_19_out_ap_vld;
reg merged_18_out_ap_vld;
reg merged_17_out_ap_vld;
reg merged_16_out_ap_vld;
reg merged_15_out_ap_vld;
reg merged_14_out_ap_vld;
reg merged_13_out_ap_vld;
reg merged_12_out_ap_vld;
reg merged_11_out_ap_vld;
reg merged_10_out_ap_vld;
reg merged_9_out_ap_vld;
reg merged_8_out_ap_vld;
reg merged_7_out_ap_vld;
reg merged_6_out_ap_vld;
reg merged_5_out_ap_vld;
reg merged_4_out_ap_vld;
reg merged_3_out_ap_vld;
reg merged_2_out_ap_vld;
reg merged_1_out_ap_vld;
reg merged_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
reg   [0:0] icmp_ln103_reg_2575;
reg   [1:0] trunc_ln103_reg_2579;
reg    ap_predicate_op82_read_state2;
reg    ap_predicate_op95_read_state2;
reg    ap_predicate_op108_read_state2;
reg    ap_predicate_op120_read_state2;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln103_fu_733_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    mamba_out_0_blk_n;
wire    ap_block_pp0_stage0;
reg    mamba_out_1_blk_n;
reg    mamba_out_2_blk_n;
reg    mamba_out_3_blk_n;
reg    ap_block_pp0_stage0_11001;
wire   [1:0] trunc_ln103_fu_745_p1;
reg   [241:0] ap_phi_mux_p_in_phi_fu_715_p8;
wire   [241:0] tmp_27_fu_1102_p16;
wire   [241:0] ap_phi_reg_pp0_iter1_p_in_reg_712;
wire   [241:0] tmp_28_fu_993_p16;
wire   [241:0] tmp_29_fu_884_p16;
wire   [241:0] tmp_26_fu_1211_p16;
wire   [63:0] zext_ln110_fu_769_p1;
wire   [63:0] zext_ln110_1_fu_787_p1;
reg   [2:0] chunk_fu_226;
wire   [2:0] add_ln103_fu_739_p2;
wire    ap_loop_init;
reg   [2:0] ap_sig_allocacmp_chunk_2;
reg   [17:0] merged_fu_230;
wire   [17:0] merged_32_fu_1338_p3;
reg   [17:0] merged_1_fu_234;
wire   [17:0] merged_33_fu_1444_p3;
reg   [17:0] merged_2_fu_238;
wire   [17:0] merged_34_fu_1550_p3;
reg   [17:0] merged_3_fu_242;
wire   [17:0] merged_35_fu_1656_p3;
reg   [17:0] merged_4_fu_246;
wire   [17:0] merged_36_fu_1762_p3;
reg   [17:0] merged_5_fu_250;
wire   [17:0] merged_37_fu_1868_p3;
reg   [17:0] merged_6_fu_254;
wire   [17:0] merged_38_fu_1974_p3;
reg   [17:0] merged_7_fu_258;
wire   [17:0] merged_39_fu_2080_p3;
reg   [17:0] merged_8_fu_262;
reg   [17:0] merged_9_fu_266;
reg   [17:0] merged_10_fu_270;
reg   [17:0] merged_11_fu_274;
reg   [17:0] merged_12_fu_278;
reg   [17:0] merged_13_fu_282;
reg   [17:0] merged_14_fu_286;
reg   [17:0] merged_15_fu_290;
reg   [17:0] merged_16_fu_294;
reg   [17:0] merged_17_fu_298;
reg   [17:0] merged_18_fu_302;
reg   [17:0] merged_19_fu_306;
reg   [17:0] merged_20_fu_310;
reg   [17:0] merged_21_fu_314;
reg   [17:0] merged_22_fu_318;
reg   [17:0] merged_23_fu_322;
reg   [17:0] merged_24_fu_326;
reg   [17:0] merged_25_fu_330;
reg   [17:0] merged_26_fu_334;
reg   [17:0] merged_27_fu_338;
reg   [17:0] merged_28_fu_342;
reg   [17:0] merged_29_fu_346;
reg   [17:0] merged_30_fu_350;
reg   [17:0] merged_31_fu_354;
reg    ap_block_pp0_stage0_01001;
reg    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_ce1_local;
reg    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_ce0_local;
reg    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_ce1_local;
reg    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_ce0_local;
reg    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_ce1_local;
reg    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_ce0_local;
reg    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_ce1_local;
reg    unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_ce0_local;
wire   [6:0] or_ln110_1_fu_759_p4;
wire   [6:0] or_ln110_2_fu_777_p4;
wire   [17:0] trunc_ln105_29_fu_874_p4;
wire   [17:0] trunc_ln105_28_fu_864_p4;
wire   [17:0] trunc_ln105_27_fu_854_p4;
wire   [17:0] trunc_ln105_26_fu_844_p4;
wire   [17:0] trunc_ln105_25_fu_834_p4;
wire   [17:0] trunc_ln105_24_fu_824_p4;
wire   [17:0] trunc_ln105_22_fu_814_p4;
wire   [17:0] trunc_ln105_31_fu_810_p1;
wire   [17:0] trunc_ln105_21_fu_983_p4;
wire   [17:0] trunc_ln105_20_fu_973_p4;
wire   [17:0] trunc_ln105_19_fu_963_p4;
wire   [17:0] trunc_ln105_18_fu_953_p4;
wire   [17:0] trunc_ln105_17_fu_943_p4;
wire   [17:0] trunc_ln105_16_fu_933_p4;
wire   [17:0] trunc_ln105_14_fu_923_p4;
wire   [17:0] trunc_ln105_23_fu_919_p1;
wire   [17:0] trunc_ln105_13_fu_1092_p4;
wire   [17:0] trunc_ln105_12_fu_1082_p4;
wire   [17:0] trunc_ln105_11_fu_1072_p4;
wire   [17:0] trunc_ln105_10_fu_1062_p4;
wire   [17:0] trunc_ln105_s_fu_1052_p4;
wire   [17:0] trunc_ln105_9_fu_1042_p4;
wire   [17:0] trunc_ln105_8_fu_1032_p4;
wire   [17:0] trunc_ln105_15_fu_1028_p1;
wire   [17:0] trunc_ln105_7_fu_1201_p4;
wire   [17:0] trunc_ln105_6_fu_1191_p4;
wire   [17:0] trunc_ln105_5_fu_1181_p4;
wire   [17:0] trunc_ln105_4_fu_1171_p4;
wire   [17:0] trunc_ln105_3_fu_1161_p4;
wire   [17:0] trunc_ln105_2_fu_1151_p4;
wire   [17:0] trunc_ln105_1_fu_1141_p4;
wire   [17:0] trunc_ln105_fu_1137_p1;
wire   [17:0] trunc_ln111_fu_1254_p1;
wire  signed [27:0] shl_ln111_1_fu_1258_p3;
wire  signed [27:0] shl_ln2_fu_1246_p3;
wire  signed [28:0] sext_ln111_1_fu_1270_p1;
wire  signed [28:0] sext_ln111_fu_1266_p1;
wire   [28:0] add_ln111_fu_1280_p2;
wire   [27:0] add_ln111_8_fu_1274_p2;
wire   [0:0] tmp_fu_1286_p3;
wire   [0:0] tmp_294_fu_1304_p3;
wire   [0:0] xor_ln111_fu_1312_p2;
wire   [0:0] and_ln111_fu_1318_p2;
wire   [0:0] xor_ln111_1_fu_1332_p2;
wire   [17:0] select_ln111_fu_1324_p3;
wire   [17:0] trunc_ln_fu_1294_p4;
wire   [17:0] tmp_20_fu_1354_p4;
wire  signed [27:0] shl_ln111_3_fu_1364_p3;
wire  signed [27:0] shl_ln111_2_fu_1346_p3;
wire  signed [28:0] sext_ln111_3_fu_1376_p1;
wire  signed [28:0] sext_ln111_2_fu_1372_p1;
wire   [28:0] add_ln111_1_fu_1386_p2;
wire   [27:0] add_ln111_9_fu_1380_p2;
wire   [0:0] tmp_295_fu_1392_p3;
wire   [0:0] tmp_296_fu_1410_p3;
wire   [0:0] xor_ln111_2_fu_1418_p2;
wire   [0:0] and_ln111_1_fu_1424_p2;
wire   [0:0] xor_ln111_3_fu_1438_p2;
wire   [17:0] select_ln111_2_fu_1430_p3;
wire   [17:0] trunc_ln111_1_fu_1400_p4;
wire   [17:0] tmp_21_fu_1460_p4;
wire  signed [27:0] shl_ln111_5_fu_1470_p3;
wire  signed [27:0] shl_ln111_4_fu_1452_p3;
wire  signed [28:0] sext_ln111_5_fu_1482_p1;
wire  signed [28:0] sext_ln111_4_fu_1478_p1;
wire   [28:0] add_ln111_2_fu_1492_p2;
wire   [27:0] add_ln111_10_fu_1486_p2;
wire   [0:0] tmp_297_fu_1498_p3;
wire   [0:0] tmp_298_fu_1516_p3;
wire   [0:0] xor_ln111_4_fu_1524_p2;
wire   [0:0] and_ln111_2_fu_1530_p2;
wire   [0:0] xor_ln111_5_fu_1544_p2;
wire   [17:0] select_ln111_4_fu_1536_p3;
wire   [17:0] trunc_ln111_2_fu_1506_p4;
wire   [17:0] tmp_22_fu_1566_p4;
wire  signed [27:0] shl_ln111_7_fu_1576_p3;
wire  signed [27:0] shl_ln111_6_fu_1558_p3;
wire  signed [28:0] sext_ln111_7_fu_1588_p1;
wire  signed [28:0] sext_ln111_6_fu_1584_p1;
wire   [28:0] add_ln111_3_fu_1598_p2;
wire   [27:0] add_ln111_11_fu_1592_p2;
wire   [0:0] tmp_299_fu_1604_p3;
wire   [0:0] tmp_300_fu_1622_p3;
wire   [0:0] xor_ln111_6_fu_1630_p2;
wire   [0:0] and_ln111_3_fu_1636_p2;
wire   [0:0] xor_ln111_7_fu_1650_p2;
wire   [17:0] select_ln111_6_fu_1642_p3;
wire   [17:0] trunc_ln111_3_fu_1612_p4;
wire   [17:0] tmp_23_fu_1672_p4;
wire  signed [27:0] shl_ln111_9_fu_1682_p3;
wire  signed [27:0] shl_ln111_8_fu_1664_p3;
wire  signed [28:0] sext_ln111_9_fu_1694_p1;
wire  signed [28:0] sext_ln111_8_fu_1690_p1;
wire   [28:0] add_ln111_4_fu_1704_p2;
wire   [27:0] add_ln111_12_fu_1698_p2;
wire   [0:0] tmp_301_fu_1710_p3;
wire   [0:0] tmp_302_fu_1728_p3;
wire   [0:0] xor_ln111_8_fu_1736_p2;
wire   [0:0] and_ln111_4_fu_1742_p2;
wire   [0:0] xor_ln111_9_fu_1756_p2;
wire   [17:0] select_ln111_8_fu_1748_p3;
wire   [17:0] trunc_ln111_4_fu_1718_p4;
wire   [17:0] tmp_24_fu_1778_p4;
wire  signed [27:0] shl_ln111_10_fu_1788_p3;
wire  signed [27:0] shl_ln111_s_fu_1770_p3;
wire  signed [28:0] sext_ln111_11_fu_1800_p1;
wire  signed [28:0] sext_ln111_10_fu_1796_p1;
wire   [28:0] add_ln111_5_fu_1810_p2;
wire   [27:0] add_ln111_13_fu_1804_p2;
wire   [0:0] tmp_303_fu_1816_p3;
wire   [0:0] tmp_304_fu_1834_p3;
wire   [0:0] xor_ln111_10_fu_1842_p2;
wire   [0:0] and_ln111_5_fu_1848_p2;
wire   [0:0] xor_ln111_11_fu_1862_p2;
wire   [17:0] select_ln111_10_fu_1854_p3;
wire   [17:0] trunc_ln111_5_fu_1824_p4;
wire   [17:0] tmp_25_fu_1884_p4;
wire  signed [27:0] shl_ln111_12_fu_1894_p3;
wire  signed [27:0] shl_ln111_11_fu_1876_p3;
wire  signed [28:0] sext_ln111_13_fu_1906_p1;
wire  signed [28:0] sext_ln111_12_fu_1902_p1;
wire   [28:0] add_ln111_6_fu_1916_p2;
wire   [27:0] add_ln111_14_fu_1910_p2;
wire   [0:0] tmp_305_fu_1922_p3;
wire   [0:0] tmp_306_fu_1940_p3;
wire   [0:0] xor_ln111_12_fu_1948_p2;
wire   [0:0] and_ln111_6_fu_1954_p2;
wire   [0:0] xor_ln111_13_fu_1968_p2;
wire   [17:0] select_ln111_12_fu_1960_p3;
wire   [17:0] trunc_ln111_6_fu_1930_p4;
wire   [17:0] tmp_31_fu_1990_p4;
wire  signed [27:0] shl_ln111_14_fu_2000_p3;
wire  signed [27:0] shl_ln111_13_fu_1982_p3;
wire  signed [28:0] sext_ln111_15_fu_2012_p1;
wire  signed [28:0] sext_ln111_14_fu_2008_p1;
wire   [28:0] add_ln111_7_fu_2022_p2;
wire   [27:0] add_ln111_15_fu_2016_p2;
wire   [0:0] tmp_307_fu_2028_p3;
wire   [0:0] tmp_308_fu_2046_p3;
wire   [0:0] xor_ln111_14_fu_2054_p2;
wire   [0:0] and_ln111_7_fu_2060_p2;
wire   [0:0] xor_ln111_15_fu_2074_p2;
wire   [17:0] select_ln111_14_fu_2066_p3;
wire   [17:0] trunc_ln111_7_fu_2036_p4;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 chunk_fu_226 = 3'd0;
#0 merged_fu_230 = 18'd0;
#0 merged_1_fu_234 = 18'd0;
#0 merged_2_fu_238 = 18'd0;
#0 merged_3_fu_242 = 18'd0;
#0 merged_4_fu_246 = 18'd0;
#0 merged_5_fu_250 = 18'd0;
#0 merged_6_fu_254 = 18'd0;
#0 merged_7_fu_258 = 18'd0;
#0 merged_8_fu_262 = 18'd0;
#0 merged_9_fu_266 = 18'd0;
#0 merged_10_fu_270 = 18'd0;
#0 merged_11_fu_274 = 18'd0;
#0 merged_12_fu_278 = 18'd0;
#0 merged_13_fu_282 = 18'd0;
#0 merged_14_fu_286 = 18'd0;
#0 merged_15_fu_290 = 18'd0;
#0 merged_16_fu_294 = 18'd0;
#0 merged_17_fu_298 = 18'd0;
#0 merged_18_fu_302 = 18'd0;
#0 merged_19_fu_306 = 18'd0;
#0 merged_20_fu_310 = 18'd0;
#0 merged_21_fu_314 = 18'd0;
#0 merged_22_fu_318 = 18'd0;
#0 merged_23_fu_322 = 18'd0;
#0 merged_24_fu_326 = 18'd0;
#0 merged_25_fu_330 = 18'd0;
#0 merged_26_fu_334 = 18'd0;
#0 merged_27_fu_338 = 18'd0;
#0 merged_28_fu_342 = 18'd0;
#0 merged_29_fu_346 = 18'd0;
#0 merged_30_fu_350 = 18'd0;
#0 merged_31_fu_354 = 18'd0;
#0 ap_done_reg = 1'b0;
end

unet_pvm_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln103_fu_733_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            chunk_fu_226 <= add_ln103_fu_739_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            chunk_fu_226 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln103_reg_2575 <= icmp_ln103_fu_733_p2;
        trunc_ln103_reg_2579 <= trunc_ln103_fu_745_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln103_reg_2579 == 2'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        merged_10_fu_270 <= merged_34_fu_1550_p3;
        merged_11_fu_274 <= merged_35_fu_1656_p3;
        merged_12_fu_278 <= merged_36_fu_1762_p3;
        merged_13_fu_282 <= merged_37_fu_1868_p3;
        merged_14_fu_286 <= merged_38_fu_1974_p3;
        merged_15_fu_290 <= merged_39_fu_2080_p3;
        merged_8_fu_262 <= merged_32_fu_1338_p3;
        merged_9_fu_266 <= merged_33_fu_1444_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln103_reg_2579 == 2'd2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        merged_16_fu_294 <= merged_32_fu_1338_p3;
        merged_17_fu_298 <= merged_33_fu_1444_p3;
        merged_18_fu_302 <= merged_34_fu_1550_p3;
        merged_19_fu_306 <= merged_35_fu_1656_p3;
        merged_20_fu_310 <= merged_36_fu_1762_p3;
        merged_21_fu_314 <= merged_37_fu_1868_p3;
        merged_22_fu_318 <= merged_38_fu_1974_p3;
        merged_23_fu_322 <= merged_39_fu_2080_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln103_reg_2579 == 2'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        merged_1_fu_234 <= merged_33_fu_1444_p3;
        merged_2_fu_238 <= merged_34_fu_1550_p3;
        merged_3_fu_242 <= merged_35_fu_1656_p3;
        merged_4_fu_246 <= merged_36_fu_1762_p3;
        merged_5_fu_250 <= merged_37_fu_1868_p3;
        merged_6_fu_254 <= merged_38_fu_1974_p3;
        merged_7_fu_258 <= merged_39_fu_2080_p3;
        merged_fu_230 <= merged_32_fu_1338_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln103_reg_2579 == 2'd3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        merged_24_fu_326 <= merged_32_fu_1338_p3;
        merged_25_fu_330 <= merged_33_fu_1444_p3;
        merged_26_fu_334 <= merged_34_fu_1550_p3;
        merged_27_fu_338 <= merged_35_fu_1656_p3;
        merged_28_fu_342 <= merged_36_fu_1762_p3;
        merged_29_fu_346 <= merged_37_fu_1868_p3;
        merged_30_fu_350 <= merged_38_fu_1974_p3;
        merged_31_fu_354 <= merged_39_fu_2080_p3;
    end
end

always @ (*) begin
    if (((icmp_ln103_fu_733_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln103_reg_2575 == 1'd0)) begin
        if ((trunc_ln103_reg_2579 == 2'd3)) begin
            ap_phi_mux_p_in_phi_fu_715_p8 = tmp_26_fu_1211_p16;
        end else if ((trunc_ln103_reg_2579 == 2'd2)) begin
            ap_phi_mux_p_in_phi_fu_715_p8 = tmp_29_fu_884_p16;
        end else if ((trunc_ln103_reg_2579 == 2'd1)) begin
            ap_phi_mux_p_in_phi_fu_715_p8 = tmp_28_fu_993_p16;
        end else if ((trunc_ln103_reg_2579 == 2'd0)) begin
            ap_phi_mux_p_in_phi_fu_715_p8 = tmp_27_fu_1102_p16;
        end else begin
            ap_phi_mux_p_in_phi_fu_715_p8 = ap_phi_reg_pp0_iter1_p_in_reg_712;
        end
    end else begin
        ap_phi_mux_p_in_phi_fu_715_p8 = ap_phi_reg_pp0_iter1_p_in_reg_712;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_chunk_2 = 3'd0;
    end else begin
        ap_sig_allocacmp_chunk_2 = chunk_fu_226;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op108_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mamba_out_0_blk_n = mamba_out_0_empty_n;
    end else begin
        mamba_out_0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op108_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mamba_out_0_read = 1'b1;
    end else begin
        mamba_out_0_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op95_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mamba_out_1_blk_n = mamba_out_1_empty_n;
    end else begin
        mamba_out_1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op95_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mamba_out_1_read = 1'b1;
    end else begin
        mamba_out_1_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op82_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mamba_out_2_blk_n = mamba_out_2_empty_n;
    end else begin
        mamba_out_2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op82_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mamba_out_2_read = 1'b1;
    end else begin
        mamba_out_2_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op120_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mamba_out_3_blk_n = mamba_out_3_empty_n;
    end else begin
        mamba_out_3_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op120_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mamba_out_3_read = 1'b1;
    end else begin
        mamba_out_3_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln103_fu_733_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        merged_10_out_ap_vld = 1'b1;
    end else begin
        merged_10_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln103_fu_733_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        merged_11_out_ap_vld = 1'b1;
    end else begin
        merged_11_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln103_fu_733_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        merged_12_out_ap_vld = 1'b1;
    end else begin
        merged_12_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln103_fu_733_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        merged_13_out_ap_vld = 1'b1;
    end else begin
        merged_13_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln103_fu_733_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        merged_14_out_ap_vld = 1'b1;
    end else begin
        merged_14_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln103_fu_733_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        merged_15_out_ap_vld = 1'b1;
    end else begin
        merged_15_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln103_fu_733_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        merged_16_out_ap_vld = 1'b1;
    end else begin
        merged_16_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln103_fu_733_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        merged_17_out_ap_vld = 1'b1;
    end else begin
        merged_17_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln103_fu_733_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        merged_18_out_ap_vld = 1'b1;
    end else begin
        merged_18_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln103_fu_733_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        merged_19_out_ap_vld = 1'b1;
    end else begin
        merged_19_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln103_fu_733_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        merged_1_out_ap_vld = 1'b1;
    end else begin
        merged_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln103_fu_733_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        merged_20_out_ap_vld = 1'b1;
    end else begin
        merged_20_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln103_fu_733_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        merged_21_out_ap_vld = 1'b1;
    end else begin
        merged_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln103_fu_733_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        merged_22_out_ap_vld = 1'b1;
    end else begin
        merged_22_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln103_fu_733_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        merged_23_out_ap_vld = 1'b1;
    end else begin
        merged_23_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln103_fu_733_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        merged_24_out_ap_vld = 1'b1;
    end else begin
        merged_24_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln103_fu_733_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        merged_25_out_ap_vld = 1'b1;
    end else begin
        merged_25_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln103_fu_733_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        merged_26_out_ap_vld = 1'b1;
    end else begin
        merged_26_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln103_fu_733_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        merged_27_out_ap_vld = 1'b1;
    end else begin
        merged_27_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln103_fu_733_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        merged_28_out_ap_vld = 1'b1;
    end else begin
        merged_28_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln103_fu_733_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        merged_29_out_ap_vld = 1'b1;
    end else begin
        merged_29_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln103_fu_733_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        merged_2_out_ap_vld = 1'b1;
    end else begin
        merged_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln103_fu_733_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        merged_30_out_ap_vld = 1'b1;
    end else begin
        merged_30_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln103_fu_733_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        merged_31_out_ap_vld = 1'b1;
    end else begin
        merged_31_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln103_fu_733_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        merged_3_out_ap_vld = 1'b1;
    end else begin
        merged_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln103_fu_733_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        merged_4_out_ap_vld = 1'b1;
    end else begin
        merged_4_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln103_fu_733_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        merged_5_out_ap_vld = 1'b1;
    end else begin
        merged_5_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln103_fu_733_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        merged_6_out_ap_vld = 1'b1;
    end else begin
        merged_6_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln103_fu_733_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        merged_7_out_ap_vld = 1'b1;
    end else begin
        merged_7_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln103_fu_733_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        merged_8_out_ap_vld = 1'b1;
    end else begin
        merged_8_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln103_fu_733_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        merged_9_out_ap_vld = 1'b1;
    end else begin
        merged_9_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln103_fu_733_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        merged_out_ap_vld = 1'b1;
    end else begin
        merged_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_ce0_local = 1'b1;
    end else begin
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_ce1_local = 1'b1;
    end else begin
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_ce0_local = 1'b1;
    end else begin
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_ce1_local = 1'b1;
    end else begin
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_ce0_local = 1'b1;
    end else begin
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_ce1_local = 1'b1;
    end else begin
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_ce0_local = 1'b1;
    end else begin
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_ce1_local = 1'b1;
    end else begin
        unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_ce1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln103_fu_739_p2 = (ap_sig_allocacmp_chunk_2 + 3'd1);

assign add_ln111_10_fu_1486_p2 = ($signed(shl_ln111_4_fu_1452_p3) + $signed(shl_ln111_5_fu_1470_p3));

assign add_ln111_11_fu_1592_p2 = ($signed(shl_ln111_6_fu_1558_p3) + $signed(shl_ln111_7_fu_1576_p3));

assign add_ln111_12_fu_1698_p2 = ($signed(shl_ln111_8_fu_1664_p3) + $signed(shl_ln111_9_fu_1682_p3));

assign add_ln111_13_fu_1804_p2 = ($signed(shl_ln111_s_fu_1770_p3) + $signed(shl_ln111_10_fu_1788_p3));

assign add_ln111_14_fu_1910_p2 = ($signed(shl_ln111_11_fu_1876_p3) + $signed(shl_ln111_12_fu_1894_p3));

assign add_ln111_15_fu_2016_p2 = ($signed(shl_ln111_13_fu_1982_p3) + $signed(shl_ln111_14_fu_2000_p3));

assign add_ln111_1_fu_1386_p2 = ($signed(sext_ln111_3_fu_1376_p1) + $signed(sext_ln111_2_fu_1372_p1));

assign add_ln111_2_fu_1492_p2 = ($signed(sext_ln111_5_fu_1482_p1) + $signed(sext_ln111_4_fu_1478_p1));

assign add_ln111_3_fu_1598_p2 = ($signed(sext_ln111_7_fu_1588_p1) + $signed(sext_ln111_6_fu_1584_p1));

assign add_ln111_4_fu_1704_p2 = ($signed(sext_ln111_9_fu_1694_p1) + $signed(sext_ln111_8_fu_1690_p1));

assign add_ln111_5_fu_1810_p2 = ($signed(sext_ln111_11_fu_1800_p1) + $signed(sext_ln111_10_fu_1796_p1));

assign add_ln111_6_fu_1916_p2 = ($signed(sext_ln111_13_fu_1906_p1) + $signed(sext_ln111_12_fu_1902_p1));

assign add_ln111_7_fu_2022_p2 = ($signed(sext_ln111_15_fu_2012_p1) + $signed(sext_ln111_14_fu_2008_p1));

assign add_ln111_8_fu_1274_p2 = ($signed(shl_ln2_fu_1246_p3) + $signed(shl_ln111_1_fu_1258_p3));

assign add_ln111_9_fu_1380_p2 = ($signed(shl_ln111_2_fu_1346_p3) + $signed(shl_ln111_3_fu_1364_p3));

assign add_ln111_fu_1280_p2 = ($signed(sext_ln111_1_fu_1270_p1) + $signed(sext_ln111_fu_1266_p1));

assign and_ln111_1_fu_1424_p2 = (xor_ln111_2_fu_1418_p2 & tmp_296_fu_1410_p3);

assign and_ln111_2_fu_1530_p2 = (xor_ln111_4_fu_1524_p2 & tmp_298_fu_1516_p3);

assign and_ln111_3_fu_1636_p2 = (xor_ln111_6_fu_1630_p2 & tmp_300_fu_1622_p3);

assign and_ln111_4_fu_1742_p2 = (xor_ln111_8_fu_1736_p2 & tmp_302_fu_1728_p3);

assign and_ln111_5_fu_1848_p2 = (xor_ln111_10_fu_1842_p2 & tmp_304_fu_1834_p3);

assign and_ln111_6_fu_1954_p2 = (xor_ln111_12_fu_1948_p2 & tmp_306_fu_1940_p3);

assign and_ln111_7_fu_2060_p2 = (xor_ln111_14_fu_2054_p2 & tmp_308_fu_2046_p3);

assign and_ln111_fu_1318_p2 = (xor_ln111_fu_1312_p2 & tmp_294_fu_1304_p3);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (((ap_predicate_op120_read_state2 == 1'b1) & (mamba_out_3_empty_n == 1'b0)) | ((ap_predicate_op108_read_state2 == 1'b1) & (mamba_out_0_empty_n == 1'b0)) | ((ap_predicate_op95_read_state2 == 1'b1) & (mamba_out_1_empty_n == 1'b0)) | ((ap_predicate_op82_read_state2 == 1'b1) & (mamba_out_2_empty_n == 1'b0)));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter1_p_in_reg_712 = 'bx;

always @ (*) begin
    ap_predicate_op108_read_state2 = ((trunc_ln103_reg_2579 == 2'd0) & (icmp_ln103_reg_2575 == 1'd0));
end

always @ (*) begin
    ap_predicate_op120_read_state2 = ((trunc_ln103_reg_2579 == 2'd3) & (icmp_ln103_reg_2575 == 1'd0));
end

always @ (*) begin
    ap_predicate_op82_read_state2 = ((trunc_ln103_reg_2579 == 2'd2) & (icmp_ln103_reg_2575 == 1'd0));
end

always @ (*) begin
    ap_predicate_op95_read_state2 = ((trunc_ln103_reg_2579 == 2'd1) & (icmp_ln103_reg_2575 == 1'd0));
end

assign ap_ready = ap_ready_sig;

assign icmp_ln103_fu_733_p2 = ((ap_sig_allocacmp_chunk_2 == 3'd4) ? 1'b1 : 1'b0);

assign merged_10_out = merged_10_fu_270;

assign merged_11_out = merged_11_fu_274;

assign merged_12_out = merged_12_fu_278;

assign merged_13_out = merged_13_fu_282;

assign merged_14_out = merged_14_fu_286;

assign merged_15_out = merged_15_fu_290;

assign merged_16_out = merged_16_fu_294;

assign merged_17_out = merged_17_fu_298;

assign merged_18_out = merged_18_fu_302;

assign merged_19_out = merged_19_fu_306;

assign merged_1_out = merged_1_fu_234;

assign merged_20_out = merged_20_fu_310;

assign merged_21_out = merged_21_fu_314;

assign merged_22_out = merged_22_fu_318;

assign merged_23_out = merged_23_fu_322;

assign merged_24_out = merged_24_fu_326;

assign merged_25_out = merged_25_fu_330;

assign merged_26_out = merged_26_fu_334;

assign merged_27_out = merged_27_fu_338;

assign merged_28_out = merged_28_fu_342;

assign merged_29_out = merged_29_fu_346;

assign merged_2_out = merged_2_fu_238;

assign merged_30_out = merged_30_fu_350;

assign merged_31_out = merged_31_fu_354;

assign merged_32_fu_1338_p3 = ((xor_ln111_1_fu_1332_p2[0:0] == 1'b1) ? select_ln111_fu_1324_p3 : trunc_ln_fu_1294_p4);

assign merged_33_fu_1444_p3 = ((xor_ln111_3_fu_1438_p2[0:0] == 1'b1) ? select_ln111_2_fu_1430_p3 : trunc_ln111_1_fu_1400_p4);

assign merged_34_fu_1550_p3 = ((xor_ln111_5_fu_1544_p2[0:0] == 1'b1) ? select_ln111_4_fu_1536_p3 : trunc_ln111_2_fu_1506_p4);

assign merged_35_fu_1656_p3 = ((xor_ln111_7_fu_1650_p2[0:0] == 1'b1) ? select_ln111_6_fu_1642_p3 : trunc_ln111_3_fu_1612_p4);

assign merged_36_fu_1762_p3 = ((xor_ln111_9_fu_1756_p2[0:0] == 1'b1) ? select_ln111_8_fu_1748_p3 : trunc_ln111_4_fu_1718_p4);

assign merged_37_fu_1868_p3 = ((xor_ln111_11_fu_1862_p2[0:0] == 1'b1) ? select_ln111_10_fu_1854_p3 : trunc_ln111_5_fu_1824_p4);

assign merged_38_fu_1974_p3 = ((xor_ln111_13_fu_1968_p2[0:0] == 1'b1) ? select_ln111_12_fu_1960_p3 : trunc_ln111_6_fu_1930_p4);

assign merged_39_fu_2080_p3 = ((xor_ln111_15_fu_2074_p2[0:0] == 1'b1) ? select_ln111_14_fu_2066_p3 : trunc_ln111_7_fu_2036_p4);

assign merged_3_out = merged_3_fu_242;

assign merged_4_out = merged_4_fu_246;

assign merged_5_out = merged_5_fu_250;

assign merged_6_out = merged_6_fu_254;

assign merged_7_out = merged_7_fu_258;

assign merged_8_out = merged_8_fu_262;

assign merged_9_out = merged_9_fu_266;

assign merged_out = merged_fu_230;

assign or_ln110_1_fu_759_p4 = {{{t}, {trunc_ln103_fu_745_p1}}, {1'd0}};

assign or_ln110_2_fu_777_p4 = {{{t}, {trunc_ln103_fu_745_p1}}, {1'd1}};

assign select_ln111_10_fu_1854_p3 = ((and_ln111_5_fu_1848_p2[0:0] == 1'b1) ? 18'd131071 : 18'd131072);

assign select_ln111_12_fu_1960_p3 = ((and_ln111_6_fu_1954_p2[0:0] == 1'b1) ? 18'd131071 : 18'd131072);

assign select_ln111_14_fu_2066_p3 = ((and_ln111_7_fu_2060_p2[0:0] == 1'b1) ? 18'd131071 : 18'd131072);

assign select_ln111_2_fu_1430_p3 = ((and_ln111_1_fu_1424_p2[0:0] == 1'b1) ? 18'd131071 : 18'd131072);

assign select_ln111_4_fu_1536_p3 = ((and_ln111_2_fu_1530_p2[0:0] == 1'b1) ? 18'd131071 : 18'd131072);

assign select_ln111_6_fu_1642_p3 = ((and_ln111_3_fu_1636_p2[0:0] == 1'b1) ? 18'd131071 : 18'd131072);

assign select_ln111_8_fu_1748_p3 = ((and_ln111_4_fu_1742_p2[0:0] == 1'b1) ? 18'd131071 : 18'd131072);

assign select_ln111_fu_1324_p3 = ((and_ln111_fu_1318_p2[0:0] == 1'b1) ? 18'd131071 : 18'd131072);

assign sext_ln111_10_fu_1796_p1 = shl_ln111_10_fu_1788_p3;

assign sext_ln111_11_fu_1800_p1 = shl_ln111_s_fu_1770_p3;

assign sext_ln111_12_fu_1902_p1 = shl_ln111_12_fu_1894_p3;

assign sext_ln111_13_fu_1906_p1 = shl_ln111_11_fu_1876_p3;

assign sext_ln111_14_fu_2008_p1 = shl_ln111_14_fu_2000_p3;

assign sext_ln111_15_fu_2012_p1 = shl_ln111_13_fu_1982_p3;

assign sext_ln111_1_fu_1270_p1 = shl_ln2_fu_1246_p3;

assign sext_ln111_2_fu_1372_p1 = shl_ln111_3_fu_1364_p3;

assign sext_ln111_3_fu_1376_p1 = shl_ln111_2_fu_1346_p3;

assign sext_ln111_4_fu_1478_p1 = shl_ln111_5_fu_1470_p3;

assign sext_ln111_5_fu_1482_p1 = shl_ln111_4_fu_1452_p3;

assign sext_ln111_6_fu_1584_p1 = shl_ln111_7_fu_1576_p3;

assign sext_ln111_7_fu_1588_p1 = shl_ln111_6_fu_1558_p3;

assign sext_ln111_8_fu_1690_p1 = shl_ln111_9_fu_1682_p3;

assign sext_ln111_9_fu_1694_p1 = shl_ln111_8_fu_1664_p3;

assign sext_ln111_fu_1266_p1 = shl_ln111_1_fu_1258_p3;

assign shl_ln111_10_fu_1788_p3 = {{tmp_24_fu_1778_p4}, {10'd0}};

assign shl_ln111_11_fu_1876_p3 = {{unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_q0}, {10'd0}};

assign shl_ln111_12_fu_1894_p3 = {{tmp_25_fu_1884_p4}, {10'd0}};

assign shl_ln111_13_fu_1982_p3 = {{unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_q0}, {10'd0}};

assign shl_ln111_14_fu_2000_p3 = {{tmp_31_fu_1990_p4}, {10'd0}};

assign shl_ln111_1_fu_1258_p3 = {{trunc_ln111_fu_1254_p1}, {10'd0}};

assign shl_ln111_2_fu_1346_p3 = {{unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_q1}, {10'd0}};

assign shl_ln111_3_fu_1364_p3 = {{tmp_20_fu_1354_p4}, {10'd0}};

assign shl_ln111_4_fu_1452_p3 = {{unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_q1}, {10'd0}};

assign shl_ln111_5_fu_1470_p3 = {{tmp_21_fu_1460_p4}, {10'd0}};

assign shl_ln111_6_fu_1558_p3 = {{unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_q1}, {10'd0}};

assign shl_ln111_7_fu_1576_p3 = {{tmp_22_fu_1566_p4}, {10'd0}};

assign shl_ln111_8_fu_1664_p3 = {{unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_q0}, {10'd0}};

assign shl_ln111_9_fu_1682_p3 = {{tmp_23_fu_1672_p4}, {10'd0}};

assign shl_ln111_s_fu_1770_p3 = {{unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_q0}, {10'd0}};

assign shl_ln2_fu_1246_p3 = {{unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_q1}, {10'd0}};

assign tmp_20_fu_1354_p4 = {{ap_phi_mux_p_in_phi_fu_715_p8[49:32]}};

assign tmp_21_fu_1460_p4 = {{ap_phi_mux_p_in_phi_fu_715_p8[81:64]}};

assign tmp_22_fu_1566_p4 = {{ap_phi_mux_p_in_phi_fu_715_p8[113:96]}};

assign tmp_23_fu_1672_p4 = {{ap_phi_mux_p_in_phi_fu_715_p8[145:128]}};

assign tmp_24_fu_1778_p4 = {{ap_phi_mux_p_in_phi_fu_715_p8[177:160]}};

assign tmp_25_fu_1884_p4 = {{ap_phi_mux_p_in_phi_fu_715_p8[209:192]}};

assign tmp_26_fu_1211_p16 = {{{{{{{{{{{{{{{trunc_ln105_7_fu_1201_p4}, {14'd0}}, {trunc_ln105_6_fu_1191_p4}}, {14'd0}}, {trunc_ln105_5_fu_1181_p4}}, {14'd0}}, {trunc_ln105_4_fu_1171_p4}}, {14'd0}}, {trunc_ln105_3_fu_1161_p4}}, {14'd0}}, {trunc_ln105_2_fu_1151_p4}}, {14'd0}}, {trunc_ln105_1_fu_1141_p4}}, {14'd0}}, {trunc_ln105_fu_1137_p1}};

assign tmp_27_fu_1102_p16 = {{{{{{{{{{{{{{{trunc_ln105_13_fu_1092_p4}, {14'd0}}, {trunc_ln105_12_fu_1082_p4}}, {14'd0}}, {trunc_ln105_11_fu_1072_p4}}, {14'd0}}, {trunc_ln105_10_fu_1062_p4}}, {14'd0}}, {trunc_ln105_s_fu_1052_p4}}, {14'd0}}, {trunc_ln105_9_fu_1042_p4}}, {14'd0}}, {trunc_ln105_8_fu_1032_p4}}, {14'd0}}, {trunc_ln105_15_fu_1028_p1}};

assign tmp_28_fu_993_p16 = {{{{{{{{{{{{{{{trunc_ln105_21_fu_983_p4}, {14'd0}}, {trunc_ln105_20_fu_973_p4}}, {14'd0}}, {trunc_ln105_19_fu_963_p4}}, {14'd0}}, {trunc_ln105_18_fu_953_p4}}, {14'd0}}, {trunc_ln105_17_fu_943_p4}}, {14'd0}}, {trunc_ln105_16_fu_933_p4}}, {14'd0}}, {trunc_ln105_14_fu_923_p4}}, {14'd0}}, {trunc_ln105_23_fu_919_p1}};

assign tmp_294_fu_1304_p3 = add_ln111_8_fu_1274_p2[32'd27];

assign tmp_295_fu_1392_p3 = add_ln111_1_fu_1386_p2[32'd28];

assign tmp_296_fu_1410_p3 = add_ln111_9_fu_1380_p2[32'd27];

assign tmp_297_fu_1498_p3 = add_ln111_2_fu_1492_p2[32'd28];

assign tmp_298_fu_1516_p3 = add_ln111_10_fu_1486_p2[32'd27];

assign tmp_299_fu_1604_p3 = add_ln111_3_fu_1598_p2[32'd28];

assign tmp_29_fu_884_p16 = {{{{{{{{{{{{{{{trunc_ln105_29_fu_874_p4}, {14'd0}}, {trunc_ln105_28_fu_864_p4}}, {14'd0}}, {trunc_ln105_27_fu_854_p4}}, {14'd0}}, {trunc_ln105_26_fu_844_p4}}, {14'd0}}, {trunc_ln105_25_fu_834_p4}}, {14'd0}}, {trunc_ln105_24_fu_824_p4}}, {14'd0}}, {trunc_ln105_22_fu_814_p4}}, {14'd0}}, {trunc_ln105_31_fu_810_p1}};

assign tmp_300_fu_1622_p3 = add_ln111_11_fu_1592_p2[32'd27];

assign tmp_301_fu_1710_p3 = add_ln111_4_fu_1704_p2[32'd28];

assign tmp_302_fu_1728_p3 = add_ln111_12_fu_1698_p2[32'd27];

assign tmp_303_fu_1816_p3 = add_ln111_5_fu_1810_p2[32'd28];

assign tmp_304_fu_1834_p3 = add_ln111_13_fu_1804_p2[32'd27];

assign tmp_305_fu_1922_p3 = add_ln111_6_fu_1916_p2[32'd28];

assign tmp_306_fu_1940_p3 = add_ln111_14_fu_1910_p2[32'd27];

assign tmp_307_fu_2028_p3 = add_ln111_7_fu_2022_p2[32'd28];

assign tmp_308_fu_2046_p3 = add_ln111_15_fu_2016_p2[32'd27];

assign tmp_31_fu_1990_p4 = {{ap_phi_mux_p_in_phi_fu_715_p8[241:224]}};

assign tmp_fu_1286_p3 = add_ln111_fu_1280_p2[32'd28];

assign trunc_ln103_fu_745_p1 = ap_sig_allocacmp_chunk_2[1:0];

assign trunc_ln105_10_fu_1062_p4 = {{mamba_out_0_dout[89:72]}};

assign trunc_ln105_11_fu_1072_p4 = {{mamba_out_0_dout[107:90]}};

assign trunc_ln105_12_fu_1082_p4 = {{mamba_out_0_dout[125:108]}};

assign trunc_ln105_13_fu_1092_p4 = {{mamba_out_0_dout[143:126]}};

assign trunc_ln105_14_fu_923_p4 = {{mamba_out_1_dout[35:18]}};

assign trunc_ln105_15_fu_1028_p1 = mamba_out_0_dout[17:0];

assign trunc_ln105_16_fu_933_p4 = {{mamba_out_1_dout[53:36]}};

assign trunc_ln105_17_fu_943_p4 = {{mamba_out_1_dout[71:54]}};

assign trunc_ln105_18_fu_953_p4 = {{mamba_out_1_dout[89:72]}};

assign trunc_ln105_19_fu_963_p4 = {{mamba_out_1_dout[107:90]}};

assign trunc_ln105_1_fu_1141_p4 = {{mamba_out_3_dout[35:18]}};

assign trunc_ln105_20_fu_973_p4 = {{mamba_out_1_dout[125:108]}};

assign trunc_ln105_21_fu_983_p4 = {{mamba_out_1_dout[143:126]}};

assign trunc_ln105_22_fu_814_p4 = {{mamba_out_2_dout[35:18]}};

assign trunc_ln105_23_fu_919_p1 = mamba_out_1_dout[17:0];

assign trunc_ln105_24_fu_824_p4 = {{mamba_out_2_dout[53:36]}};

assign trunc_ln105_25_fu_834_p4 = {{mamba_out_2_dout[71:54]}};

assign trunc_ln105_26_fu_844_p4 = {{mamba_out_2_dout[89:72]}};

assign trunc_ln105_27_fu_854_p4 = {{mamba_out_2_dout[107:90]}};

assign trunc_ln105_28_fu_864_p4 = {{mamba_out_2_dout[125:108]}};

assign trunc_ln105_29_fu_874_p4 = {{mamba_out_2_dout[143:126]}};

assign trunc_ln105_2_fu_1151_p4 = {{mamba_out_3_dout[53:36]}};

assign trunc_ln105_31_fu_810_p1 = mamba_out_2_dout[17:0];

assign trunc_ln105_3_fu_1161_p4 = {{mamba_out_3_dout[71:54]}};

assign trunc_ln105_4_fu_1171_p4 = {{mamba_out_3_dout[89:72]}};

assign trunc_ln105_5_fu_1181_p4 = {{mamba_out_3_dout[107:90]}};

assign trunc_ln105_6_fu_1191_p4 = {{mamba_out_3_dout[125:108]}};

assign trunc_ln105_7_fu_1201_p4 = {{mamba_out_3_dout[143:126]}};

assign trunc_ln105_8_fu_1032_p4 = {{mamba_out_0_dout[35:18]}};

assign trunc_ln105_9_fu_1042_p4 = {{mamba_out_0_dout[53:36]}};

assign trunc_ln105_fu_1137_p1 = mamba_out_3_dout[17:0];

assign trunc_ln105_s_fu_1052_p4 = {{mamba_out_0_dout[71:54]}};

assign trunc_ln111_1_fu_1400_p4 = {{add_ln111_9_fu_1380_p2[27:10]}};

assign trunc_ln111_2_fu_1506_p4 = {{add_ln111_10_fu_1486_p2[27:10]}};

assign trunc_ln111_3_fu_1612_p4 = {{add_ln111_11_fu_1592_p2[27:10]}};

assign trunc_ln111_4_fu_1718_p4 = {{add_ln111_12_fu_1698_p2[27:10]}};

assign trunc_ln111_5_fu_1824_p4 = {{add_ln111_13_fu_1804_p2[27:10]}};

assign trunc_ln111_6_fu_1930_p4 = {{add_ln111_14_fu_1910_p2[27:10]}};

assign trunc_ln111_7_fu_2036_p4 = {{add_ln111_15_fu_2016_p2[27:10]}};

assign trunc_ln111_fu_1254_p1 = ap_phi_mux_p_in_phi_fu_715_p8[17:0];

assign trunc_ln_fu_1294_p4 = {{add_ln111_8_fu_1274_p2[27:10]}};

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_address0 = zext_ln110_1_fu_787_p1;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_address1 = zext_ln110_fu_769_p1;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_ce0 = unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_ce0_local;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_ce1 = unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_1_ce1_local;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_address0 = zext_ln110_1_fu_787_p1;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_address1 = zext_ln110_fu_769_p1;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_ce0 = unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_ce0_local;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_ce1 = unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_2_ce1_local;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_address0 = zext_ln110_1_fu_787_p1;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_address1 = zext_ln110_fu_769_p1;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_ce0 = unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_ce0_local;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_ce1 = unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_3_ce1_local;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_address0 = zext_ln110_1_fu_787_p1;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_address1 = zext_ln110_fu_769_p1;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_ce0 = unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_ce0_local;

assign unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_ce1 = unet_pvm_top_ap_fixed_ap_fixed_ap_fixed_18_8_0_0_0_enc4_out_ce1_local;

assign xor_ln111_10_fu_1842_p2 = (tmp_303_fu_1816_p3 ^ 1'd1);

assign xor_ln111_11_fu_1862_p2 = (tmp_304_fu_1834_p3 ^ tmp_303_fu_1816_p3);

assign xor_ln111_12_fu_1948_p2 = (tmp_305_fu_1922_p3 ^ 1'd1);

assign xor_ln111_13_fu_1968_p2 = (tmp_306_fu_1940_p3 ^ tmp_305_fu_1922_p3);

assign xor_ln111_14_fu_2054_p2 = (tmp_307_fu_2028_p3 ^ 1'd1);

assign xor_ln111_15_fu_2074_p2 = (tmp_308_fu_2046_p3 ^ tmp_307_fu_2028_p3);

assign xor_ln111_1_fu_1332_p2 = (tmp_fu_1286_p3 ^ tmp_294_fu_1304_p3);

assign xor_ln111_2_fu_1418_p2 = (tmp_295_fu_1392_p3 ^ 1'd1);

assign xor_ln111_3_fu_1438_p2 = (tmp_296_fu_1410_p3 ^ tmp_295_fu_1392_p3);

assign xor_ln111_4_fu_1524_p2 = (tmp_297_fu_1498_p3 ^ 1'd1);

assign xor_ln111_5_fu_1544_p2 = (tmp_298_fu_1516_p3 ^ tmp_297_fu_1498_p3);

assign xor_ln111_6_fu_1630_p2 = (tmp_299_fu_1604_p3 ^ 1'd1);

assign xor_ln111_7_fu_1650_p2 = (tmp_300_fu_1622_p3 ^ tmp_299_fu_1604_p3);

assign xor_ln111_8_fu_1736_p2 = (tmp_301_fu_1710_p3 ^ 1'd1);

assign xor_ln111_9_fu_1756_p2 = (tmp_302_fu_1728_p3 ^ tmp_301_fu_1710_p3);

assign xor_ln111_fu_1312_p2 = (tmp_fu_1286_p3 ^ 1'd1);

assign zext_ln110_1_fu_787_p1 = or_ln110_2_fu_777_p4;

assign zext_ln110_fu_769_p1 = or_ln110_1_fu_759_p4;

endmodule //unet_pvm_top_pvm_merge_and_project_config_enc5_Pipeline_VITIS_LOOP_103_4
