// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module unet_pvm_top_pvm_merge_and_project_config_enc5_Pipeline_VITIS_LOOP_125_7 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        merged_reload,
        merged_1_reload,
        merged_2_reload,
        merged_3_reload,
        merged_4_reload,
        merged_5_reload,
        merged_6_reload,
        merged_7_reload,
        merged_8_reload,
        merged_9_reload,
        merged_10_reload,
        merged_11_reload,
        merged_12_reload,
        merged_13_reload,
        merged_14_reload,
        merged_15_reload,
        merged_16_reload,
        merged_17_reload,
        merged_18_reload,
        merged_19_reload,
        merged_20_reload,
        merged_21_reload,
        merged_22_reload,
        merged_23_reload,
        merged_24_reload,
        merged_25_reload,
        merged_26_reload,
        merged_27_reload,
        merged_28_reload,
        merged_29_reload,
        merged_30_reload,
        merged_31_reload,
        conv_i_i16_i739,
        var_5_out,
        var_5_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [17:0] merged_reload;
input  [17:0] merged_1_reload;
input  [17:0] merged_2_reload;
input  [17:0] merged_3_reload;
input  [17:0] merged_4_reload;
input  [17:0] merged_5_reload;
input  [17:0] merged_6_reload;
input  [17:0] merged_7_reload;
input  [17:0] merged_8_reload;
input  [17:0] merged_9_reload;
input  [17:0] merged_10_reload;
input  [17:0] merged_11_reload;
input  [17:0] merged_12_reload;
input  [17:0] merged_13_reload;
input  [17:0] merged_14_reload;
input  [17:0] merged_15_reload;
input  [17:0] merged_16_reload;
input  [17:0] merged_17_reload;
input  [17:0] merged_18_reload;
input  [17:0] merged_19_reload;
input  [17:0] merged_20_reload;
input  [17:0] merged_21_reload;
input  [17:0] merged_22_reload;
input  [17:0] merged_23_reload;
input  [17:0] merged_24_reload;
input  [17:0] merged_25_reload;
input  [17:0] merged_26_reload;
input  [17:0] merged_27_reload;
input  [17:0] merged_28_reload;
input  [17:0] merged_29_reload;
input  [17:0] merged_30_reload;
input  [17:0] merged_31_reload;
input  [17:0] conv_i_i16_i739;
output  [17:0] var_5_out;
output   var_5_out_ap_vld;

reg ap_idle;
reg var_5_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln125_fu_438_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln125_reg_925;
wire   [17:0] diff_2_fu_646_p3;
reg   [17:0] diff_2_reg_929;
wire   [35:0] mul_ln128_fu_662_p2;
reg   [35:0] mul_ln128_reg_934;
reg   [0:0] tmp_289_reg_939;
reg   [17:0] var_fu_208;
wire   [17:0] var_6_fu_893_p3;
wire    ap_block_pp0_stage0;
wire    ap_loop_init;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [5:0] c_2_fu_212;
wire   [5:0] add_ln125_fu_444_p2;
reg   [5:0] ap_sig_allocacmp_c;
wire    ap_block_pp0_stage0_01001;
wire   [17:0] tmp_124_fu_454_p65;
wire   [4:0] tmp_124_fu_454_p66;
wire   [17:0] tmp_124_fu_454_p67;
wire  signed [18:0] sext_ln127_fu_590_p1;
wire  signed [18:0] conv_i_i16_i739_cast_fu_421_p1;
wire   [18:0] sub_ln127_fu_594_p2;
wire   [0:0] tmp_fu_600_p3;
wire   [0:0] tmp_287_fu_612_p3;
wire   [0:0] xor_ln127_fu_620_p2;
wire   [0:0] and_ln127_fu_626_p2;
wire   [0:0] xor_ln127_1_fu_632_p2;
wire   [17:0] select_ln127_fu_638_p3;
wire   [17:0] diff_fu_608_p1;
wire  signed [17:0] mul_ln128_fu_662_p0;
wire  signed [35:0] sext_ln128_fu_659_p1;
wire  signed [17:0] mul_ln128_fu_662_p1;
wire   [27:0] shl_ln3_fu_679_p3;
wire  signed [35:0] sext_ln128_1_fu_687_p1;
wire   [35:0] add_ln128_fu_691_p2;
wire   [17:0] var_4_fu_704_p4;
wire   [17:0] zext_ln128_fu_722_p1;
wire   [17:0] var_5_fu_725_p2;
wire   [0:0] tmp_291_fu_731_p3;
wire   [0:0] tmp_290_fu_714_p3;
wire   [0:0] xor_ln128_fu_739_p2;
wire   [6:0] tmp_136_fu_759_p4;
wire   [7:0] tmp_137_fu_775_p4;
wire   [0:0] and_ln128_fu_745_p2;
wire   [0:0] icmp_ln128_1_fu_785_p2;
wire   [0:0] icmp_ln128_2_fu_791_p2;
wire   [0:0] tmp_292_fu_751_p3;
wire   [0:0] icmp_ln128_fu_769_p2;
wire   [0:0] xor_ln128_1_fu_805_p2;
wire   [0:0] and_ln128_1_fu_811_p2;
wire   [0:0] select_ln128_fu_797_p3;
wire   [0:0] xor_ln128_2_fu_831_p2;
wire   [0:0] tmp_288_fu_696_p3;
wire   [0:0] or_ln128_fu_837_p2;
wire   [0:0] xor_ln128_3_fu_843_p2;
wire   [0:0] select_ln128_1_fu_817_p3;
wire   [0:0] and_ln128_2_fu_825_p2;
wire   [0:0] and_ln128_4_fu_855_p2;
wire   [0:0] or_ln128_2_fu_861_p2;
wire   [0:0] xor_ln128_4_fu_867_p2;
wire   [0:0] and_ln128_3_fu_849_p2;
wire   [0:0] and_ln128_5_fu_873_p2;
wire   [0:0] or_ln128_1_fu_887_p2;
wire   [17:0] select_ln128_2_fu_879_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [4:0] tmp_124_fu_454_p1;
wire   [4:0] tmp_124_fu_454_p3;
wire   [4:0] tmp_124_fu_454_p5;
wire   [4:0] tmp_124_fu_454_p7;
wire   [4:0] tmp_124_fu_454_p9;
wire   [4:0] tmp_124_fu_454_p11;
wire   [4:0] tmp_124_fu_454_p13;
wire   [4:0] tmp_124_fu_454_p15;
wire   [4:0] tmp_124_fu_454_p17;
wire   [4:0] tmp_124_fu_454_p19;
wire   [4:0] tmp_124_fu_454_p21;
wire   [4:0] tmp_124_fu_454_p23;
wire   [4:0] tmp_124_fu_454_p25;
wire   [4:0] tmp_124_fu_454_p27;
wire   [4:0] tmp_124_fu_454_p29;
wire   [4:0] tmp_124_fu_454_p31;
wire  signed [4:0] tmp_124_fu_454_p33;
wire  signed [4:0] tmp_124_fu_454_p35;
wire  signed [4:0] tmp_124_fu_454_p37;
wire  signed [4:0] tmp_124_fu_454_p39;
wire  signed [4:0] tmp_124_fu_454_p41;
wire  signed [4:0] tmp_124_fu_454_p43;
wire  signed [4:0] tmp_124_fu_454_p45;
wire  signed [4:0] tmp_124_fu_454_p47;
wire  signed [4:0] tmp_124_fu_454_p49;
wire  signed [4:0] tmp_124_fu_454_p51;
wire  signed [4:0] tmp_124_fu_454_p53;
wire  signed [4:0] tmp_124_fu_454_p55;
wire  signed [4:0] tmp_124_fu_454_p57;
wire  signed [4:0] tmp_124_fu_454_p59;
wire  signed [4:0] tmp_124_fu_454_p61;
wire  signed [4:0] tmp_124_fu_454_p63;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 var_fu_208 = 18'd0;
#0 c_2_fu_212 = 6'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) unet_pvm_top_sparsemux_65_5_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 5'h0 ),
    .din0_WIDTH( 18 ),
    .CASE1( 5'h1 ),
    .din1_WIDTH( 18 ),
    .CASE2( 5'h2 ),
    .din2_WIDTH( 18 ),
    .CASE3( 5'h3 ),
    .din3_WIDTH( 18 ),
    .CASE4( 5'h4 ),
    .din4_WIDTH( 18 ),
    .CASE5( 5'h5 ),
    .din5_WIDTH( 18 ),
    .CASE6( 5'h6 ),
    .din6_WIDTH( 18 ),
    .CASE7( 5'h7 ),
    .din7_WIDTH( 18 ),
    .CASE8( 5'h8 ),
    .din8_WIDTH( 18 ),
    .CASE9( 5'h9 ),
    .din9_WIDTH( 18 ),
    .CASE10( 5'hA ),
    .din10_WIDTH( 18 ),
    .CASE11( 5'hB ),
    .din11_WIDTH( 18 ),
    .CASE12( 5'hC ),
    .din12_WIDTH( 18 ),
    .CASE13( 5'hD ),
    .din13_WIDTH( 18 ),
    .CASE14( 5'hE ),
    .din14_WIDTH( 18 ),
    .CASE15( 5'hF ),
    .din15_WIDTH( 18 ),
    .CASE16( 5'h10 ),
    .din16_WIDTH( 18 ),
    .CASE17( 5'h11 ),
    .din17_WIDTH( 18 ),
    .CASE18( 5'h12 ),
    .din18_WIDTH( 18 ),
    .CASE19( 5'h13 ),
    .din19_WIDTH( 18 ),
    .CASE20( 5'h14 ),
    .din20_WIDTH( 18 ),
    .CASE21( 5'h15 ),
    .din21_WIDTH( 18 ),
    .CASE22( 5'h16 ),
    .din22_WIDTH( 18 ),
    .CASE23( 5'h17 ),
    .din23_WIDTH( 18 ),
    .CASE24( 5'h18 ),
    .din24_WIDTH( 18 ),
    .CASE25( 5'h19 ),
    .din25_WIDTH( 18 ),
    .CASE26( 5'h1A ),
    .din26_WIDTH( 18 ),
    .CASE27( 5'h1B ),
    .din27_WIDTH( 18 ),
    .CASE28( 5'h1C ),
    .din28_WIDTH( 18 ),
    .CASE29( 5'h1D ),
    .din29_WIDTH( 18 ),
    .CASE30( 5'h1E ),
    .din30_WIDTH( 18 ),
    .CASE31( 5'h1F ),
    .din31_WIDTH( 18 ),
    .def_WIDTH( 18 ),
    .sel_WIDTH( 5 ),
    .dout_WIDTH( 18 ))
sparsemux_65_5_18_1_1_U891(
    .din0(merged_reload),
    .din1(merged_1_reload),
    .din2(merged_2_reload),
    .din3(merged_3_reload),
    .din4(merged_4_reload),
    .din5(merged_5_reload),
    .din6(merged_6_reload),
    .din7(merged_7_reload),
    .din8(merged_8_reload),
    .din9(merged_9_reload),
    .din10(merged_10_reload),
    .din11(merged_11_reload),
    .din12(merged_12_reload),
    .din13(merged_13_reload),
    .din14(merged_14_reload),
    .din15(merged_15_reload),
    .din16(merged_16_reload),
    .din17(merged_17_reload),
    .din18(merged_18_reload),
    .din19(merged_19_reload),
    .din20(merged_20_reload),
    .din21(merged_21_reload),
    .din22(merged_22_reload),
    .din23(merged_23_reload),
    .din24(merged_24_reload),
    .din25(merged_25_reload),
    .din26(merged_26_reload),
    .din27(merged_27_reload),
    .din28(merged_28_reload),
    .din29(merged_29_reload),
    .din30(merged_30_reload),
    .din31(merged_31_reload),
    .def(tmp_124_fu_454_p65),
    .sel(tmp_124_fu_454_p66),
    .dout(tmp_124_fu_454_p67)
);

unet_pvm_top_mul_18s_18s_36_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 36 ))
mul_18s_18s_36_1_1_U892(
    .din0(mul_ln128_fu_662_p0),
    .din1(mul_ln128_fu_662_p1),
    .dout(mul_ln128_fu_662_p2)
);

unet_pvm_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln125_fu_438_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            c_2_fu_212 <= add_ln125_fu_444_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            c_2_fu_212 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            var_fu_208 <= 18'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            var_fu_208 <= var_6_fu_893_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        diff_2_reg_929 <= diff_2_fu_646_p3;
        icmp_ln125_reg_925 <= icmp_ln125_fu_438_p2;
        mul_ln128_reg_934 <= mul_ln128_fu_662_p2;
        tmp_289_reg_939 <= mul_ln128_fu_662_p2[32'd9];
    end
end

always @ (*) begin
    if (((icmp_ln125_fu_438_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_c = 6'd0;
    end else begin
        ap_sig_allocacmp_c = c_2_fu_212;
    end
end

always @ (*) begin
    if (((icmp_ln125_reg_925 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        var_5_out_ap_vld = 1'b1;
    end else begin
        var_5_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln125_fu_444_p2 = (ap_sig_allocacmp_c + 6'd1);

assign add_ln128_fu_691_p2 = ($signed(mul_ln128_reg_934) + $signed(sext_ln128_1_fu_687_p1));

assign and_ln127_fu_626_p2 = (xor_ln127_fu_620_p2 & tmp_287_fu_612_p3);

assign and_ln128_1_fu_811_p2 = (xor_ln128_1_fu_805_p2 & icmp_ln128_fu_769_p2);

assign and_ln128_2_fu_825_p2 = (icmp_ln128_1_fu_785_p2 & and_ln128_fu_745_p2);

assign and_ln128_3_fu_849_p2 = (xor_ln128_3_fu_843_p2 & or_ln128_fu_837_p2);

assign and_ln128_4_fu_855_p2 = (tmp_291_fu_731_p3 & select_ln128_1_fu_817_p3);

assign and_ln128_5_fu_873_p2 = (xor_ln128_4_fu_867_p2 & tmp_288_fu_696_p3);

assign and_ln128_fu_745_p2 = (xor_ln128_fu_739_p2 & tmp_290_fu_714_p3);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign conv_i_i16_i739_cast_fu_421_p1 = $signed(conv_i_i16_i739);

assign diff_2_fu_646_p3 = ((xor_ln127_1_fu_632_p2[0:0] == 1'b1) ? select_ln127_fu_638_p3 : diff_fu_608_p1);

assign diff_fu_608_p1 = sub_ln127_fu_594_p2[17:0];

assign icmp_ln125_fu_438_p2 = ((ap_sig_allocacmp_c == 6'd32) ? 1'b1 : 1'b0);

assign icmp_ln128_1_fu_785_p2 = ((tmp_137_fu_775_p4 == 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln128_2_fu_791_p2 = ((tmp_137_fu_775_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln128_fu_769_p2 = ((tmp_136_fu_759_p4 == 7'd127) ? 1'b1 : 1'b0);

assign mul_ln128_fu_662_p0 = sext_ln128_fu_659_p1;

assign mul_ln128_fu_662_p1 = sext_ln128_fu_659_p1;

assign or_ln128_1_fu_887_p2 = (and_ln128_5_fu_873_p2 | and_ln128_3_fu_849_p2);

assign or_ln128_2_fu_861_p2 = (and_ln128_4_fu_855_p2 | and_ln128_2_fu_825_p2);

assign or_ln128_fu_837_p2 = (xor_ln128_2_fu_831_p2 | tmp_291_fu_731_p3);

assign select_ln127_fu_638_p3 = ((and_ln127_fu_626_p2[0:0] == 1'b1) ? 18'd131071 : 18'd131072);

assign select_ln128_1_fu_817_p3 = ((and_ln128_fu_745_p2[0:0] == 1'b1) ? and_ln128_1_fu_811_p2 : icmp_ln128_1_fu_785_p2);

assign select_ln128_2_fu_879_p3 = ((and_ln128_3_fu_849_p2[0:0] == 1'b1) ? 18'd131071 : 18'd131072);

assign select_ln128_fu_797_p3 = ((and_ln128_fu_745_p2[0:0] == 1'b1) ? icmp_ln128_1_fu_785_p2 : icmp_ln128_2_fu_791_p2);

assign sext_ln127_fu_590_p1 = $signed(tmp_124_fu_454_p67);

assign sext_ln128_1_fu_687_p1 = $signed(shl_ln3_fu_679_p3);

assign sext_ln128_fu_659_p1 = $signed(diff_2_reg_929);

assign shl_ln3_fu_679_p3 = {{var_fu_208}, {10'd0}};

assign sub_ln127_fu_594_p2 = ($signed(sext_ln127_fu_590_p1) - $signed(conv_i_i16_i739_cast_fu_421_p1));

assign tmp_124_fu_454_p65 = 'bx;

assign tmp_124_fu_454_p66 = ap_sig_allocacmp_c[4:0];

assign tmp_136_fu_759_p4 = {{add_ln128_fu_691_p2[35:29]}};

assign tmp_137_fu_775_p4 = {{add_ln128_fu_691_p2[35:28]}};

assign tmp_287_fu_612_p3 = sub_ln127_fu_594_p2[32'd17];

assign tmp_288_fu_696_p3 = add_ln128_fu_691_p2[32'd35];

assign tmp_290_fu_714_p3 = add_ln128_fu_691_p2[32'd27];

assign tmp_291_fu_731_p3 = var_5_fu_725_p2[32'd17];

assign tmp_292_fu_751_p3 = add_ln128_fu_691_p2[32'd28];

assign tmp_fu_600_p3 = sub_ln127_fu_594_p2[32'd18];

assign var_4_fu_704_p4 = {{add_ln128_fu_691_p2[27:10]}};

assign var_5_fu_725_p2 = (var_4_fu_704_p4 + zext_ln128_fu_722_p1);

assign var_5_out = var_fu_208;

assign var_6_fu_893_p3 = ((or_ln128_1_fu_887_p2[0:0] == 1'b1) ? select_ln128_2_fu_879_p3 : var_5_fu_725_p2);

assign xor_ln127_1_fu_632_p2 = (tmp_fu_600_p3 ^ tmp_287_fu_612_p3);

assign xor_ln127_fu_620_p2 = (tmp_fu_600_p3 ^ 1'd1);

assign xor_ln128_1_fu_805_p2 = (tmp_292_fu_751_p3 ^ 1'd1);

assign xor_ln128_2_fu_831_p2 = (select_ln128_fu_797_p3 ^ 1'd1);

assign xor_ln128_3_fu_843_p2 = (tmp_288_fu_696_p3 ^ 1'd1);

assign xor_ln128_4_fu_867_p2 = (or_ln128_2_fu_861_p2 ^ 1'd1);

assign xor_ln128_fu_739_p2 = (tmp_291_fu_731_p3 ^ 1'd1);

assign zext_ln128_fu_722_p1 = tmp_289_reg_939;

endmodule //unet_pvm_top_pvm_merge_and_project_config_enc5_Pipeline_VITIS_LOOP_125_7
