// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module unet_pvm_top_forward_20_Pipeline_VITIS_LOOP_32_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_vec_address0,
        in_vec_ce0,
        in_vec_q0,
        sum_sq_out,
        sum_sq_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [4:0] in_vec_address0;
output   in_vec_ce0;
input  [17:0] in_vec_q0;
output  [17:0] sum_sq_out;
output   sum_sq_out_ap_vld;

reg ap_idle;
reg sum_sq_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln32_fu_133_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln32_reg_468;
wire   [0:0] icmp_ln35_fu_160_p2;
reg   [0:0] icmp_ln35_reg_472;
reg   [0:0] icmp_ln35_reg_472_pp0_iter1_reg;
wire   [35:0] mul_ln35_fu_175_p2;
reg   [35:0] mul_ln35_reg_483;
reg   [0:0] tmp_477_reg_488;
wire   [63:0] zext_ln32_fu_145_p1;
wire    ap_block_pp0_stage0;
reg   [17:0] sum_sq_fu_92;
wire   [17:0] sum_sq_4_fu_424_p9;
wire    ap_loop_init;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [5:0] d_fu_96;
wire   [5:0] add_ln32_fu_139_p2;
reg   [5:0] ap_sig_allocacmp_d_4;
wire    ap_block_pp0_stage0_01001;
reg    in_vec_ce0_local;
wire   [2:0] tmp_fu_150_p4;
wire  signed [17:0] mul_ln35_fu_175_p0;
wire  signed [35:0] sext_ln35_fu_171_p1;
wire  signed [17:0] mul_ln35_fu_175_p1;
wire   [27:0] shl_ln8_fu_192_p3;
wire  signed [35:0] sext_ln35_2_fu_200_p1;
wire   [35:0] add_ln35_fu_204_p2;
wire   [17:0] sum_sq_5_fu_217_p4;
wire   [17:0] zext_ln35_fu_235_p1;
wire   [17:0] sum_sq_6_fu_238_p2;
wire   [0:0] tmp_479_fu_244_p3;
wire   [0:0] tmp_478_fu_227_p3;
wire   [0:0] xor_ln35_fu_252_p2;
wire   [6:0] tmp_s_fu_272_p4;
wire   [7:0] tmp_334_fu_288_p4;
wire   [0:0] and_ln35_fu_258_p2;
wire   [0:0] icmp_ln35_5_fu_298_p2;
wire   [0:0] icmp_ln35_6_fu_304_p2;
wire   [0:0] tmp_480_fu_264_p3;
wire   [0:0] icmp_ln35_4_fu_282_p2;
wire   [0:0] xor_ln35_6_fu_318_p2;
wire   [0:0] and_ln35_7_fu_324_p2;
wire   [0:0] select_ln35_fu_310_p3;
wire   [0:0] xor_ln35_7_fu_344_p2;
wire   [0:0] tmp_476_fu_209_p3;
wire   [0:0] or_ln35_fu_350_p2;
wire   [0:0] xor_ln35_8_fu_356_p2;
wire   [0:0] select_ln35_3_fu_330_p3;
wire   [0:0] and_ln35_8_fu_338_p2;
wire   [0:0] and_ln35_10_fu_368_p2;
wire   [0:0] or_ln35_3_fu_374_p2;
wire   [0:0] xor_ln35_9_fu_380_p2;
wire   [0:0] and_ln35_11_fu_386_p2;
wire   [0:0] and_ln35_9_fu_362_p2;
wire   [0:0] or_ln35_2_fu_392_p2;
wire   [0:0] and_ln35_12_fu_406_p2;
wire   [0:0] xor_ln35_10_fu_411_p2;
wire   [17:0] sum_sq_4_fu_424_p2;
wire   [17:0] sum_sq_4_fu_424_p7;
wire   [1:0] sum_sq_4_fu_424_p8;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire  signed [1:0] sum_sq_4_fu_424_p1;
wire   [1:0] sum_sq_4_fu_424_p3;
wire   [1:0] sum_sq_4_fu_424_p5;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 sum_sq_fu_92 = 18'd0;
#0 d_fu_96 = 6'd0;
#0 ap_done_reg = 1'b0;
end

unet_pvm_top_mul_18s_18s_36_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 36 ))
mul_18s_18s_36_1_1_U484(
    .din0(mul_ln35_fu_175_p0),
    .din1(mul_ln35_fu_175_p1),
    .dout(mul_ln35_fu_175_p2)
);

(* dissolve_hierarchy = "yes" *) unet_pvm_top_sparsemux_7_2_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 18 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 18 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 18 ),
    .def_WIDTH( 18 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 18 ))
sparsemux_7_2_18_1_1_U485(
    .din0(sum_sq_4_fu_424_p2),
    .din1(sum_sq_fu_92),
    .din2(sum_sq_6_fu_238_p2),
    .def(sum_sq_4_fu_424_p7),
    .sel(sum_sq_4_fu_424_p8),
    .dout(sum_sq_4_fu_424_p9)
);

unet_pvm_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln32_fu_133_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            d_fu_96 <= add_ln32_fu_139_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            d_fu_96 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            sum_sq_fu_92 <= 18'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            sum_sq_fu_92 <= sum_sq_4_fu_424_p9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln32_reg_468 <= icmp_ln32_fu_133_p2;
        icmp_ln35_reg_472 <= icmp_ln35_fu_160_p2;
        icmp_ln35_reg_472_pp0_iter1_reg <= icmp_ln35_reg_472;
        mul_ln35_reg_483 <= mul_ln35_fu_175_p2;
        tmp_477_reg_488 <= mul_ln35_fu_175_p2[32'd9];
    end
end

always @ (*) begin
    if (((icmp_ln32_fu_133_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_d_4 = 6'd0;
    end else begin
        ap_sig_allocacmp_d_4 = d_fu_96;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_vec_ce0_local = 1'b1;
    end else begin
        in_vec_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln32_reg_468 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sum_sq_out_ap_vld = 1'b1;
    end else begin
        sum_sq_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln32_fu_139_p2 = (ap_sig_allocacmp_d_4 + 6'd1);

assign add_ln35_fu_204_p2 = ($signed(mul_ln35_reg_483) + $signed(sext_ln35_2_fu_200_p1));

assign and_ln35_10_fu_368_p2 = (tmp_479_fu_244_p3 & select_ln35_3_fu_330_p3);

assign and_ln35_11_fu_386_p2 = (xor_ln35_9_fu_380_p2 & tmp_476_fu_209_p3);

assign and_ln35_12_fu_406_p2 = (or_ln35_2_fu_392_p2 & icmp_ln35_reg_472_pp0_iter1_reg);

assign and_ln35_7_fu_324_p2 = (xor_ln35_6_fu_318_p2 & icmp_ln35_4_fu_282_p2);

assign and_ln35_8_fu_338_p2 = (icmp_ln35_5_fu_298_p2 & and_ln35_fu_258_p2);

assign and_ln35_9_fu_362_p2 = (xor_ln35_8_fu_356_p2 & or_ln35_fu_350_p2);

assign and_ln35_fu_258_p2 = (xor_ln35_fu_252_p2 & tmp_478_fu_227_p3);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln32_fu_133_p2 = ((ap_sig_allocacmp_d_4 == 6'd32) ? 1'b1 : 1'b0);

assign icmp_ln35_4_fu_282_p2 = ((tmp_s_fu_272_p4 == 7'd127) ? 1'b1 : 1'b0);

assign icmp_ln35_5_fu_298_p2 = ((tmp_334_fu_288_p4 == 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln35_6_fu_304_p2 = ((tmp_334_fu_288_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln35_fu_160_p2 = ((tmp_fu_150_p4 == 3'd0) ? 1'b1 : 1'b0);

assign in_vec_address0 = zext_ln32_fu_145_p1;

assign in_vec_ce0 = in_vec_ce0_local;

assign mul_ln35_fu_175_p0 = sext_ln35_fu_171_p1;

assign mul_ln35_fu_175_p1 = sext_ln35_fu_171_p1;

assign or_ln35_2_fu_392_p2 = (and_ln35_9_fu_362_p2 | and_ln35_11_fu_386_p2);

assign or_ln35_3_fu_374_p2 = (and_ln35_8_fu_338_p2 | and_ln35_10_fu_368_p2);

assign or_ln35_fu_350_p2 = (xor_ln35_7_fu_344_p2 | tmp_479_fu_244_p3);

assign select_ln35_3_fu_330_p3 = ((and_ln35_fu_258_p2[0:0] == 1'b1) ? and_ln35_7_fu_324_p2 : icmp_ln35_5_fu_298_p2);

assign select_ln35_fu_310_p3 = ((and_ln35_fu_258_p2[0:0] == 1'b1) ? icmp_ln35_5_fu_298_p2 : icmp_ln35_6_fu_304_p2);

assign sext_ln35_2_fu_200_p1 = $signed(shl_ln8_fu_192_p3);

assign sext_ln35_fu_171_p1 = $signed(in_vec_q0);

assign shl_ln8_fu_192_p3 = {{sum_sq_fu_92}, {10'd0}};

assign sum_sq_4_fu_424_p2 = ((and_ln35_9_fu_362_p2[0:0] == 1'b1) ? 18'd131071 : 18'd131072);

assign sum_sq_4_fu_424_p7 = 'bx;

assign sum_sq_4_fu_424_p8 = {{and_ln35_12_fu_406_p2}, {xor_ln35_10_fu_411_p2}};

assign sum_sq_5_fu_217_p4 = {{add_ln35_fu_204_p2[27:10]}};

assign sum_sq_6_fu_238_p2 = (sum_sq_5_fu_217_p4 + zext_ln35_fu_235_p1);

assign sum_sq_out = sum_sq_fu_92;

assign tmp_334_fu_288_p4 = {{add_ln35_fu_204_p2[35:28]}};

assign tmp_476_fu_209_p3 = add_ln35_fu_204_p2[32'd35];

assign tmp_478_fu_227_p3 = add_ln35_fu_204_p2[32'd27];

assign tmp_479_fu_244_p3 = sum_sq_6_fu_238_p2[32'd17];

assign tmp_480_fu_264_p3 = add_ln35_fu_204_p2[32'd28];

assign tmp_fu_150_p4 = {{ap_sig_allocacmp_d_4[5:3]}};

assign tmp_s_fu_272_p4 = {{add_ln35_fu_204_p2[35:29]}};

assign xor_ln35_10_fu_411_p2 = (icmp_ln35_reg_472_pp0_iter1_reg ^ 1'd1);

assign xor_ln35_6_fu_318_p2 = (tmp_480_fu_264_p3 ^ 1'd1);

assign xor_ln35_7_fu_344_p2 = (select_ln35_fu_310_p3 ^ 1'd1);

assign xor_ln35_8_fu_356_p2 = (tmp_476_fu_209_p3 ^ 1'd1);

assign xor_ln35_9_fu_380_p2 = (or_ln35_3_fu_374_p2 ^ 1'd1);

assign xor_ln35_fu_252_p2 = (tmp_479_fu_244_p3 ^ 1'd1);

assign zext_ln32_fu_145_p1 = ap_sig_allocacmp_d_4;

assign zext_ln35_fu_235_p1 = tmp_477_reg_488;

endmodule //unet_pvm_top_forward_20_Pipeline_VITIS_LOOP_32_2
